### ISSUE TITLE
how to use "class" keyword

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/cppwinrt#104]
In the provided examples,  all implementations are placed in a structure. I really want to try "class" since it supports standard c++. The compiler is complaining that something can not be in private. Question, what methods have been put in private in default. 
![image](https://cloud.githubusercontent.com/assets/6119906/22892842/e49812b4-f1e1-11e6-801b-a6d5cfafdf52.png)

**Comment by KevinWelton** [comment]
class and struct are both standard c++, with the only difference being the default accessor. Public for structs, private for classes.

I strongly suggest you use a struct to void the pain of switching visibility for different members. The implements<> structure App inherits from uses [CRTP ](https://en.wikipedia.org/wiki/Curiously_recurring_template_pattern) in the library's innards to actually invoke a user-defined overload of an interface method, such as those in your program above. 

Otherwise you will need to make sure that you add public: before any of the interface overloads are defined, and change "implements<IFace1, IFace2, ...>" to "public implements<IFace1, IFace2, ...>.

Your life will be easier using struct.
