### ISSUE TITLE
Specialization of 'std::formatter<winrt::Windows::Foundation::IStringable, wchar_t>' breaks with conformant compilers

### ISSUE THREAD

**Issue by dunhor** [microsoft/cppwinrt#1069]
E.g. when building with Clang 13 & the standard conformance flags, I see the error:
```
include\winrt/impl/Windows.Foundation.1.h(245,68): error: function 'ToString' with deduced return type cannot be used before it is defined
        return std::formatter<winrt::hstring, wchar_t>::format(obj.ToString(), fc);
                                                                   ^
include\winrt/impl/Windows.Foundation.0.h(864,34): note: 'ToString' declared here
        WINRT_IMPL_AUTO(hstring) ToString() const;
```
Seems that it's because the definition of `consume_Windows_Foundation_IStringable<D>::ToString` is defined in the "normal" `winrt/Windows.Foundation.h` header, but all of the `winrt/impl/*.h` files are included first, and one of these is the header trying to consume the function in question.

**Comment by sylveon** [comment]
Shouldn't it work if you include `winrt/Windows.Foundation.h` before making use of std::format?

**Comment by dunhor** [comment]
This break is caused simply by including `winrt/Windows.Foundation.h`. No use of `std::format` is necessary

**Comment by dunhor** [comment]
I'd assume that this is because `IStringable::ToString` is not dependent on any template parameter and so the compiler needs to know the return type, which it can't because the function is only declared at that time with an `auto` return type. The fix is to either not declare the function with an `auto` return type (probably not going to happen) or to define the specialization after the function's definition.

**Comment by dunhor** [comment]
E.g. see https://godbolt.org/z/fnWK4bnb9

**Comment by sylveon** [comment]
Moving it to `winrt/Windows.Foundation.h` would cause issues because specializations are generated for types which implement `IStringable` and they depend on the base specialization, but the header for those doesn't necessarily include `winrt/Windows.Foundation.h`, while it does include `winrt/impl/Windows.Foundation.1.h`.

Two different ideas for a fix:

- Forward declare the specialization at the existing location, then implement `formatter::format` in `winrt/Windows.Foundation.h`, using the same `auto` trick as is used currently in other methods to avoid linker errors.
- Make `formatter::format` a template (and make `obj` depend on it), to prevent expansion until use.

In both cases, users will still need to include `winrt/Windows.Foundation.h` to use `std::format`, but this isn't anything new, they already have to do that to e.g. await `IAsyncOperation`.
