### ISSUE TITLE
Improve the IDE experience of attaching an event handler

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/cppwinrt#1083]
In C# and C++/CX, you could simply enter += and Visual Studio will automatically add a handler for the event. Whereas in C++/WinRT, unless when working with the XAML designer, I've to first lookup the type of the event, find its signature, write a method in the header file, create an implementation in the source file and then attach it. Consider providing an editor extension in the VSIX to simplify this scenario (C++/WinRT uses function-like syntax for attaching event handlers but still some help could be provided by the VSIX.

**Comment by pjmlp** [comment]
You will find several requests to give C++/CX like tooling experience to C++/WinRT on Developer Community, WinUI, AppSDK.

It is of no use, the ATL like development experience from Visual C++ 6.0 days seems to be the global maximum for C++/WinRT tooling.

The whole IDL, XAML workflow has hardly changed since 2015.

**Comment by kennykerr** [comment]
See https://github.com/microsoft/cppwinrt/issues/1085#issuecomment-1004235012
