### ISSUE TITLE
Is there a general solution to add external libs to UWP app

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/cppwinrt#110]
I love the idea of C++/WinRT. But I really want to know how to add additional libs to C++/WInRT UWP. e.g. opencv, opencl,  I find a solution here : https://github.com/Microsoft/opencv, but it seems to be not supporting Windows 10.

**Comment by walbourn** [comment]
There looks to be a [branch](https://github.com/Microsoft/opencv/blob/winrt/README.md) for WinRT which presumably is a C++/CX (``/ZW``) version for UWP.

Since C++/WinRT is just C++, you can link a C++/WinRT application with any C/C++ code that builds with VS 2015, uses the UWP API partition, and passes the WACK tool. It can be built with or without ``/ZW``. This is really more an issue of getting libraries to support UWP rather than specific to C++/WinRT.

**Comment by bigdimboom** [comment]
Thank you for the replay. What is UWP API Partition? How do I make a library support UWP? Can you give a link that could explain the process. I'm really new to the UWP application. Is there any project setup document I can read? Or, do you have a CMakeList file I can study.
