### ISSUE TITLE
[question] c++ winrt coroutine lambda issue

### ISSUE THREAD

**Issue by IVVOVVI** [microsoft/cppwinrt#1131]
1. Create a blank UWP or WinUI 3 project.

2. Edit ClickHandler(IInspectable const&, RoutedEventArgs const&) in MainPage.cpp (UWP) or MainWindow.xaml.cpp (WinUI 3).

`[strong_this = get_strong()]()->fire_and_forget`
`{`
`    apartment_context ui_thread;`
`    co_await resume_background();`
`    co_await ui_thread;`
`    strong_this->myButton().Content(box_value(L"Clicked"));`
`}();`

Why does this code crash? But the following code will not.

`[this]()->fire_and_forget`
`{`
`    auto const strong_this = get_strong();`
`    apartment_context ui_thread;`
`    co_await resume_background();`
`    co_await ui_thread;`
`    strong_this->myButton().Content(box_value(L"Clicked"));`
`}();`

**Comment by sylveon** [comment]
The lambda is destructed upon reaching the first suspension point, so captures become invalid while local variables are still fine (because those are saved in the coroutine frame). Generally, lambdas should be avoided with coroutines.

**Comment by sylveon** [comment]
> But according to the C++ standard, the lifetime of captures should extend to the end of the lambda body

This is incorrect. The lifetime of captures ends when the lambda functor object is destroyed. The issue is, most code gets rid of the lambda as soon as the call returns, which in the case of coroutines is the first suspension point. The C++ Core Guidelines specifically call this out: https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rcoro-capture

It's a language issue, not a C++/WinRT issue.

The reason for using lambdas for async code in C++/CX was because there was no native support for awaiting, so PPL and callback chaining was used. In C++/WinRT, you can instead write normal functions that `co_await`, almost like you would in C#.

**Comment by IVVOVVI** [comment]
So this C++ WinRT coroutine is a standard C++20 coroutine, right? Even if my project is WinUI 3 with C++17 language standard, am I still using standard C++20?

**Comment by IVVOVVI** [comment]
Got it. Thank you for your help.
