### ISSUE TITLE
Propose make more threadsafe assignment operators

### ISSUE THREAD

**Issue by afrankeser** [microsoft/cppwinrt#1137]
Problem:
One thread is reading the IUnknown while the other thread is assigning a new pointer. For the reading thread it is possible to get a nullptr instead the old/new pointer.

The writing thread called release_ref (line 166) and enters line 167, now m_ptr is nullptr.
Then the reading thread calls the as() function and retrieves the value of m_ptr (now nullptr).
The writing thread assigns m_ptr to the new value (line 167).
_base_windows.h_
```
162  IUnknown& operator=(IUnknown const& other) noexcept
163  {
164     if (this != &other)
165     {
166         release_ref();
167         m_ptr = other.m_ptr;
168         add_ref();
169    }
170 
171    return*this;
172 }
```
Same problem in the _com_ptr::copy_ref (base_com_ptr.h)_ implementation.

Here I propose a more threadsafe implementation, which the STL _shared_ptr_ also uses.
```
IUnknown& operator=(IUnknown const& other) noexcept
{
    IUnknown tmp(other);
    swap(tmp, *this);
    
    return*this;
}
```

**Comment by Jaiganeshkumaran** [comment]
If you just swap, how will you call add_ref?

**Comment by tim-weis** [comment]
> If you just swap, how will you call add_ref?

@Jaiganeshkumaran Doesn't `IUnknown tmp(other);` do that for us? Which, if it did, would then still be [thread-compatible](https://youtu.be/s5PCh_FaMfM?t=1216) (I'm guessing...). Unless I'm missing something obvious. Or subtle.

---

Though, I did learn a different trick, a while back, from Arthur O'Dwyer's CppCon 2019 talk "RAII and the Rule of Zero": [By-value assignment operator](https://youtu.be/7Qgd9B1KuMQ?t=2145).

The proposition he makes is to conflate copy- and move-assignment into a single by-value assignment operator:

```cpp
IUnknown& operator=(IUnknown rhs) noexcept
{
    rhs.swap(*this);
    return *this;
}
```

The audio goes on to explain:

> Arthur O'Dwyer: "In C++, when I take by value, rather than by reference, that makes a copy. Or maybe it makes a move. Right? That's up to the caller."

I'm guessing this is in reference to guaranteed [copy elision](https://en.cppreference.com/w/cpp/language/copy_elision), mandated as of C++17. I will not pretend to have understood even a fraction of the referenced document, and most certainly not even a fraction of a fractional of any of its ramifications.

Meanwhile, the accompanying talk slides move on to proclaim:

> I'm not aware of any problems with this idiom.

Neither am I. But, like, ... let's not kid ourselves.

This is C++, and when it comes to making predictions about what code written *should* correspond to object code being executed, "being wrong" is the default.

---

That out of the way, could the actual solution be as simple as "replacing code with less code"? Or is there even a problem that needs to be solved to begin with?

I'm confident that @kennykerr and @oldnewthing can answer any of those question. And raise new ones, too!

**Comment by sylveon** [comment]
I think the by value operator is best as it does indeed avoid doing a needless add_ref when assigning a rvalue:

```cpp
IUnknown GetFoo();

IUnknown foo;
// The return value of GetFoo is moved into the assignment operator, eliding a add_ref
foo = GetFoo();
```

**Comment by kennykerr** [comment]
Feel free to contribute such a change - note that both `com_ptr` and `IUnknown` have similar functionality and should ideally be consistent.

**Comment by MikeGitb** [comment]
Correct me if I'm wrong, but none of the suggested solutions is threadsafe and it is language level UB to have an assignment in one thread an a read in another thread without a synchronization primitive in between (e.g. a mutex).

The fact that you get an unexpected nullptr could be seen as a red flag, because the user code has a bug, no matter how the assignment operator is implemented. 


Btw.: "Thread compatible" just means that your type doesn't do anything crasy and e.g. two threads can read from it at the same time without having a data race.

**Comment by MikeGitb** [comment]
> > I'm guessing this is in reference to guaranteed [copy elision](https://en.cppreference.com/w/cpp/language/copy_elision), mandated as of C++17. I will not pretend to have understood even a fraction of the referenced document, and most certainly not even a fraction of a fractional of any of its ramifications.

Has nothing to do with c++17. It works just as well with c++11. The only drawback of this pattern is that it makes copy/move assignment a tad more expensive (depending on what the optimizer does), but I guess, you won't notice that in most code that uses Windows API.

**Comment by sylveon** [comment]
> It works just as well with c++11.

Yes, but C++17 has made it mandatory for compilers to implement. It was implementation details prior to that.

**Comment by MikeGitb** [comment]
>   >It works just as well with c++11.
>
> Yes, but C++17 has made it mandatory for compilers to implement. It was implementation details prior to that.

I don't think c++17 changed anything relevant to the code in question. But I may be wrong.

**Comment by tim-weis** [comment]
> none of the suggested solutions is threadsafe and it is language level UB to have an assignment in one thread an a read in another thread without a synchronization primitive in between

That's what confused me, too, @MikeGitb. The only way to run into the data race this change request is motivated by is, if you are holding an `IUnknown*` to the same instance in more than one thread. That would be a bug in client code much like sharing a `std::shared_ptr<T>*` to the same instance across multiple threads is. It is not something that library code can fix.

That's what I was thinking of when saying:

> Or is there even a problem that needs to be solved to begin with?

**Comment by afrankeser** [comment]
@tim-weis and @MikeGitb you are totally right. It is a threading problem and the client code can fix the problem using lock at any point where an assignment takes place (for data shared between threads).
Nevertheless, `shared_ptr<T>` solves this better because it does not have the problem of becoming temporary nullptr on assignment due to the copy-swap implementation.

@tim-weis no IUnknown* is shared but IUnknown. Anyway in our case there are several reading threads and only one writing thread. The reading threads don't care if they read the old or new instance, but they should definitely never read nullptr.
Also the comparison on the same address can be problematic and is also solved by the copy-swap ideom (see https://youtu.be/7Qgd9B1KuMQ?t=854). Thanks for the video @tim-weis.

**Comment by sylveon** [comment]
You should use a slim reader writer lock to control access to the IUnknown global then.

**Comment by MikeGitb** [comment]
@afrankeser:

> Anyway in our case there are several reading threads and only one writing thread. The reading threads don't care if they read the old or new instance, but they should definitely never read nullptr.

Just to make sure: Are you aware that even something simple as 

    int global = 0;

    void thread1(){
        global = 5;
    }
    void thread2(){
        std::cout << global << std::endl
    }
    
is invalid c++ and undefined behavior? In practice, it will almost certainly print either 0 or 5, but in principle ,the program is allowed to do whatever it wants, including formatting your hard drive.
In order to get the semantic that you seem to expect, global would have to be an atomic variable:

    std::atomic<int> global = 0;
    

or **both** read and write need to be guarded by some synchronization primitive. The same is true, if global would be a std::shared_ptr btw.

All that being said: I'm not in any way opposed to changing the implementation of the assignmnt operator. I'm just trying to point out that - from what you are describing - your client code has a bug, no matter what the new implementation will look like (unless IUnknown is going to make `m_ptr` an atomic variable) .

**Comment by afrankeser** [comment]
@MikeGitb you are right. We are totally aware of the race condition and we will find a good solution for our issue on the client side.

**Comment by Jaiganeshkumaran** [comment]
Could we have something std::atomic but for C++/WinRT projected types to simplify multi-thread access? They are really pointers under the hood but since it's wrapped in an RAII wrapper, it won't let you use it with std::atomic.

**Comment by kennykerr** [comment]
Note that while I'm supportive of a change to adopt `swap` or some other modern implementation, we cannot fundamentally change the nature of COM interface pointer ownership. A COM interface pointer, as others have mentioned, is not "thread safe" even if the object being pointed to is thread safe. Even if you were to create an `atomic` wrapper for a COM interface pointer, it wouldn't fundamentally improve the situation since the lifetime of a COM interface pointer must extend to any synchronous function calls made through that pointer but holding a lock while calling arbitrary code is not a great idea. Have a look at `winrt::event` for a glimpse at some of the complexities of doing that.
