### ISSUE TITLE
InitializeComponent is not called for base classes.

### ISSUE THREAD

**Issue by sylveon** [microsoft/cppwinrt#1140]
With #1130, `InitializeComponent` is now called internally as part of `winrt::make` instead of within the constructor. This means that the following scenario, by default, does not work anymore:

- Class A is a base class using XAML.
- Class B derives from class A in metadata, and uses XAML too.
- Both are within the same project, so `implementation::B` directly derives from `implementation::A`, instead of using WinRT composition.

C++/WinRT will call class B's `InitializeComponent` function, but the XAML compiler did not generate code in class B's `InitializeComponent` function to call class A's `InitializeComponent` function. As a result, nothing from class A is loaded: none of the XAML is visible, no event handlers are attached, `x:Bind` bindings are not set up, trying to access a `x:Name`'d control gives `nullptr`, ets.

To fix this, a user has to explicitly go and add the following in `implementation::B`:
```cpp
void B::InitializeComponent()
{
    A::InitializeComponent();
    BT::InitializeComponent();
}
```

These kinds of things should be transparent to the user.

**Comment by sylveon** [comment]
Worse even, this still doesn't work if XAML calls back to the type (most notably, used for x:Bind), as instead of calling class A's `Connect` when in `A::InitializeComponent`, it will call class B's `Connect`, which is wrong. This worked previously before because by the point `A::InitalizeComponent` was called, B's vtable didn't exist yet, so it correctly called A's `Connect`.

**Comment by roxk** [comment]
While I think manually adding `InitializeComponent` makes sense given that's how inheritance/shadowing work in C++, it's compatibility with the xaml runtime is ultimately broken for now.

On top of the above issue, in my testing, `LoadComponent` isn't even called for the derived class. Inside `DerviedT::InitializeComponent`, `_contentLoaded` is already `true` since `Base::InitializeComponent` had set it, thus skipping the call.

While I personally don't recommend using inheritance for composing UI, and there are other workarounds (namely, don't inherit classes from the same project), inheriting pages within the same project is [explicitly documented](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/move-to-winrt-from-csharp#derived-classes) and this breakage would confuse lots of users.

Modifying xaml compiler to explicitly quality every such variables like `_DerivedT_contentLoaded` might work, but this fix is going to take a long time to ship. And it doesn't even solve the issue of xaml runtime calling `DerivedT::GetBindingConnector` even in `Base::InitializeComponent`.

**Comment by Scottj1s** [comment]
@sylveon, thanks for opening the issue - can you put together a simple repro?

**Comment by sylveon** [comment]
Here's a repro:
[InitializeComponentRepro.zip](https://github.com/microsoft/cppwinrt/files/8579074/InitializeComponentRepro.zip)

You'll notice, when clicking on "Navigate to DerivedPage", that the app turns blank. This is because `DerivedPageT`'s `InitializeComponent` will be called by cppwinrt, but not `BasePageT`'s `InitializeComponent`. So `Page`'s `Content` is never set (because it is set by `BasePage`), resulting in an empty page.

Now if we go and uncomment the `InitializeComponent` in `DerivedPage.h` and `DerivedPage.cpp`, and rerun the app, we will see that navigating to `DerivedPage` will instead crash the app, with an `hresult_no_interface` exception. This happens within `DerivedPageT::Connect`. It is trying to cast the `ContentPresenter` from `BasePage` to a `TextBlock`. The XAML framework was expecting to call `BasePageT::Connect` to connect the `x:Bind`, since it's currently loading up `BasePage`, but ends up calling `DerivedPageT::Connect` since `DerivedPage`'s vtable is fully formed (because we are outside the constructor).

**Comment by sylveon** [comment]
@roxk's comment about `_contentLoaded` being set is not a naming conflict, but rather that when the XAML framework wrongfully calls `DerivatePageT::Connect`, it somehow succeeds (for example, there is no `x:Name`'d element, no event handler, and no `x:Bind` in `DerivedPage`, so there is nothing for `Connect` to actually do), and sets `_contentLoaded` to true.

**Comment by Scottj1s** [comment]
Thanks - investigating

**Comment by sylveon** [comment]
As a temporary workaround, we can keep the `InitializeComponent()` call within the constructor for all `unsealed` runtime classes.

**Comment by Scottj1s** [comment]
@sylveon, thanks for your patience.  I should have time to look at this next week.  Glad you have a workaround.
