### ISSUE TITLE
IVectorView from singled_threaed_vector ItemSource problem when cosumed from  C++/CX

### ISSUE THREAD

**Issue by brabebhin** [microsoft/cppwinrt#1164]
Hi,

We are currently porting a large-ish windows runtime component from C++/CX to C++/winrt.
We have some sample apps that show how to use the library, one of the sample apps is written in C# and the other in C++/CX.

One of our runtime classes in the runtime component returns an IVectorView<Some class>, and that IVectorView doesn't want to work as an ItemSource for a listview in the C++/CX project, but works perfectly fine in the C# sample.

Now, I fixed the issue by creating the IVectorView<Some class> using winrt:: single_threaded_observable_vector backing collection instead of single_threaded_vector. This seems like a rather odd behavior, since it works fine with C# sample, but not with the C++/CX sample.

You can find the sample to reproduce here:
https://github.com/ffmpeginteropx/FFmpegInteropX/tree/cpp-winrt-strange-binding-problem

Simply run the MediaPlayerCpp sample and you will get the exception.

Thanks.

**Comment by kennykerr** [comment]
This stems from the fact that the default `IVector` and `IVectorView` implementations in C++/WinRT share a COM identity and return the same value for `GetRuntimeClassName` that is used by C# to determine the type of the collection at runtime. If you have a workaround great. Otherwise, you can also use the `implements` class template to implement `IVectorView` without `IVector` and it will return the correct value for `GetRuntimeClassName` as well.

**Comment by brabebhin** [comment]
But I still don't understand why C++/CX can't do the same as C#. There has to be a bug somewhere,  returning a read-only view of a collection is one of the most basic principles of OOP, which C++ (and by extension, C++/winRT) is all about.

**Comment by kennykerr** [comment]
For the broader question I'd suggest you ask over on https://stackoverflow.com/ as it spans different languages and runtimes. This repo is focused on reporting issues with cppwinrt itself and you'll get more eyeballs on you question over on stackoverflow.

**Comment by lukasf** [comment]
@kennykerr Thank you for your responses, but I did not really understand you explanation. This is the situation:

From C++/CX App:
- DataBinding to IVectorView (C++/CX) -> Does work
- DataBinding to IVectorView (C++/WinRT) -> Does NOT work
- DataBinding to IVectorView from ObservableVector (C++/CX) -> Does work
- DataBinding to IVectorView from ObservableVector (C++/WinRT) -> Does work

From C# App:
- DataBinding to IVectorView (C++/CX) -> Does work
- DataBinding to IVectorView (C++/WinRT) -> Does work
- DataBinding to IVectorView from ObservableVector (C++/CX) -> Does work
- DataBinding to IVectorView from ObservableVector (C++/WinRT) -> Does work

It is strange that 
- IVectorView from normal vector behaves different than IVectorView from observable vector. They should both work without any limitations in data binding scenarios.
- IVectorView from C++/WinRT behaves different than IVectorView from C++/CX (although they are the exact same interface!)
- IVectorView from C++/WinRT behaves different in C#, compared to C++/CX

These are a lot of strange differences. I did not find any documentation on these. Are these known limitations or known bugs? If you do not consider this irregular behavior a bug, then should it not at least be documented?

**Comment by kennykerr** [comment]
Thanks for the table. So this looks like the only one that doesn't work:

> C++/CX DataBinding to C++/WinRT IVectorView

So it appears to be specific to C++/CX which is no longer under development but feel free open an issue here: 

https://developercommunity.visualstudio.com/search?space=62

But more specifically, the question is specific to Xaml so feel free to open an issue with the Xaml team:

https://github.com/microsoft/microsoft-ui-xaml/issues

Sorry I can't be more help but there are many many moving parts to Xaml so they'll have to dig into this. On the other hand, if you're moving away from C++/CX then all should be well, and it may not be worth spending hours debugging. 😉

**Comment by kennykerr** [comment]
Understood. Again, you are free to ditch `single_threaded_vector` if it does not serve you well. This is just a helper implementation for some common scenarios but is not ideal everywhere particularly with interop due to the reasons I previously mentioned. If all you need is a view, it is not hard to implement `IVectorView` directly.

**Comment by brabebhin** [comment]
> Understood. Again, you are free to ditch single_threaded_vector if it does not serve you well. This is just a helper implementation for some common scenarios but is not ideal everywhere particularly with interop due to the reasons I previously mentioned. If all you need is a view, it is not hard to implement IVectorView directly.

Our current work around with observable_vector seems to work fine, but the reason we are kind of worried about this is that we do not understand why and changes that are out of our control and any changes might break it. Officially documenting such corner cases could be good.

**Comment by kennykerr** [comment]
Sure, I'm just not sure why that would affect the behavior in your case, but Xaml does treats observable collections in a special way so that's not too surprising. I can't document the behavior of Xaml and why it likes one implementation over another. That's for the Xaml team to document as needed. 

C++/WinRT is very stable at this point and these implementations in particular are unlikely to change specifically to avoid destabilizing existing code.
