### ISSUE TITLE
Projection requires .net interfaces

### ISSUE THREAD

**Issue by asklar** [microsoft/cppwinrt#1177]
This may be a bug in the winmd parser, so cc @DefaultRyan 

Setup:
- .net Windows runtime component with a single class MyClass
- produce the winmd (change the output type to runtime component in project properties)
- Reference it from a C++/WinRT project, add it to the list of winmds considered for component generation:
   ```xml
      <CppWinRTMdMergeInputs Include="$(SolutionDir)bin\$(Configuration)\MyAssembly.winmd">
        <IsWinMDFile>true</IsWinMDFile>
      </CppWinRTMdMergeInputs>
   ```
- Implement the class in C++/WinRT - observe the error about `MyClass`  not implementing `ToString()` 

The metadata has two copies of `MyClass`, one for .net and one for winrt; it seems the winmd parser isn't filtering out the .net metadata correctly.

Looking at MyClass.g.h:
```cpp
    template <typename D, typename... I>
    struct __declspec(empty_bases) MyClass_base : implements<D, MyAssembly::MyClass, winrt::Windows::Foundation::IStringable, I...>
``` 
Note how it calls out IStringable.

**Comment by sylveon** [comment]
This seems like not a bug to me - the .NET Framework WinRT support will add IStringable to the generated metadata of every C# Windows Runtime class, because every C# class has ToString via System.Object. It may be unexpected if trying to produce from cppwinrt a class whose metadata was defined in C#, but all tooling agrees that MyClass does implement IStringable. At runtime, if using a C# implementation of that class, it will of course succeed and end up calling System.Object.ToString

It seems there is another bug in mdmerge where it doesn't like the CompilerGenerated attribute in the C#-generated winmd, but it seems exclusive to mdmerge, as C++/CX, winmdidl, C++/WinRT all handle/ignore this attribute with no issues.

**Comment by kennykerr** [comment]
Yes, its not obvious this is a bug in cppwinrt.
