### ISSUE TITLE
AppRecordingManager.GetStatus got "winrt::hresult_error at memory location 0x0000002A2E8FF728."

### ISSUE THREAD

**Issue by luyimin** [microsoft/cppwinrt#1220]
Excuse me, for personal use, I need to get current Screen is being Recording or not.
So I would like to use the following WinRT API to achieve it: [Windows.Media.AppRecording](https://learn.microsoft.com/en-us/uwp/api/windows.media.apprecording?view=winrt-22621)

I Create a C++/WinRT template to experiment what I need. 
![image](https://user-images.githubusercontent.com/17100800/197733587-e70e7d49-4a55-42e9-a7e0-a952a1b4117d.png)

The following is my main.cpp.

```cpp
#include "pch.h"
#include <winrt/Windows.Media.AppRecording.h>
using namespace winrt;
using namespace winrt::Windows::Foundation;
using namespace winrt::Windows::Storage;
using namespace winrt::Windows::Media;

int main()
{
    init_apartment();
    //Uri uri(L"http://aka.ms/cppwinrt");
    //printf("Hello, %ls!\n", uri.AbsoluteUri().c_str());
    AppRecording::AppRecordingManager AppRecordingManager = AppRecording::AppRecordingManager::GetDefault();
    AppRecording::AppRecordingStatus AppRecordingStatus = AppRecordingManager.GetStatus(); //<------- I Got Exception here.
    bool canRecord = AppRecordingStatus.CanRecord();
    return 0;
}


```

but I got this Exception during runtime:
![image](https://user-images.githubusercontent.com/17100800/197731476-cc3eeb81-0321-4095-a4ad-52fa955a60b7.png)

`Unhandled exception at 0x00007FF85C80428C in ConsoleApplication3.exe: Microsoft C++ exception: winrt::hresult_error at memory location 0x000000D8F12FF8D8.`

My Environment
Visual Studio Perfessional 2022 17.3.6
windows SDK: (change version still encounter)
- 10.0.18362.0 
- 10.0.19041.0 
- 10.0.17763.0

C++ lang standard: 
- **ISO C++20 Standard (/std:c++20)** or **ISO C++17 Standard (/std:c++17)**

packages.config:
```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Microsoft.Windows.CppWinRT" version="2.0.220531.1" targetFramework="native" />
</packages>
```

Can someone tell which part is wrong, or it is a issue?

**Comment by kennykerr** [comment]
You're having an issue with a specific API rather than with C++/WinRT itself. The way to start debugging this is to figure out what error information the API provided. You might try something like this:

```C++
int main()
{
    try
    {
        AppRecording::AppRecordingManager AppRecordingManager = AppRecording::AppRecordingManager::GetDefault();
        AppRecording::AppRecordingStatus AppRecordingStatus = AppRecordingManager.GetStatus();
    }
    catch (hresult_error const& e)
    {
        printf("(0x%x) %ls\n", e.code().value, e.message().c_str());
    }
}
```

Now you can print out the error. Alternatively, you can hook up a debugger and see the error information directly. Anyway, the call seems to fail with: `(0x80070490) Element not found.`

What that means depends on the API you're using and I'm unfortunately not familiar with this one. You can try [stackoverflow.com](https://stackoverflow.com/) or [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/topics/windows-api.html).
