### ISSUE TITLE
winrt/Windows.Foundation.h and winrt/bash.h is not compatible with clang compiler

### ISSUE THREAD

**Issue by benjycui** [microsoft/cppwinrt#1237]
Our project is compiled by clang, and we found that Windows.Foundation.h and bash.h is not compatible with clang.

![image](https://user-images.githubusercontent.com/3580607/203887199-bdd85e4e-47b8-4102-9c47-37649bb177fc.png)

**Comment by sylveon** [comment]
Use the NuGet package to generate the headers instead of the pre-generated files from the SDK. These should be compatible with Clang.

(note that supporting Clang is a community effort and [cppwinrt's official stance](https://learn.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/faq#can-i-use-llvm-clang-to-compile-with-c---winrt-) still is that it's unsupported iirc)

**Comment by kennykerr** [comment]
Yes, the version in the Windows SDK is generally quite old and should not be used. Please use the latest version available here:

https://www.nuget.org/packages/Microsoft.Windows.cppwinrt
