### ISSUE TITLE
converting c++/cx examples to winrt/c++ examples, is there a plan of?

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/cppwinrt#128]
It's a question not an issue. Do you guys have plans of entirely translating c++/cx samples to winrt/c++ samples. Are you going to add document support for winrt/c++.

**Comment by walbourn** [comment]
Which samples in particular are you talking about? Every C++ sample on [Universal-windows-samples](https://github.com/Microsoft/Windows-universal-samples)? [DirectX-Graphics-Samples](https://github.com/Microsoft/DirectX-Graphics-Samples)? [Xbox-ATG-Samples](https://github.com/Microsoft/Xbox-ATG-Samples)?

**Comment by bigdimboom** [comment]
I think, the best fit questions for this is, "do you have a lookup table"  for all the c++/cx counter parts winrt/c++. For example, what is the equivalent for "Platform::String^" in winrt/c++.

**Comment by walbourn** [comment]
Have you read through [this doc](https://github.com/Microsoft/cppwinrt/blob/master/Docs/Migrating%20C%2B%2B%20CX%20source%20code%20to%20C%2B%2B%20WinRT.md)?

**Comment by bigdimboom** [comment]
Yes, I did. Does it cover everything? For example, what is difference between "winrt::hstring" and "winrt::hstring_view" ?  How do I translate this into winrt/c++? 
![image](https://cloud.githubusercontent.com/assets/6119906/23728094/0052dde6-0429-11e7-83c0-2cf2e00dc948.png)

BTW, a long type "messageNumber" calling a "ToString" method really does not make sense to me. COde is from one of the c++/cx example.
![image](https://cloud.githubusercontent.com/assets/6119906/23728126/2e322370-0429-11e7-82b8-d035553045a7.png)

**Comment by BrentRe** [comment]
We do not support C++/CX here so, in general, will not answer C++/CX specific questions.

But I can answer your question as to the difference between `winrt::hstring` and `winrt::hstring_view`. The C++/WinRT type `winrt::hstring` is our C++ representation of the Windows Runtime `HSTRING` type.

In addition to encapsulating a Windows Runtime `HSTRING` value, the `winrt::hstring` type provides a number of conversion operators to standard C++ library types. As a result, your code typically will not directly use `winrt::hstring` (though it can) but instead will oftern use `std::wstring` or other familiar C++ types as they provide many additional string functions.

E.g. for the method:

```winrt::hstring MyMethod();```

You'd typically just assign the result to a standard string type:

```std::wstring result = obj.MyMethod();```

Now you can use all the standard library string functions on `result`.

Our `hstring_view` type is our C++ representation of a string *parameter* to a Windows Runtime API. 

E.g. for the method:

```void MyMethod2(winrt::hstring_view arg);```

You'd typically call it like this:

```std::wstring arg = L"C++\WinRT is the greatest!";```
```winrt::hstring arg2 = L"C++\WinRT is the greatest!";```

```obj.MyMethod2 (arg);```
```obj.MyMethod2 (arg2);```

Or simply:

```obj.MyMethod2 (L"C++\WinRT is the greatest!");```

Why did we invent the `winrt::hstring_view` type when we already have `winrt::hstring` and why use the former, instead of the latter, for the type of string parameters?

A `winrt::hstring` object holds a string for the lifetime of the object. When you use `winrt::hstring` as a parameter, the calling code needs to make a copy of the string argument in order to pass the copy as the parameter. Additionally, when the function returns, the code must then destruct the argument, releasing the copy of the string. If the parameter type in the example previously was `winrt::hstring`, the compiler would be making a copy of the string, calling the method, then releasing the copy of the string. That's not efficient.

Therefore, we use the `winrt::hstring_view` type for parameters. This type, as it's only used for parameters, can avoid the string copy. In effect, `winrt::hstring_view` references the original copy of the string. Then, when the function call returns, we only need to destruct the `hstring_view` object, which, being a value type, is extremely efficient. We do not have a copy of the string to release.

The other `*_view` classes, like `array_view`, work similarly.
