### ISSUE TITLE
co_await and IAsync::get() difference

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/cppwinrt#130]
co_await suspend the current executing function.
IAsyncAction::get() or IAsyncOoperation<...>::get block the current executing thread.

suspension on a function also blocks the rest of code in a function to be executed. 

so what's the difference between these two concepts in simple example.

**Comment by kennykerr** [comment]
The `co_await` suspension is cooperative. While it prevents further execution of the current function (coroutine), it returns execution back to the caller immediately so that it doesn't block the progress of the thread itself. The `get()` suspension is not cooperative. It blocks execution of the calling thread indefinitely.

**Comment by bigdimboom** [comment]
another way of playing around and to understand the co_await behavior is to use "F10 step over". It shows that co_await directly returns execution back to caller and will come back to this moment later.
