### ISSUE TITLE
 coroutine discussion and a hypothetical scenario 

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/cppwinrt#131]
The example from your CPPCON talk:
![image](https://cloud.githubusercontent.com/assets/6119906/23800947/3e6e7d02-057c-11e7-9c6b-09cdf7c723da.png)

And, my modification to the "BackgroundAsync":
![image](https://cloud.githubusercontent.com/assets/6119906/23801070/b0faf15c-057c-11e7-9c8c-3de2e67a4ada.png)

So, heperthecially, I have many "co_await"s in a co_routine; the only necessary co_await is the fist one, the rest of the co_awaits can be converted into "Async::get()". Am I right?

Another question is, performance-wise speaking, are these two version the same?

**Comment by AlexBAV** [comment]
Placing .get() everywhere you just make everything synchronous.

`co_await` is easily understandable if you rewrite the code (in mind) according to the following rule:

```
co_await A();
co_await B();
co_await C();
```

into the following:

```
A().then([] { B() }).then([] { C(); })
```

That is, consider everything after `co_await expr;` to be a _continuation_ of the previous statements.

**Comment by kennykerr** [comment]
The co_await version will also be more efficient as each continuation is not forced onto the same thread and the thread pool itself is not blocked indefinitely, resulting in a more scalable implementation.

**Comment by wizarrc** [comment]
I think @bigdimboom is confused. I'm pretty sure that when traversing a stack, and every function in the stack is awaited, only the top level in the stack needs to be awaited where lower levels in the stack, if there are no operations after the co_await can be done synchronously up the call stack, because you are just awaiting one asynchronous operation, no need to co_await all the way up. The example he gave is different as each operation is a separate asynchronous task and each task should be awaited.
