### ISSUE TITLE
Bug: In some situations, calling get_weak() may over-release the "outer" object

### ISSUE THREAD

**Issue by JesseCol** [microsoft/cppwinrt#1431]
### Version

2.0.240405.15

### Summary

There seems to be an issue where get_weak() will over-release the "outer" object when:
* The object is aggregated/subclassed by a component in a different module or DLL.
* When get_weak() is called, the object is using the external control block for refcounting, rather than keeping the refcount internally.  (the issue doesn't repro when l just call get_weak() in the class's ctor, for example).

In the debugger, for the repro case it appears get_weak()'s net effect on the refcounts is that the inner gets +1 ref count and the "this" gets -1 ref count.

Here's a repro project:
[GetWeakRefCount.zip](https://github.com/user-attachments/files/16549498/GetWeakRefCount.zip)

For best results, enable pageheap for the process before running (as admin: "gflags.exe -i ThermometerCoreApp.exe +hpa").

It is UWP because it's based on the "ThermometerWRC" sample project.

### Expected behavior

I'd expect get_weak() not to effect the strong ref count of the inner or outer objects.

### Actual behavior

In the repro case, when I call get_weak() I'm seeing the outer object lose a strong ref, and the inner object gain a strong ref.

**Comment by kennykerr** [comment]
Spent a bit of time debugging this on my end. A few thoughts before I get back to work and forget all about this. 😉

* C++/WinRT support for weak references is limited to non-composable or at least non-open composable hierarchies. That's because it's implemented by swapping out the ref count on the object while open composable types delegate ref counting to the outer/derived object and thus there's really two ref counts at play and that's not supported by the C++/WinRT weak reference implementation. 
* C++/WinRT support for open/binary composable hierarchies is limited to Xaml. Nothing else has ever been tested nor is it recommended.
* To the best of my knowledge, the base composable type in Xaml has always been implemented in something other than C++/WinRT. Its that base composable type(s) that must implement weak reference support. Derived types cannot do it - they simply delegate to the base.
* You may want to confirm that a derived type in the binary hierarchy isn't accidentally responding to queries for `IWeakReferenceSource`. That would be a big problem.
* You can instruct C++/WinRT not to implement weak reference support for a particular implementation by using the `no_weak_ref` marker type.

**Comment by acoates-ms** [comment]
To work around this issue, would it be possible to implement a base composable type in something other than C++/WinRT, then use C++/WinRT to compose types on top of that?  Similar to what Xaml does?
