### ISSUE TITLE
Bug: Linker error LNK2001 when including winrt/base.h in global module fragment in DLL (WINRT_abi_val, WINRT_get_val and WINRT_version unresolved)

### ISSUE THREAD

**Issue by Optimierungswerfer** [microsoft/cppwinrt#1449]
### Version

2.0.240405.15

### Summary

We are using C++/WinRT in one of our DLLs that is part of a bigger solution and try to contain it to that DLL/vcxproj, so only that project has got the CppWinRT package installed. Then there is our main project, which references the DLL, which has no idea about WinRT. So far, we were using the classic .h/.cpp approach in the DLL and to facilitate this isolation, we pimpled the WinRT classes, which comes with a lot of bloat. With C++20 we now migrated to modules instead, which allows us to use WinRT types in the interface (what was previously the header) without exporting them, so there is no longer a need to pimpl them. To do this, we need to include the WinRT headers in the global module fragment (since WinRT itself is not available as a module yet, see #1123 ). However, if we do that in the module interface file (.ixx), we get linker errors about unresolved symbols WINRT_abi_val, WINRT_get_val, and WINRT_version.

The culprit are the lines winrt/base.h:9654-9660 and winrt/base.h:9670-9673 or more specifically these three preprocessor directives:
```cpp
// ...
#pragma comment(linker, "/include:WINRT_abi_val")
#pragma comment(linker, "/include:WINRT_get_val")
// ...
#pragma comment(linker, "/include:WINRT_version")
// ...
```
which compromise the otherwise perfectly fine working module isolation. When removing those lines, the build succeeds just fine. It also works if this is not done in the module *interface* file (.ixx) but an optional module *implementation* file (.cpp) for the respective module, but then we need to forward / pimpl the types in the interface again, which defeats the whole purpose.

### Reproducible example

```cpp
// MyModule.ixx in MyDLL.vcxproj (Visual Studio DLL project template, /std:c++20, CppWinRT package, "All Modules are Public" = "Yes")
module;

#include <winrt/base.h> // Culprit
#include <iostream>

export module MyModule;

export __declspec(dllexport) void HelloWorld()
{
  std::cout << "Hello World!" << std::endl;
}

// main.cpp in Main.vcxproj (Visual Studio ConsoleApplication template, /std:c++20, references MyDLL.vcxproj, no CppWinRT package)
import MyModule;

int main()
{
  HelloWorld();
}
```

### Expected behavior

No build / link errors.

### Actual behavior

> 2>------ Build started: Project: Main, Configuration: Debug x64 ------
2>main.cpp
2>main.obj : error LNK2001: unresolved external symbol WINRT_abi_val
2>main.obj : error LNK2001: unresolved external symbol WINRT_get_val
2>main.obj : error LNK2001: unresolved external symbol WINRT_version
2>\x64\Debug\Main.exe : fatal error LNK1120: 3 unresolved externals
2>Done building project "Main.vcxproj" -- FAILED.

### Additional comments

It seems like CppWinRT assumes that the importer of a DLL using it, also links against CppWinRT, which is not always the case. And when it's not, the above errors occur.

**Comment by DefaultRyan** [comment]
>It seems like CppWinRT assumes that the importer of a DLL using it, also links against CppWinRT, which is not always the case. And when it's not, the above errors occur.

Not sure what you mean by "links against CppWinRT". It's a header-only library, the definitions for those WINRT_* functions are already present in base.h. Those `#pragma comment(linker, "/include:Foo")` lines are only there to tell the linker to not optimize the functions away due to not being referenced.

> I think this is only used for natvis - [@Scottj1s](https://github.com/Scottj1s) may know whether there's a way to control this.

`WINRT_abi_val` and `WINRT_get_val` is used by the natvis, but it must be present in the binary for the natvis to do it's job. I don't understand enough about how modules work to really get what's happening here.

Seems that the `#pragma comment` lines are only active if `WINRT_NATVIS` is defined, which is true by default in debug builds. But if `WINRT_NATVIS` is defined, then `WINRT_abi_val` and `WINRT_get_val` both have definitions, so I don't get why the linker doesn't find it, but has no issues with the other functions in the projection.

The main difference that comes to mind is that the rest of the projection stuff is prefixed with `WINRT_EXPORT`, but that's not defined to anything by default. Are you defining `WINRT_EXPORT` or something to use modules? Sorry if that's a dumb question.
