### ISSUE TITLE
runtime assertion for c++/winrt

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/cppwinrt#150]
what is the runtime assertion call in c++/winrt headers.

**Comment by walbourn** [comment]
Can you provide more details of what assertion you are seeing?

**Comment by bigdimboom** [comment]
I mean, I want to use "runtime assertion" in my code. What is the conversion for using assert in c++/winrt code? I usually use <assert.h> or define my own assert macro. How do I use asserts in UWP applications?

**Comment by kennykerr** [comment]
`<assert.h>` should work just fine. We don't mandate any particular assert macro.

**Comment by peterflynn** [comment]
@kennykerr Normally the standard-library `assert()` function prints a message to `stderr` to give an idea of what assert failed. E.g. on Mac it'll print something like:

`Assertion failed: (foo > 0), function myFunction, file /src/path/File.cpp, line 42.`

But my understanding is that `stderr` doesn't exist on UWP.  Does the C++/WinRT flavor of assert.h print a message somewhere else so that we can see it?  Or does the assertion message go into a black hole if we use this standard library routine?

**Comment by kennykerr** [comment]
C++/WinRT doesn't define how assert.h works - that is the provided by the standard library. Note that typical store apps don't have a console but you can see the error information using a debugger's output window.
