### ISSUE TITLE
Dependency properties

### ISSUE THREAD

**Issue by raffaeler** [Microsoft/cppwinrt#166]
I am migrating some code and registering few dependency properties in my components.
Can anyone provide a small snippet showing how to do it?
I am not sure in doing it correctly.
TIA

**Comment by drewcanitz** [comment]
It is a simple question, but could result in a very complex answer.  I've never seen it done with only c++/winrt, but I did see it with a c++/winrt WRL hybrid that used WRL to dig into the dependency property values etc.  I'll try my best to give a quick overview.

Basically you'll register your DPs with ::winrt::Windows::UI::Xaml::DependencyProperty::Register.  However...

The first problem you'll encounter is that this registration will start trying to establish a XamlType base class hierarchy for the types you register by querying your XamlMetadataProvider (XMP), so your implementation of XMP will need to be available to query.  This puts you into an interesting order-of-initialization situation.  Your Application class must be active to provide your XMP, so this might mean you can't register your types globally, but instead have to wait until your XMP is queried for the control types that will use the DPs or when you create the XMP instance.  In the example I saw, the DPs a control was going to use were registered by the factory for the control.  This works great for DPs that have an app provided owning type.

You can use GetValue and SetValue on DependencyObject as you might expect.  However, for non-iinspectable types (bool, int, double, etc), it may be that the value is wrapped by IReference to make it an "object".  If you're setting or pulling out a value, you may need to cast the returned IInspectable to IReference or IPropertyValue to get access to the get_Value method.

Does this help?

**Comment by raffaeler** [comment]
yes and no :)
I understood that I am not missing something trivial, at least.
I am trying to avoid merging WRL with cppwinrt because I had problems with the WRL include files in cppwinrt projects.
I am thinking that the best way to resolve is to create a CX DLL that I could use as a factory of TypeNames and then using it from the cppwinrt.
It is of course a temporary solution  while waiting for the full cppwinrt support for XAML.

The real use-case is a swapchainpanel for which I don't need XAML at all, but I have to expose depedency property so that it can be used from other XAML-based projects.

**Comment by drewcanitz** [comment]
I would suggest you either choose entirely cx or entirely cppwinrt.  You lose most performance/memory benefits once you throw cx into the mix in any capacity.

I think you're saying you want cx because that will automatically generate a winmd for you that is consumable by cx/c#.  If you chose purely cppwinrt it isn't as obvious how to get/create that all-important winmd.  I would do a search for "c++ windows runtime components" and learn how to use idl and midl to produce a winmd file for your dll.  Kenny has written a lot on this subject.  Here's one such article https://msdn.microsoft.com/en-us/magazine/mt185570.aspx.  

Once you have a winmd for your dll, you'll need to make sure your custom SwapChainPanel has an exported ActivationFactory and you'll need an appropriate dllmain.

Then you can ensure registration of your DP in your panel factory in your dll using DependencyProperty::Register.  Xaml will ask the application's XMP for the types the DP Registers with.  If your DP is of type "object", then you're probably done at this point.

**Comment by raffaeler** [comment]
I totally agree with you that mixing is not a good developer experience.
I am comfortable with WRL and I already developed components (with callbacks too :) ) using it.
But again, when mixing WRL with cppwinrt a lot of strange include conflicts appears.

I would like to always have the option to use WRL as soon as the cppwinrt projection cannot give me an obvious solution (like TypeName).
If you have workarounds to make WRL work well with cppwinrt, please create a new document explaining how to do it.

Exporting the DP as an object is not a good option IMO. Binding would not work in C# unless you create a Converter.
While waiting for a definitive cppwinrt solution, it would be good to have a guideline in mixing WRL.

Thank you

**Comment by kennykerr** [comment]
This might help: https://kennykerr.ca/2016/12/01/cppwinrt-working-with-namespaces/

**Comment by BrentRe** [comment]
We'd rather devote our engineering resources to creating a better C++/WinRT rather than creating samples demonstrating how to use WRL and C++/WinRT. Especially as both WRL and C++/WinRT are just C++, so conflicts are generally those caused by conflicting namespaces, type names, etc. Thus are standard C++ issues developers have seen before.

While I'd love to create such docs to help folks given unlimited resources, we don't have those imaginary unlimited resources. :(
