### ISSUE TITLE
coroutine optimization in release 

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/cppwinrt#169]
I heavily use coroutine in my code and it works fine in debug mode. However, if I switch it to release mode, visual studio would pop out pointer error. Because its in release mode, I've no idea what has been optimized by the compiler.  
![image](https://cloud.githubusercontent.com/assets/6119906/24933333/d29dfcca-1ee3-11e7-9efd-2c64e2e4716a.png)

**Comment by AlexBAV** [comment]
First of all, make sure you compile Release with debug information. This will allow you to debug a release build.

Also, coroutines are badly broken in Visual Studio 2017 RTM (they became broken in latest RC build and are not yet fixed in RTM and subsequent updates):

https://developercommunity.visualstudio.com/content/problem/23949/stack-overflow-in-generated-coroutine-code.html

In short, normal coroutine works correctly in Debug build and fails with Stack Overflow exception in Release build. This behavior seems to be affected by completely unrelated code elsewhere (in my example, crash disappears if I remove two virtual functions from a class, which are never actually called).

There are also apparently other problems with coroutines optimization.

**Comment by bigdimboom** [comment]
I'm actually using vs 2015 professional. This was not an issue before yesterday. I'm using coroutine in production-like environment. Is there a way to get round it? BTW, the error appears at when this coroutine calling the "resume" method.

**Comment by bigdimboom** [comment]
How do I turn off the optimization for coroutine in visual studio then?

**Comment by AlexBAV** [comment]
You can try [`#pragma optimize`](https://docs.microsoft.com/en-us/cpp/preprocessor/optimize).

Nevertheless, I would recommend you to run your application in Debug mode under Application Verifier, because there are other issues (mostly related to utilizing undefined behavior) that might work in Debug but fail in Release.

**Comment by GorNishanov** [comment]
@bigdimboom 
To turn optimizations off:

#pragma optimize (“”, off)
task<void> MyCoroutine() { … }
#pragma optimize (“”, on)

You can use https://connect.microsoft.com/VisualStudio to file bugs against Visual Studio/C++ compiler.

Please attached a self-contained repro.

**Comment by bigdimboom** [comment]
I found the problem.  you can mix openmp and winrt co_routine code in debug mode. openmp would have problem in release mode. The work around is using async code plus a kind of thread "barrier" impl.

**Comment by ahhlun** [comment]
what do you mean by a kind of thread "barrier" impl?

**Comment by bigdimboom** [comment]
https://en.wikipedia.org/wiki/Barrier_(computer_science)
