### ISSUE TITLE
Calling a coroutine, containing muliple co_await's,  with a blocking get() - fails

### ISSUE THREAD

**Issue by JackDetrick** [Microsoft/cppwinrt#170]
When I call the coroutine with NO blocking get it runs to completion. When I use the blocking get, the first co_await completes but the 2nd fails. Placing a try/catch around the caller and the 2nd co_await does not respond and the debugger returns to the caller where it displays:  "...exe has triggered a break point".
What is the proper approach for this situation?

**Comment by kennykerr** [comment]
I'm not sure I understand. How is that different [to this example](https://github.com/Microsoft/cppwinrt/blob/master/10.0.15063.0/Samples/Syndication/Main.cpp)? 

It sounds like you might be calling .get() from a UI/STA thread. That's not permitted since it would starve the message pump/dispatcher.

**Comment by JackDetrick** [comment]
The coroutine in your example contains only one co_await. My problem coroutine contains more than one.
I created a clone of the iBuffer sample and added a helper class for my code. The method that performs the blocking get is called from the method - std::future<void> ClickHandler(const IInspectable&, const IInspectable&)
As an aside, the last time I heard of the message pump was in the first book of Charles Petzold...
Thanks again for your teams hard work...

**Comment by kennykerr** [comment]
The message pump hasn't gone away - its just not as visible as in the Petzold days. 😄 

> The method that performs the blocking get is called from the method - std::future ClickHandler(const IInspectable&, const IInspectable&)

That's the problem. The ClickHandler is called from the UI thread (the STA). You may not call .get() from the UI thread, but you can use co_await.

Hope that helps.

**Comment by JackDetrick** [comment]
Does this mean if you write an app using XAML code behind you will be NOT be able to a do a a blocking get()? 

How do I address the following : The app has a "save" button that must be handled immediately and during start up, retrieving saved data must be handled before the first XAML page displays.. A modal display also  requires blocking..

**Comment by kennykerr** [comment]
XAML or otherwise, a UI thread must not introduce any blocking operation as it will prevent any windows associated with that thread from receiving and responding to window messages and it will prevent (deadlock) any components expecting or issuing callbacks on that same thread. 

This is of course not a new problem nor in any way specific to C++/WinRT.

**Comment by kennykerr** [comment]
It also doesn't matter how many co_await statements exist in a coroutine. It might only appear to behave differently if none of the co_await statements actually introduce a suspension. If all of the co_await statements never actually suspend (presumably because the results are immediately available) then the coroutine itself will complete before returning to the caller and thus the .get() method will have no reason to block the calling thread either.

**Comment by JackDetrick** [comment]
Thanks for your time and patience.
