### ISSUE TITLE
Suggested coroutine utilities

### ISSUE THREAD

**Issue by AlexBAV** [Microsoft/cppwinrt#183]
First of all, let me thank Kenny and the rest of the team for this amazing library. For me it looks like one of the best things that happened for C++ on Windows within last few years.

I hope coroutines will be fully accepted to the standard and their support will mature in time. 

`cppwinrt` introduces a few new utilities for asynchronous programming, including I/O, timers, waiting on events and so on, but lacks "supporting" machinery when compared with PPL, for example. Under this machinery I mean the solid cancellation support, `when_all`/`when_any` "aggregators" and ability to build "continuation graphs".

I would like to hear your team's opinion on a few extension classes and functions I developed, on their applicability, correctness and usefulness. Maybe you can take some of the ideas for a future version of `cppwinrt`.

https://github.com/AlexBAV/cppwinrt_ex

**Comment by kennykerr** [comment]
Thanks Alexander, I'll certainly take a look. I have been working on much deeper cancellation support. We (Microsoft) are also investing in better library support for coroutines, but I'm increasingly thinking that this should be a separate library that's complimentary to C++/WinRT rather than baked into C++/WinRT as its usefulness extends beyond just WinRT APIs and types.

**Comment by AlexBAV** [comment]
PPL has great cancellation support, but it seems not obvious how to mimic it with current primitives provided by `cppwinrt`. I'm eagerly looking forward to see deep cancellation support you are talking about.

So far, I've only managed to add "local" cancellation support to a timer and I/O awaitable types.

Having support utilities as a separate library seems reasonable; it even looks like `cppwinrt` is worth being divided into "pure C++" coroutine support library and WinRT auto-generated wrapper classes/functions.

**Comment by therealkenc** [comment]
> but I'm increasingly thinking that this should be a separate library that's complimentary to C++/WinRT

This would help immensely. Right now the gap between what Gor Nishanov has explained (very well) in N4649 and practical application is somewhat wide. Take for example this [VC++ team blog post](https://blogs.msdn.microsoft.com/vcblog/2017/02/02/using-ibuv-with-c-resumable-functions/) regarding libuv. It is very informative, but at the end of the day leaves the reader (or at least this reader) with the take away: "Here is how you might use coroutines sorta maybe but not really because we haven't explored cancellation or propagation of errors. But good luck with that." So while I can come here and "do it like Kenny says" if all my code is cppwinrt, once I leave this safe space and start fighting (say) boost it all kind of starts to unravel. This isn't a complaint, or for that matter cppwinrt's problem. I drank Gor's coroutine cool aid. I am just saying there is a bit of a vacuum out there.

**Comment by AlexBAV** [comment]
I'm about to publish another version of extension library referenced above.

Right now it may be used starting from Windows Vista (compared to cppwinrt, which requires Windows 8).

I've already migrated parts of three big projects from PPL to this new library and currently I'm very happy with a result.

Basically now we have a very thin wrapper around Windows thread pool with modern cool coroutine-style "interface".

I've also added simple cancellation support, which works surprisingly well.
