### ISSUE TITLE
Unified C++/Everywhere

### ISSUE THREAD

**Issue by MRahilly** [Microsoft/cppwinrt#184]
C++/CLI had its syntax copied (^) and was then diminished (Winform support disappeared in VS2012 etc) as C++/CX was developed. Now that C++/CX is to be phased out, could C++/CLI be revamped with modern asynch features for .NET non-deterministic garbage collection?

**Comment by tim-weis** [comment]
C++/CLI and C++/CX share a bit of syntax, but are otherwise completely unrelated. There is no connection at all between C++/CLI being phased out (not sure anyone would share that opinion anyway), and the introduction of C++/CX either. There's also no sign of C++/CX being phased out. It's unclear, how any of this is related to C++/WinRT. You should probably ask this question elsewhere (e.g. on UserVoice).
