### ISSUE TITLE
Lack of documentation, examples, wiki and a such

### ISSUE THREAD

**Issue by DBJDBJ** [Microsoft/cppwinrt#186]
I might be wrong. there might be this mountain of cppwinrt documentation in existence which I do not see. Please enlighten me?

**Comment by walbourn** [comment]
Some material is [here](https://github.com/Microsoft/cppwinrt/tree/master/Docs). I have C++/WinRT versions of my Direct3D templates [here](https://github.com/walbourn/directx-vs-templates/wiki).

**Comment by FeBrex** [comment]
From my point of view there is no need to document using WinRT/DirectX itself because there is a lot of material out there. But I'd especially like to see `base.h`  documented. It comprises a lot of functionality that differs from other language projections and there are some nice helper classes/functions in it.

**Comment by DBJDBJ** [comment]
I also do not have all the time and resources to wonder around the code. Lack of proper documentation can also mean lack of commitment to promote and keep some technology in use for longer period of time. It is really good but some crucial question needs to be answered before serious commitment towards cppwinrt.

**Comment by DBJDBJ** [comment]
@walbourn I am looking for MSDN section/part equivalent to the [WRL section](https://msdn.microsoft.com/en-us/library/hh438466.aspx). 

I am looking for the cppwinrt roadmap too. For next 5 years.

**Comment by BrentRe** [comment]
C++/WinRT will eventually be added as a language projection in MSDN. We need to finish the work needed to support C++ application development using XAML first. In the meantime, C++/WinRT code looks much like C# code so you have a reference that helps to some degree.

We likely will not provide a 5 year roadmap. Generally speaking, we hope developers adopt C++/WinRT as their preferred C++ language projection for calling Windows Runtime APIs. Additionally, for those creating WinRT class libraries, that they use C++/WinRT to implement their Windows Runtime types.

Therefore, generally speaking, our roadmap is to do what is needed to accomplish that goal and assist those developers.

**Comment by DomXC** [comment]
"We need to finish the work needed to support C++ application development using XAML first"

When can we expect the XAML support? Thank you.

**Comment by DBJDBJ** [comment]
@BrentRe Thanks ...  "we hope developers adopt C++/WinRT as their preferred C++ language projection for calling Windows Runtime API.." ... And we will, as soon as there is proper documentation :) 

I think the scope of cppwinrt should be bigger. I would like to be able to deliver win server side projects using cppwinrt. And compose the team(s) (for that) that will be based on C++ resources using the cppwinrt.  

As a CTO, I am far from convinced, right now, committing to cppwinrt is risk free.  I am going to be asked if cppwinrt is ok as the tech foundation for my (5 year) road map.

**Comment by tbandrowsky** [comment]
I don't think this technology is going to go away.  You have to understand that this is the first time in programming Windows, ever, that you can use a C++ that is standards based.  This is one of those things where Microsoft has smacked one out of the park and if there is a problem, it will be, in, how fast they can deliver those header files for the whole Windows universal platform.  The benchmarks, clarity of code, all align and I know this architect thinks Microsoft is really onto something. If you are looking to get started, I've written a simple article as to how to make a Visual Studio project for this from scratch, using Microsoft's example as a guide.  Hope this helps!

https://www.linkedin.com/pulse/creating-cwinrt-projects-visual-studio-todd-bandrowsky

**Comment by kennykerr** [comment]
@tbandrowsky - thanks for the article!

**Comment by DBJDBJ** [comment]
@tbandrowsky you have to understand, I am using C++ and WIN32 since 1994. Commercially. I think there is nothing "I have to understand" in there by now: this is not a technical issue :) Thanks for the article btw...

Back to the issue: also the source code is undocumented. To put it mildly. For example base.h has 12K lines of code. Undocumented.

"The King is naked" !

**Comment by DBJDBJ** [comment]
Ok "the wall of silence" is the answer. Fine. Let me ask one more simple questions and then close. 

https://docs.microsoft.com/en-us/

I think it is not so the question is when will the cppwinrt documentation appear over there?

Thanks ....

**Comment by DefaultRyan** [comment]
Not sure what sort of answer you expected over the weekend, and it's still morning on the west coast of the USA where the maintainers work. Just saying...

**Comment by VSChawathe** [comment]
@DBJDBJ You might be wishing for this [coverage](https://moderncpp.com/). As the source is mainly **autogenerated** based on WinRT API from the Windows (formerly platform) SDK mainly using the metadata (.WinMD files) so looking at the SDK documentation for _WinRT API_ might be better idea than. Using this repo just [allows **ISO C++** syntax rather than C++/CX](https://github.com/Microsoft/cppwinrt/blob/master/Docs/Migrating%20C%2B%2B%20CX%20source%20code%20to%20C%2B%2B%20WinRT.md)
@DomXC XAML can be used via [C++/CX interop](https://gist.github.com/kennykerr/105f96d61f51b5773670844edec99d85)
I've [shared](https://gitlab.com/iProcess/modernCX) minimalist project with documentation links as comments. Cloning it, [and restoring the nugget package for this repo](https://gitlab.com/iProcess/modernCX/wikis/home), to modify MainPage.XAML to fit your needs should work for now.

**Comment by Zingam** [comment]
That link is broken: 

> We have a demonstration of using the UWP Windows.Gaming.Input APIs with C++/WinRT here.

**Comment by walbourn** [comment]
Updated the [link]((https://github.com/Microsoft/Xbox-ATG-Samples/tree/master/UWPSamples/System/GamepadCppWinRT_UWP)
