### ISSUE TITLE
More details on "specializing" IAsyncOperation<*> and friends

### ISSUE THREAD

**Issue by AlexBAV** [Microsoft/cppwinrt#19]
As we can see in the JustCouroutines sample, one has to specialize winrt::ABI::Windows::Foundation::IAsyncOperation<T> and a number of other interfaces in order to use them in the code.

Could someone provide more details on this and the design rationale? 

Evidently, as number of "asynchronous" return types grow, we might find ourselves writing more and more of this "boilerplate" code.

Is there a way to simplify this? Or at least provide a macro?

**Comment by kennykerr** [comment]
You need to have specializations for any of the generic interfaces defined by WinRT. Usually, the projection will define them for you based on metadata. In this example, no metadata is provided and you must therefore define them yourself.

We realize this is not practical and are solving this in a future update where C++/WinRT will use a constexpr function to derive the GUIDs automatically. This requires constexpr support that is only available in the next version of Visual C++ (and Clang), which is why we haven’t made this solution available yet.

**Comment by AlexBAV** [comment]
This makes sense. Thank you for explanation!
