### ISSUE TITLE
get_abi for collection<T> should deep convert to abi

### ISSUE THREAD

**Issue by aballway** [Microsoft/cppwinrt#203]
for example, iterable<IKeyValuePair<hstring, IInspectable>> should return ComPtr<IIterable<IKeyValuePair<HSTRING, IInspectable*>*>>

Due to some templating assertions the return cannot be converted using ComPtr.As() so the value can't be used

**Comment by kennykerr** [comment]
The `get_abi` function is used for interop, the ability to cast a C++/WinRT type to some other ABI representation. It might be a Windows SDK type, a C++/CX ref type, or something else. Each of those projections will have their own representations of `IIterable`, `IKeyValuePair`, `hstring`, and so on. The next major update of C++/WinRT goes further and strips out even more of the ABI type information so that interop is easier still. You should thus not assume anything about the result, other than it is an `::IUnknown*` to an implementation. Our focus is to provide a richer projection that gives you fewer reasons to use the ABI and a simplified process for interop when that is needed.
