### ISSUE TITLE
Linker failure using Windows::Storage::FileProperties::IStorageItemExtraProperties Save/RetrievePropertiesAsync

### ISSUE THREAD

**Issue by aballway** [Microsoft/cppwinrt#204]
``` c++
WS::FileProperties::IStorageItemExtraProperties props{};
winrt::iterable<winrt::hstring> it{}
auto result = props.RetrievePropertiesAsync(it);
```

results in:

**error LNK2019: unresolved external symbol "public: struct winrt::Windows::Foundation::IAsyncOperation<struct winrt::Windows::Foundation::Collections::IMap<struct winrt::hstring,struct winrt::Windows::Foundation::IInspectable> > __thiscall winrt::Windows::Storage::FileProperties::impl_IStorageItemExtraProperties<struct winrt::Windows::Storage::FileProperties::IStorageItemExtraProperties>::RetrievePropertiesAsync(struct winrt::iterable<struct winrt::hstring>)const " (?RetrievePropertiesAsync@?$impl_IStorageItemExtraProperties@UIStorageItemExtraProperties@FileProperties@Storage@Windows@winrt@@@FileProperties@Storage@Windows@winrt@@QBE?AU?$IAsyncOperation@U?$IMap@Uhstring@winrt@@UIInspectable@Foundation@Windows@2@@Collections@Foundation@Windows@winrt@@@Foundation@45@U?$iterable@Uhstring@winrt@@@5@@Z) ...**

**Comment by kennykerr** [comment]
Make sure you're including the `Windows.Storage.FileProperties` namespace header. That's where the compiler/linker will find the definition its looking for.

**Comment by aballway** [comment]
That resolved the issue, thanks!  Would it be possible to make this fail in a more outwardly understandable way?  Linker errors are terribly opaque.

**Comment by BrentRe** [comment]
Unfortunately, C++ doesn't provide a good way to make this fail in a more understandable way. We'd love to make this type of error more intuitive but can't.

Conceptually, what you did was only include headers that forward-declared types/functions in the Windows.Storage.FileProperties namespace (because the headers you did include referenced those types/functions). This allowed the C++ compiler to compile everything as C++ assumes you'll provide the (missing) implementations at link time via a link library or separately compiled object file.

But the linker couldn't find them because they weren't present in any of the object files. By including the Windows.Storage.FileProperties.h header file, you provided the compiler the implementations, so it compiled them, and the linker now found everything it needed.
