### ISSUE TITLE
ValueSet  IInspectable Vs Object?

### ISSUE THREAD

**Issue by GregDomjan** [Microsoft/cppwinrt#205]
Trying to implement an Edge extension to match existing Chrome/Firefox, needing to call on native in new manner through AppService.  Existing implementation of nativeMessaging all in C++ but only examples I've found of AppService and Edge native message are in C#. 
ie. https://github.com/MicrosoftEdge/MicrosoftEdge-Extensions-Demos/tree/master/SecureInput

In trying to use winrt to convert the SecureInput project to C++ I've become stuck with the winrt ValueSet. 
Basically the Value is IInspectable, and the doc is suggesting Object. 
Am I just missing some way of converting Object/IInspectable to and from string ?

```
/// <summary>
/// Receives message from UWP app and sends a response back
/// </summary>
void Connection_RequestReceived(AppServiceConnection sender, AppServiceRequestReceivedEventArgs args)
{
	auto key = args.Request().Message().First().Current().Key();
	auto value = args.Request().Message().First().Current().Value().ToString();

	ValueSet focusoutResponse;
	focusoutResponse.Insert(L"message", L"ValueSet test\r\n");
```

**Comment by kennykerr** [comment]
A future update will make this easier, but you can manually box and unbox values as follows:

```C++
using namespace Windows::Foundation;

auto object = PropertyValue::CreateString(L"Hello world");

hstring value = object.as<IReference<hstring>>().Value();

assert(value == L"Hello world");
```

**Comment by GregDomjan** [comment]
Thanks for the pointer, good to know it will get easier :+1: 

Initial attempt to use the suggested left me with subsequent issue

> base.h(2446): error C2787: 'winrt::ABI::Windows::Foundation::IReference<HSTRING__ *>': no GUID has been associated with this object

Based on [CoRoutines sample](https://github.com/Microsoft/cppwinrt/blob/master/10.0.15063.0/Samples/JustCoroutines/Main.cpp) as I understand it, I need to also add something like this?  

```
namespace winrt::ABI::Windows::Foundation
{
	template <> struct __declspec(uuid("3a14233f-a037-4ac0-a0ad-c4bb0bbf0112")) __declspec(novtable) IReference<HSTRING__ *> : impl_IReference<HSTRING__ *> {};
}
```

**Comment by eklipse2k8** [comment]
I'd also like an explanation of 

```
no GUID has been associated with this object
```

as that error showed up so much that I gave up using the platform for now.

**Comment by BrentRe** [comment]
When you define a new generic interface type, e.g. IReference<Foo>, you *must* associated the correct, deterministically computed GUID with that new type.  IReference<Foo> will have a specific GUID. IReference<Bar> will have a different specific GUID. IReference<MyNamespace.Bar> will have yet another specific GUID.

For types defined in the system metadata, this GUID will be present in the metadata, and therefore present in the C++/WinRT header files that describe the types in the metadata.

For new types that you are defining, you (currently) need to manually define equivalent classes to the ones generated by the C++/WinRT projection and in those classes, provide the proper GUID.

In a future update, you'll be able to simply declare an IReference<Foo> type, and the C++/WinRT header files will use constexpr expressions to calculate the appropriate GUID for you.

**Comment by GregDomjan** [comment]
So @BrentRe if I'm understanding correctly, while taking the guid "3a14233f-a037-4ac0-a0ad-c4bb0bbf0112"  allowed it to compile, I believe your saying it's not going to work properly because that GUID belongs to the "AsyncActionProgressHandler<int>" type I stole it from.

But there is some way to find the appropriate GUID as it's a compute-able value, how do I find/lookup/compute the right value for a hstring ref? 
```
template <> struct __declspec(uuid("???"))  __declspec(novtable) IReference<HSTRING__ *> : impl_IReference<HSTRING__ *> {};
template <> struct __declspec(uuid("???")) __declspec(novtable) IReference<hstring> : impl_IReference<hstring> {};
```

**Comment by tim-weis** [comment]
@GregDomjan: You can call [RoGetParameterizedTypeInstanceIID](https://msdn.microsoft.com/en-us/library/br229857.aspx) to compute the interface identifier (IID) of the interface or delegate type. While this allows you to compute an IID at runtime, I wouldn't know of any immediate compiler support.

**Comment by BrentRe** [comment]
@GregDomjan Correct. The easiest way to determine the correct GUID (until the next release) is to define the parameterized interface using IDL, run MIDLRT, and inspect the ABI generated header file, which will contain the GUID as a comment.

**Comment by GregDomjan** [comment]
Thanks @BrentRe @tim-weis 
I've now been trying the IDL method suggested, maybe I've misunderstood, but it seems this particular case is blocked?

Tried with various combinations  hstring/HSTRING/HSTRING__*
Here is a small sample
```
import "inspectable.idl";
import "hstring.idl";
import "Windows.Foundation.idl";

// Type definition
namespace MyApp
{
[uuid(1589F754-FF6E-4AB5-9868-C1430D294A1B)]
[version(0x06030000)]
interface IMyComponent : IInspectable
{
	HRESULT Foo([in] HSTRING someString,
		[in]Windows.Foundation.IReference<HSTRING> myCallback);
//	HRESULT Bar([out][retval] Windows.Foundation.IReference<HSTRING__*>** monkey);
}
}
```
commandline of 
```midlrt Source.idl /ns_prefix /I"winrt-10.0.15063.0-2017.4.6.1\include" /metadata_dir "C:\Program Files (x86)\Windows Kits\8.1\References\CommonConfiguration\Neutral"```
results in 
```error MIDL5037 : Invalid parameter to IReference or IReferenceArray  :```

and with <HSTRING__ *>
```error MIDL5040 : only reference types (interfaces and runtime classes) can be declared as pointers in parameterized interfaces  : HSTRING__```

Then noticed this advice in [IReference<T> doc](https://msdn.microsoft.com/en-us/library/windows/desktop/br224583(v=vs.85).aspx) **When used in a property, method signature, or delegate parameter, T must not be a delegate type or an HSTRING.**

**Comment by DefaultRyan** [comment]
That error message is correct - you shouldn't ever need to have a method parameter that is an IReference<HSTRING>, because the IReference adds no value in this case. An HSTRING* parameter is already nullable (given that it's a pointer-to-HSTRING).

That being said, there are still times when you need to box up an HSTRING for a method that expects an IInspectable (Windows.UI.Xaml.DependencyObject.SetValue comes to mind). In that case, you can still determine the GUID by declaring an IReference<HSTRING> in IDL and running midlrt as described above. You were on the right track, but overcomplicated things by making the interface a param instead of simply declaring the interface:

```import "windows.foundation.idl";

namespace Foo
{
    declare
    {
        interface Windows.Foundation.IReference<HSTRING>;
    }
}
```

After running midlrt on this, you should be able to pick through the generated header and find this declaration containing the desired GUID. 
```
    MIDL_INTERFACE("fd416dfb-2a07-52eb-aae3-dfce14116c05")
    __FIReference_1_HSTRING : public IInspectable
```
This is the "IDL method" of computing parameterised interface GUIDs, alluded to by Brent.

**Comment by BrentRe** [comment]
Actually, Ryan is correct, with the sole exception of his second sentence, but his answer discusses two orthogonal concepts. Let me try and clear things up by potentially being overly pedantic.

A HSTRING parameter is *never* nullable. A Windows Runtime HSTRING is a value type. Therefore it *always* has a value. That value is *always* a string containing zero or more characters. There is simply no way in the Windows Runtime to distinguish not passing any string (aka "NULL" string) from passing a string. Full stop. 

This confusion arises because, for a string with zero characters, the binary ABI passes a NULL pointer. For a string with one or more characters, the binary ABI passes a pointer to an HSTRING structure. If you attempt to pass a NULL HSTRING, the callee will receive an empty ("") string.

So, if there is no binary representation for "I didn't pass any string", can I work around this by passing a IReference<HSTRING>? A Windows Runtime IReference<T> parameter represents a nullable valuetype. 

No, you cannot. While the HSTRING type in the Windows Runtime is a value type, some language projections treat string as a reference type. E.g. In C#, an IReference<T> parameter projects as a Nullable<T>. In both the Windows Runtime and in .NET, the T type parameter must be a value type. While T = HSTRING is a value type in the Windows Runtime, an HSTRING parameter projects as a System.String in .NET, which is a reference type. It is illegal to have a Nullable<T> where T is a reference type.

This IDL:
    HRESULT MyMethod (IReference<int> value);
projects to C# as:
    void MyMethod (Nullable<int> value);

As a consequence, we explicitly disallow IReference<HSTRING> because the concept does not project to .NET. E.g. Nullable<System.String> is illegal in .NET.

Okay, part one of my pedantic Windows type system tutorial is complete. Now onto part two... :)

There is a separate concept of boxing. Boxing is the technique used to pass a value type as an untyped object (aka a reference type). In the Windows Runtime, we represent an untyped object as an IInspectable interface pointer. HSTRING is a value type so how do I pass one as a boxed object? You pass an IInspectable.

This is where is gets confusing. First, let's talk about the IDL used to represent *any* boxed value type. The parameter must be: [variant] IInspectable* obj.  E.g.

HRESULT MyMethodWithObject ([variant] IInspectable* potentiallyBoxedValue);

The variant part specifies that the IInspectable may contain a boxed valuetype. Of course, as the IInspectable parameter is a reference type (object), it may also contain any more derived reference type as well.

We're almost there...

An object containing a boxed valuetype must provide some mechanism to allow retrieval of the value type. How does it do that? Sadly, in retrospect, we decided to reuse the IReference<T> mechanism. If I could do it over, I would have invented a new IBoxed<T> interface.

If you want to determine if the parameter contains a boxed integer, than QI for IReference<int> and, if it succeeds, retrieve the value. If you have a boxed double, then QI for IReference<double> and retrieve the value. If you have a boxed HSTRING, then QI for IReference<HSTRING> and retrieve the value.

As the parameter is an reference type parameter, it can be NULL or non-NULL.

Here's an example of the above IDL projection to C#:

void MyMethodWithObject (System.Object potentiallyBoxedValue);

With that as context, hopefully this answer makes sense:
1. There is no semantic in the Windows Runtime for "a string parameter that is sometimes not present".
2. You can approximate it by specifying a parameter of type object (aka IInspectable). It can be NULL or non-NULL, and, if non-NULL, may contain a boxed string - but, by going to IInspectable, you lose the strong typing.

Hope this helps.
way to designate a string parameter of a

**Comment by GregDomjan** [comment]
Having started to use the spring_2017 update, thankyou.

Now able to (and must) remove the definition of `IReference<hstring>`

Have found a few cases where we were converting hstring to wstring using like `wstring(hstring)` but now need to use `wstring(hstring.c_str())`   due to `cannot convert argument 1 from 'winrt::hstring' to 'std::wstring'`

Wondering if this method of unboxing an object (which is still working) now has a simplified syntax I could/should be updating to.
```
using namespace Windows::Foundation;

auto object = PropertyValue::CreateString(L"Hello world");

hstring value = object.as<IReference<hstring>>().Value();
```

**Comment by kennykerr** [comment]
We don't yet have a simpler syntax for that, but it is required by XAML (which is what we're working on now) so there will be simpler helper functions for this in a future update.
