### ISSUE TITLE
default barrier api?

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/cppwinrt#206]
I have a thread running multiple IAsyncActions:  
auto lamda = []()->IAsyncAction{ co_await winrt::resume_background(); //doing something parallel; }

lamda();
lamda();
......

How do I syn these IAsyncAction threads. e.g.
lamda();
lamda();
barrier.wait();

**Comment by Scottj1s** [comment]
Try gathering your lambdas into a collection and passing to something like this:

        template <typename Collection>
        static IAsyncAction wait_all(Collection & collection)
        {
            for (auto&& item : collection)
            {
                co_await item;
            }
        }

**Comment by bigdimboom** [comment]
But, I thought "co_await" will block current execution until current item has been finished, meaning items in collection will not execute in parallel.

**Comment by Scottj1s** [comment]
It depends on your awaitable semantics.  Since yours are implemented with resume_background, they'll be running concurrently.  Yes, wait_all is running in a synchronous loop, but advancing as each lambda has completed (which may occur before wait_all gets there).  You would then block on wait_all(lambdas).get().
