### ISSUE TITLE
Question: why is the hresult_error struct not derived from std::exception ?

### ISSUE THREAD

**Issue by vbaderks** [Microsoft/cppwinrt#207]
Hi,

I like the design concepts of the cppwinrt framework. Unfortunately many design decisions are not documented in the GIT repository. I like to understand why hresult_error isn’t derived from std::exception. while the latest modern C++ Core Guidelines advice to create user exception types derived from std::exception.

Question: what is the primary reason to not derive (indirectly) hresult_error from std::exception

**Comment by BrentRe** [comment]
C++/WinRT’s exception class does not derive from std::exception because that doesn’t add any real value. Additionally, using std::exception imposes unnecessary run time cost and implementation complexity.The Visual C++ team originally suggested we derive from std::system_error but that turned out to be even worse. The best we could do is derive from std::exception and override exception::what() to return a literal such as “winrt::hresult_error”. Anything else would require a runtime cost to retrieve the error information, possibly format the message, convert it to UTF8, etc. It would also force calls into the CRT from both constructor and destructor and all to produce a message that lacks much of the richness of WinRT’s error information and would not be used in the normal course of error propagation as the language projection transports and chains error information from one ABI boundary to the next.

**Comment by FeBrex** [comment]
Have you considered not deriving from any error class, but instead throwing `HRESULT`s as `std::system_error` with a class derived from `std::error_category`?

Something like the following:

```
std::error_category const& com_category();

[[noreturn]] inline throw_hresult(HRESULT const hr)
{
  throw std::system_error{ static_cast<int>(hr), com_category() };
}

std::string wide_char_to_multi_byte(std::wstring_view wide_char_str);

class ComCategory : public std::error_category
{
public:
  char const* name() const noexcept override { return "com"; }

  std::string message(int errVal) const override
  {
    // Call FormatMessageW or GetRestrictedErrorInfo
    return wide_char_to_multi_byte({ message, length });
  }
};

std::error_category const& com_category()
{
  static ComCategory const instance;
  return instance?
}
```

If C++/WinRT's exception classes are not part of the standard exception class hierarchy then catch clauses become more complex because one has to be prepared to catch `winrt::hresult_error` as well as `std::exception` derived exceptions.

For reference: https://youtu.be/w7ZVbw2X-tE

**Comment by kennykerr** [comment]
We had considered using system_error/runtime_error but it doesn't work well with the Windows Runtime, which has a rich error origination and propagation facility that doesn't integrate well with those types.
