### ISSUE TITLE
Umm, how to read a file?

### ISSUE THREAD

**Issue by procedural** [Microsoft/cppwinrt#217]
Hello people, it's me, your friendly neighbor C developer!

I don't particularly care about UWP or C++, but since Microsoft locks some of their platforms on this horrific abomination of an API, I have to deal with it regardless whether I like it or not.

I have a very simple question I haven't found an answer for:

How to read a file into an array of bytes?

Good old `fopen` is not allowed I presume? I'm currently trying to find any code on this, but all I get is C#, C++/CX or `co_await` long and boring reads and talks I have no time to read or watch to know how to simply open and read a file.

Is it even possible to read a file in a few lines of code? Or we are at a turning point in programming where to read a file you have to be a C++ PhD with 20+ years of experience?

Thanks!

**Comment by kennykerr** [comment]
You should be able to use [fopen_s](http://en.cppreference.com/w/c/io/fopen) and [fread](http://en.cppreference.com/w/c/io/fread) if you so desire.

**Comment by procedural** [comment]
@kennykerr will I be kicked out of Windows Store if I use these functions?

**Comment by procedural** [comment]
@kennykerr BTW, why C++/WinRT is ignored in the official docs? Where I can read more about file system interactions with C++/WinRT? Or it's not documented anywhere and you have to dig through C#, C++CX docs and interpret them to C++/WinRT? But then all this `co_await` disaster train in the way of simply reading and writing files...

**Comment by walbourn** [comment]
The majority of the C++/C++ Runtime is supported for Windows Store apps, Xbox One, and Universal Windows Platform (UWP) apps and will pass WACK as long as you use the Store version of the CRT.

You can use ``fopen`` (or better yet ``fopen_s``) when dealing with files in your AppX package, the appdata folder, or the temporary files folder. You can't use them directly for working with areas like user documents due to the permissions model--and in fact they might not be files on disk. In this case you need to use Windows Runtime APIs to either parse the file -or- you can copy the file to a temporary file folder and then reopen/parse with old-school ``fopen``. I have some examples of this using C++/CX (I should add C++/WinRT versions) [here](https://github.com/Microsoft/DirectXTK/wiki/WICTextureLoader#windows-store-apps). See also [File access and permissions (Windows Runtime apps)](https://msdn.microsoft.com/en-us/library/windows/apps/hh967755.aspx).

Similar issues apply when using Win32 file I/O APIs. The only real difference in this case is that you can't use ``CreateFile``--which can do about a zillion zany things in addition to dealing with files--and must use the simplier ``CreateFile2``.

You might want to read through [Dual-use Coding Techniques for Games](https://blogs.msdn.microsoft.com/chuckw/2012/09/17/dual-use-coding-techniques-for-games-part-1/) for a discussion of the API surface area at least for games.

**Comment by procedural** [comment]
@walbourn Thank you for all this info! I will check all of your links and will try them in code. Issue can be closed for now!

**Comment by procedural** [comment]
> (I should add C++/WinRT versions)

Yea, that would've been really helpful!

**Comment by walbourn** [comment]
I'll work on getting them up today...

**Comment by procedural** [comment]
@walbourn thanks again for this table (https://blogs.msdn.microsoft.com/chuckw/2012/09/17/dual-use-coding-techniques-for-games-part-2/), very helpful in figuring out what can and what can't be called!

Here's what I use now to read a UTF-16 text file, in C:

```c
  wchar_t file_path[10000] = {0};
  swprintf(file_path, 10000, L"%s%s", installed_location_path, L"\\Assets\\Text.txt");
  HANDLE fh = CreateFile2(file_path, FILE_READ_DATA, FILE_SHARE_READ | FILE_SHARE_WRITE, OPEN_EXISTING, NULL);
  assert(fh != INVALID_HANDLE_VALUE);
  size_t fsize = 0;
  GetFileSizeEx(fh, (PLARGE_INTEGER)&fsize);
  HANDLE fmap = CreateFileMappingFromApp(fh, NULL, PAGE_READONLY, fsize, NULL);
  assert(fmap != INVALID_HANDLE_VALUE);
  wchar_t * data = MapViewOfFileFromApp(fmap, FILE_MAP_READ, 0, 0);
  OutputDebugStringW(data);
```
