### ISSUE TITLE
Question: Completed handler

### ISSUE THREAD

**Issue by partmachine** [Microsoft/cppwinrt#225]
I  tried to add a completed handler to the justcoroutines sample:

async.Completed([](auto const & /*sender*/, AsyncStatus s) 
{
	printf("completed\n");
});

This throws an exception (winrt::hresult_illegal_delegate_assignment) because await_adapter::await_suspend also tries to register a completed handler.
Shouldn't await_adapter::await_suspend not honour any existing completion handler and call it in its own completed handler?

**Comment by kennykerr** [comment]
The Windows Runtime’s async pattern does not permit more than one completed handler because reasoning about the correctness of what you suggest is simply too problematic in general. What if a third caller decides to do the same…

Anyway, you have three choices – get(), co_await, and Completed – and are certainly capable of achieving this level of composability given the primitives provided by C++/WinRT. Rather than providing your own Completed handler, simply use get() or co_await to do the Completion handling and then chain your own completion logic to the end of one of those.
