### ISSUE TITLE
Do you have a plan to do same for COM?

### ISSUE THREAD

**Issue by black78** [Microsoft/cppwinrt#231]
I like what you do! Many thanks!
I have a lot manage/native interactions via COM (Win32 COM).
I'll be happy to see same approach for importing COM type library.

Do you have a plan to do same for COM (some tool which generate same c++ classes)?

**Comment by Scottj1s** [comment]
We're investigating doing something similar for COM type libraries.  At this stage, as noted in our timeline, our priority is to integrate the compiler into the build process in a natural way.  We'll keep in mind extending that to COM types as well.

**Comment by VSChawathe** [comment]
For UWP, COM subset WRL has been known to work with the extensions as [C++/CX-WRL integration](https://docs.microsoft.com/en-us/cpp/cppcx/wrl-integration-c-cx). Maybe analogous WRL guidance should be with the [docs](https://github.com/Microsoft/cppwinrt/tree/master/Docs).

**Comment by black78** [comment]
Thank you Scott.

**Comment by Zingam** [comment]
What I really hate to see is something like that:

Read ActivatableClassId entry Windows.Xbox.Input.Gamepad in scope !Windows::Foundation::RegistrationScope!, property ActivationType (0): !HRESULT!GetRuntimeClassInfo(Windows.Xbox.Input.Gamepad) for CLSID entry {E0422A66-C480-4C70-9F99-F8371DCC3E30} in scope 0: 0x800705aa
GetClassInfo({E0422A66-C480-4C70-9F99-F8371DCC3E30}) for ActivatableClassId entry Windows.Xbox.Input.Gamepad in scope !Windows::Foundation::RegistrationScope!: !HRESULT!Exception thrown at 0x0000010149DC390E in framework.exe: Microsoft C++ exception: Platform::COMException ^ at memory location 0x000002072F75F358. HRESULT:0x800705AA

What did just happen here? A complete mystery. Is this a bug in the runtime or was it caused by our code. Will CppWinRT be able to help here and provide more introspection?
