### ISSUE TITLE
Making winrt::impl::lock more standard and probably open

### ISSUE THREAD

**Issue by YohDeadfall** [Microsoft/cppwinrt#236]
The `lock` class currently doesn't implement the lockable concept and is located in the `winrt::impl` namespace. Probably it would be better if the `lock` implements the lockable concepts.

```cpp
struct lock
{
    lock(lock const&) = delete;
    lock& operator=(lock const&) = delete;
    lock() noexcept = default;

    // Lockable concept
    void lock() noexcept;
    bool try_lock() noexcept;
    void unlock() noexcept;

    // Shared mutex concept
    void lock_shared() noexcept;
    bool try_lock_shared() noexcept;
    void unlock_shared() noexcept;
};
```

As an addition, the `lock` class could be moved outside of the `winrt::impl` namespace to be a slim version of `std::mutex` and `std::shared_mutex` (requires the shared mutex concept). So, it would be possible to use it not only in C++/WinRT implementation.

For now it isn't a good idea to use it, and the standard mutexes are too expensive.

**Comment by kennykerr** [comment]
The Visual C++ team continues to improve the performance of the standard synchronization primitives. While we love the SRW lock and use it internally, none of the types and functions in the winrt::impl namespace are considered part of the public surface of the C++/WinRT library and you should thus not use them directly. The SRW lock is however beautifully simple and you can easily write such a wrapper yourself, even using our implementation as a starting point. I would just be careful not to take a dependency on anything in the winrt::impl namespace because it is subject to change or removal at any time.

**Comment by YohDeadfall** [comment]
Yes, it's written in the change log.

> We have steadily cleaned up the base library to avoid leaking any unnecessary implementation details. The winrt namespace is now a lot leaner, exposing only those functions and types that you could conceivably need to use in order to make the most of C++/WinRT. Anything that begins with impl_ or is within the winrt::impl namespace should be considered an implementation detail subject to change at any time.

The are few ways to implement a slim lock (using `SRWLOCK` or `std::atomic<T>`), but reimplementing something isn't a good idea. Since you are investigating similar things for COM, why not to make such things public, write an extension library, or do something else? The things like `lock` and `handle<T>` are really useful and could be used in our projects, not only internally in yours.

**Comment by kennykerr** [comment]
Yes, we may surface these in a separate library since they are not specific to WinRT. Thanks for the suggestion!

**Comment by devhawk** [comment]
I'm making changes to base_lock (and dependencies) to make the existing winrt::impl::lock and winrt::impl::condition_variable conform to standard library concepts in order for them to work with other std types like std::lock_guard.
