### ISSUE TITLE
Howto for libraries of code that uses cppwinrt 

### ISSUE THREAD

**Issue by andrew7webb** [Microsoft/cppwinrt#244]
My goal is to create a class library of routines that a cppwinrt application can use.
I would like to expose pure C++ objects like std::vector, and also things like
    winrt::Windows::Security::Cryptography::Certificates:Certificate

Should I create a new project of:
     DLL (Universal windows)
     Static library (Universal windows)
     Windows Runtime component (Universal windows) 
    or something else?

Then what project settings need to be changed to make this work?

Anybody done this yet?

**Comment by Scottj1s** [comment]
Since C++/WinRT is standard C++, you're not limited in any way.  A few considerations to keep in mind however:
1) Unless you're exposing your own runtime classes, rather than just reusing system types, a WinRT component is not necessary for your library, and would only restrict its use, 
2) The projection itself is versioned, based on the compiler.  You may want to assert that version in your library, to ensure compatibility.  See the "Mismatched component and base headers." assert in the authoring samples for reference.
3) Project settings like /std:c++17 and /await may be necessary to light up certain features in the projection
4) Availability of runtime classes that your library exposes is also subject to runtime context (desktop or store app), whether the class is dual_api_partition attributed, and so on.

**Comment by andrew7webb** [comment]
Thanks, I'm trying a universal windows static library
  Add in project properties, C++, command line, additional objects, /bigobj /await /std:c++latest /d1permissive- 
  Add in pch.h the includes for cppwinrt 
  Remove the lean and mean define: WIN32_LEAN_AND_MEAN

But then, perhaps in upgrading to 15063, I started to run into these errors with my original non library version.      

1>------ Build started: Project: PivUwpLib, Configuration: Debug Win32 ------
pch.cpp
\prj_nosw\pivuwplib\pch.cpp(1): **error C4996**:
  'winrt::Windows::Media::IMediaControl::~IMediaControl': 
 MediaControl may be altered or unavailable for releases after Windows 8.1. Instead, use SystemMediaTransportControls.

\cppwinrt-master\10.0.**15063**.0\winrt\impl\windows.media.1.h(58):
   note: compiler has generated 'winrt::Windows::Media::IMediaControl::~IMediaControl' here

\prj_nosw\pivuwplib\pch.cpp(1): **error C4996**:
  'winrt::Windows::UI::Xaml::Controls::IInkToolbarRulerButton::IInkToolbarRulerButton':
  InkToolbarRulerButton is deprecated starting from Windows 10 Creators Update.
  Please use InkToolbarStencilButton going forward. For more info, see MSDN.

\cppwinrt-master\10.0.15063.0\winrt\impl\windows.ui.xaml.controls.1.h(1884):
   note: compiler has generated 'winrt::Windows::UI::Xaml::Controls::IInkToolbarRulerButton::IInkToolbarRulerButton' here
\prj_nosw\pivuwplib\pch.cpp(1): note: This diagnostic occurred in the compiler generated function
   'winrt::Windows::UI::Xaml::Controls::InkToolbarRulerButton::InkToolbarRulerButton(winrt::Windows::UI::Xaml::Controls::InkToolbarRulerButton &&)'

**Comment by Scottj1s** [comment]
Yes, unfortunately, the deprecation warnings are a compiler bug.  The
workaround is to leave them disabled in the pch with a WINRT_WARNING_PUSH.
Visual Studio 15.5 should correct many of these.

On Sep 23, 2017 11:44 AM, "andrew7webb" <notifications@github.com> wrote:

Thanks, I'm trying a universal windows static library
Add in project properties, C++, command line, additional objects, /bigobj
/await /std:c++latest /d1permissive-
Add in pch.h the includes for cppwinrt
Remove the lean and mean define: WIN32_LEAN_AND_MEAN

But then, perhaps in upgrading to 15063, I started to run into these errors
with my original non library version.

1>------ Build started: Project: PivUwpLib, Configuration: Debug Win32
------
pch.cpp
\prj_nosw\pivuwplib\pch.cpp(1): *error C4996*:
'winrt::Windows::Media::IMediaControl::~IMediaControl':
MediaControl may be altered or unavailable for releases after Windows 8.1.
Instead, use SystemMediaTransportControls.

\cppwinrt-master\10.0.*15063*.0\winrt\impl\windows.media.1.h(58):
note: compiler has generated
'winrt::Windows::Media::IMediaControl::~IMediaControl'
here

\prj_nosw\pivuwplib\pch.cpp(1): *error C4996*:
'winrt::Windows::UI::Xaml::Controls::IInkToolbarRulerButton::
IInkToolbarRulerButton':
InkToolbarRulerButton is deprecated starting from Windows 10 Creators
Update.
Please use InkToolbarStencilButton going forward. For more info, see MSDN.

\cppwinrt-master\10.0.15063.0\winrt\impl\windows.ui.xaml.controls.1.h(1884):
note: compiler has generated 'winrt::Windows::UI::Xaml::Controls::
IInkToolbarRulerButton::IInkToolbarRulerButton' here
\prj_nosw\pivuwplib\pch.cpp(1): note: This diagnostic occurred in the
compiler generated function
'winrt::Windows::UI::Xaml::Controls::InkToolbarRulerButton::
InkToolbarRulerButton(winrt::Windows::UI::Xaml::Controls::InkToolbarRulerButton
&&)'

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/cppwinrt/issues/244#issuecomment-331662088>,
or mute the thread

**Comment by andrew7webb** [comment]
I removed [[deprecated in the cppwinrt headers to continue with the library attempt.

I did try WINRT_WARNING_PUSH,POP in my .h, but that did not fix the errors.  Perhaps I should have inserted them in the cppwinrt headers.

**Comment by Scottj1s** [comment]
To be clear, you cannot end your pch with a WINRT_WARNING_POP, you must leave an open WINRT_WARNING_PUSH.  The compiler bug is due to deprecation warnings involving compiler generated functions (ctors and dtors) which happen at the end of the file, and 'outside' any efforts to disable them.

**Comment by RyutaMiyake** [comment]
I'm not sure why, but I tried comparing the sample compile options. The compile option allows you to compile the SDL check to No (/sdl-).

**Comment by Scottj1s** [comment]
Ah!  I wasn't reading carefully.  Yes, the SDL checks turn a deprecation warning (4996) into an error, which the warning disables have no effect upon.  I've already removed that option from our samples and suggest you do the same.

**Comment by walbourn** [comment]
In my [templates](https://github.com/walbourn/directx-vs-templates) I make use of a ``pch.h`` precompiled-header, so the workaround for me was to disable C4996 in the ``pch.cpp``:

    #pragma warning(disable : 4996) 
    #include "pch.h"
