### ISSUE TITLE
Warning non-agile factory

### ISSUE THREAD

**Issue by eklipse2k8** [Microsoft/cppwinrt#254]
I'm getting this warning on all my XAML subclasses. Is there something new I need to do?

```
            if (!factory.template try_as<IAgileObject>())
            {
                WINRT_TRACE("Warning non-agile factory: %ls\n", name_v<Class>);
                return factory;
            }
```

**Comment by kennykerr** [comment]
The XAML activation factories are incorrectly implemented. This was meant to be fixed in RS3 but it ended up slipping. The warning is legitimate but you can ignore it for now or simply comment out that line if its bothering you. It is however a good reminder that loading those runtime classes is a lot slower than it could be (and potentially buggy).

**Comment by kennykerr** [comment]
I have removed the warnings for the new update.
