### ISSUE TITLE
Are .winmd no longer required?

### ISSUE THREAD

**Issue by Zingam** [Microsoft/cppwinrt#255]
I looked up the new samples and they do not contain [.winmd files](https://github.com/Microsoft/cppwinrt/issues/124#issuecomment-284453717) any longer.

**Comment by Scottj1s** [comment]
Yes, the app template-generated winmd files were removed as part of general
cleanup and simplification.  They were not participating in any C++/WinRT
projection behavior.

On Oct 13, 2017 10:59 PM, "Zingam" <notifications@github.com> wrote:

I looked up the new samples and they do not contain .winmd files any longer.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/cppwinrt/issues/255>, or mute the thread

**Comment by willdieh** [comment]
I know this is closed, but with WinRT 2.0.191111.2 at least, the CoreApp template has Generate Windows Metadata enabled under the Common Properties -> C++/WinRT project settings. This causes the build to fail due to missing winmd file. Changing the setting to disabled resolves the build issue.
AppxPackage error code: APPX0702 (Payload file missing)

**Comment by kingofthebongo2008** [comment]
I have the same, I must set /ZW to get them back, but then cppwinrt does not work if I put c++ 20 features

**Comment by kingofthebongo2008** [comment]
1>cl : command line error D8016: '/ZW' and '/std:c++latest' command-line options are incompatible
