### ISSUE TITLE
Consuming non-graphic WinRT component in a C# console app

### ISSUE THREAD

**Issue by therealkenc** [Microsoft/cppwinrt#256]
This is a bit of a shot in the dark, but I have been banging on this on-and-off for some time to no avail. Basically I want to re-frame the question asked in #229. Or, in short, get an answer to Q1 in this 2014 Stack Overflow [question](https://stackoverflow.com/questions/44552573/consuming-c-winrt-components-from-c-sharp).

Given a toy non-graphical WinRT component written using WRL (cppwinrt the hard way) such as the canonical [Oven Server](https://github.com/Microsoft/Windows-universal-samples/tree/6370138b150ca8a34ff86de376ab6408c5587f5d/Samples/ProxyStubsForWinRTComponents/cpp/Server) sample, how do I go about consuming that component in a C# console application? I am all to familiar with the Desktop Bridge (Centennial), but that isn't the ask. My component performs operations verboten in the app model, and I end up between the rock and hard place of (a) access errors or (b) using the newly-minted RunFullTrust feature, but ending up with the verboten operations being virtualized.

All of this is straightforward with C++/CLI, but that is what I am trying to avoid. I know it is _possible_, because I can consume _Microsoft-authored_ WinRT components from a **non**-app-model (aka **not** UWP/Store) C# console project (following [this walkthrough](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-enhance)) just fine. Samples involving UWP/Store apps consuming custom WinRT components abound, but I have not been able to find one that does not land me in sandbox jail.

Hope this question makes sense.

**Comment by BrentRe** [comment]
First, this is not a question about C++/WinRT so really not appropriate here.

Bottom line is that you cannot use user-authored WinRT components in a Desktop application. It doesn't matter how the WinRT component was authored - WRL, C++/WinRT, other.

When client code attempts to activate a user-authored component, defined as any class that is not in the Windows.* namespace hierarchy, the activation logic goes to the app container for the application to locate the appx's manifest, to locate the DLL that contains the component. A Desktop application does not have an app container.

**Comment by therealkenc** [comment]
Very well. But if the question is inappropriate here it is a fair question where the question should have been directed.

Saying "you can't get from here to there" is not very constructive. You can activate a user-authored WRL or C++/WinRT class from a Win32 Desktop application -- you CoCreate the thing. It must be possible to do this from C#, because _you do this_ with the Windows.* hierarchy. _My ask is how_.

**Comment by BrentRe** [comment]
No, you cannot activate a user-authored *WinRT* class (which is what C++/WinRT creates) from a Desktop application. Full Stop.
You can activate a user-authored *COM* class from a Desktop application. You've been able to do that for literally decades.

A WinRT activation request for a class in the Windows.* namespace goes through an activation path that *only* searches the system class activation catalog for the requested type. A WinRT activation request for a class not in the Windows.* namespace goes through a completely different activation path that *only* searches the calling application's app container's package graph looking for the requested class' manifest entry (which maps the class name to the appropriate DLL contained in the APPX package).

Desktop applications do not have an app container in which local WinRT classes can be registered.

**Comment by kennykerr** [comment]
As I mentioned in the [related question](https://github.com/Microsoft/cppwinrt/issues/229), this isn't supported by WinRT today. It is however a popular request and I would personally love to see this restriction removed, however your best bet is to bring it up on [uservoice](https://wpdev.uservoice.com/forums/110705-universal-windows-platform).

**Comment by therealkenc** [comment]
Very much appreciate the replies from you both. Thank you for clarifying the difference between the classic COM component activation and WinRT component activation paths. I am still having a tough time wrapping my head around the "Full Stop" part of this, but must accept that answer as given.

**Comment by BrentRe** [comment]
This current restriction is something I'd very much like to remove. But, for now, it's the way it is.

**Comment by mediabuff** [comment]
I am confused on "Full Stop" as well. According to this blog [post.](https://blogs.windows.com/buildingapps/2017/07/06/calling-winrt-components-win32-process-via-desktop-bridge/#VTVxfof7SUEBGdBg.97)

in-process WinRT components can be activated from Win32 process as part of the Desktop bridge packaging.

**Comment by BrentRe** [comment]
Correct. As I mentioned, in-process WinRT components can only be activated from an app container process, otherwise known as a process with package identity. That is, an APPX application. 

The Desktop bridge creates an APPX from a Win32 application. Therefore a Desktop bridge application has package identity and can activate an in-process WinRT component.

**Comment by mediabuff** [comment]
Thank you. So, the activation occurs on the "appcontainer" leg and not the "win32" leg of the Bridge ? meaning, activation has two important criteria - appx identity and an appcontainer process - are required , which the Bridge provides.

**Comment by therealkenc** [comment]
Any links/references to the WinRT activation process would be awesome. I understand the App Bridge **_use_**. But everything is a 'win32 leg' -- calls into ntdll.dll is what Windows speaks. I am not going to question "full stop" because you guys live and breath this stuff all day and I lost my "Inside COM" about a decade ago, let alone "Inside WinRT" (which does not exist). I am just not fully understanding how it works.

**Comment by BrentRe** [comment]
Here's a more detailed breakdown though I'm glossing over a few details.

Activation requests for types *not* in the Windows.* namespace, e.g. third-party types, search the package graph of the calling application. In order for an application to have a package graph, the application must be an app container-based application. Basically, an APPX package.

When an APPX based application starts up, the system reads the manifest in the APPX package and, when the manifest optionally contains entries saying, in effect, for the type "Brent.Foo", you can find the implementation of that type in the Brent.dll file contained in this APPX, creates a mapping table.

A particular APPX may have a dependency on another APPX and this secondary APPX can also have such entries. Effectively. the system creates a graph of these "type-name-to-implementation-file" entries called the "package graph". Activation requests for non-Windows.* namespace types search this graph to find and load the implementation.

UWP applications are APPX-based, so they have the ability to define these manifest entries that create the package graph. Desktop Bridge applications are also APPX-based, so you can also define these entries in Bridge applications as well.

Traditional Win32 applications are not APPX-based, so they don't have the appx manifest file and aren't loaded by the APPX loader. They don't have package identity and don't have a package graph. So in effect, when an Activation request for a non-Windows.* namespace type originates in a traditional Win32 application, the system looks for the package (APPX) identity of the caller, which is needed to find its package graph, sees that the traditional Win32 app doesn't have a package identity, therefore, no package graph. And since there's nothing to search, fails the activation request because there's no mapping of the Brent.Foo type name to a DLL.

Does this help?

**Comment by mediabuff** [comment]
BrentRe - really appreciate the breakdown. Everything is clear - in a pure UWP situation (appx containing single .exe) and desktop win32 (no appx). But on aBridge package - there are two exe/dll - win32 and uwp. The activation of Winrt component can only occur in-process in the "uwp leg" and not on the "win32 leg". Is this correct ?

**Comment by therealkenc** [comment]
Thank you BrentRE. It helps. I need to research and experiment some more in order to ask anything more detailed/informed. I moved on to C++/CLI for the time being so I haven't got back to looking since accepting "impossible". I am just dangerously uninformed enough to have looked at [DllGetActivationFactory](https://msdn.microsoft.com/en-us/library/br205771(v=vs.85).aspx?f=255&MSPPError=-2147217396) [RoResolveNamespace](https://msdn.microsoft.com/en-us/library/br229860(v=vs.85).aspx), [RoGetActivationFactory](https://msdn.microsoft.com/en-us/library/br224648(v=vs.85).aspx) and [RoGetMetaDataFile](https://msdn.microsoft.com/en-us/library/br229856(v=vs.85).aspx). Also glanced at [WinRtClassicComMix](https://msdn.microsoft.com/en-us/library/br245040.aspx). But assume the short answer remains "no those aren't going to get you there either".

**Comment by BrentRe** [comment]
Not quite. In a Bridge application, you can "register" a WinRT non-WIndows.* namespace component for use in either leg, or both. But the details are involved. So I'll point you to our blog post more the gore.. :)

See 
[https://blogs.windows.com/buildingapps/2017/07/06/calling-winrt-components-win32-process-via-desktop-bridge/](url)

**Comment by therealkenc** [comment]
Link above 404s for some reason but here's an [alternate](https://blogs.windows.com/buildingapps/2017/07/06/calling-winrt-components-win32-process-via-desktop-bridge/#ZTcVheQPDaKkj9jR.97). I have gone through that blog post; they even make it easy with the new [packaging template](https://blogs.msdn.microsoft.com/appconsult/2017/08/28/package-a-net-desktop-application-using-the-desktop-bridge-and-visual-studio-preview/). I put a sample on github [here](https://github.com/therealkenc/WinformsOutOfProcessWinRT). But you end up in sandbox jail, even with RunFullTrust. This is a feature not a bug, natch.

**Comment by Alovchin91** [comment]
There is a suggestion about this exact feature on [UserVoice](https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/7308561-winrt-custom-components-desktop). The problem is they marked it as "Completed" even though it's definitely not.

From a UWP view point, opening WinRT for desktop applications would definitely be good for sandboxed UWP apps. Put it this way: the developers would be able to write redistributable components in languages they prefer for the users that will be able to consume those components from the languages they prefer. The more WinRT components will be written, the more complete UWP platform would be from the developers' perspective.

And still, Windows had that manifest thing for ages. Registration-free COM component can be declared using this same manifest. What on Earth prevents Microsoft from allowing using WinRT components from desktop apps by declaring those Activatable Classes in application manifest? It would be almost the same as declaring them in AppxManifest.

**Comment by kennykerr** [comment]
Yes, the UserVoice response is not accurate. 

You should give Desktop Bridge a try. [Here's an example](https://github.com/kennykerr/cppwinrt/tree/master/Bridge). It's pretty close to the classic reg-free COM approach.

**Comment by Alovchin91** [comment]
@kennykerr Thank you for the link. There are some kinds of software that are not suitable for Desktop Bridge. For example, if one is developing an anti-malware app that internally uses Chromium engine, this app would not be suitable neither for Store nor for the sandbox.

**Comment by kennykerr** [comment]
Agreed, there are some limitations.

**Comment by Alovchin91** [comment]
@kennykerr Here's one of the scenarios I personally had dealt with recently.

We were developing support for Windows 10 toasts in our well-known end-user software product. To implement it in right way, I had to implement COM interface INotificationActivationCallback in native code to minimize the time the app responds to request for this iface (the managed part is pretty heavy and doesn't start until some time into the app usage). I then had to make some calls into the managed code from the callback, and it wasn't all that trivial.

Using WinRT, I see this scenario made easier by exposing this interface in WinRT type system, along with the static method to register the callback. It then could call into managed WinRT component thus making interop between the native and managed parts seamless.

**Comment by therealkenc** [comment]
My use case, for what it is worth, is manipulating NTFS extended attributes with [NtQueryFile](https://msdn.microsoft.com/en-us/library/windows/hardware/ff961907%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396)/[NtSetEaFile](https://msdn.microsoft.com/en-us/library/windows/hardware/ff625895(v=vs.85).aspx). I fell back to C++/CLI for lack of a better solution; the alternative being classic COM per post above, or pinvoke like the closed User Voice. The whole UWP/Store (in other words Windows::ApplicationModel) isn't the ask. I would settle for WPF. The ask is being able to write my C++ side using the modern async interfaces and interop/marshal (sanely) with the C#/CLI side.

**Comment by raffaeler** [comment]
@Alovchin91 @therealkenc  I initially opened the request on UserVoice but I lost any hope on that and don't want to return on the open wounds. It is not a technical problem, it is just a political thing, and I want to stay away from that.
You'd better find a different solution/technology if the current UWP implementation is not enough for you (and this is also the situation with my customers).
Also, I strongly suggest to stay away from C++/CLI and prefer PInvoke instead. This is based on various discussions I read on the internet and it is just my personal conclusion on those readings.

**Comment by therealkenc** [comment]
> I strongly suggest to stay away from C++/CLI and prefer PInvoke instead.

Don't like it either. Mostly I just followed Microsoft's lead. It how they do something similar in spirit to what I was doing with their [GVFS](https://github.com/Microsoft/GVFS/tree/master/GVFS/GVFS.GvFltWrapper). If C++/CLI is good enough for MSFT I guess it is good enough for me.

[Deep in my gut I still don't see how it is impossible full stop. The ask is really: "If MSFT won't do it for _reasons_, how would I go about rewriting or proxying enough of the activation path myself to make C# happy". But it just isn't my area, and as such it, it makes more sense to accept the answer as given and follow GVFS' lead.]

**Comment by raffaeler** [comment]
The entire .net echosystem is moving on netcore+nestandard not only for going cross-platform but also to rejuvenate the framework. There is no plan (they said) for C++/CLI for netcore/nestandard, this should be a first good deterrent. Also, it is not standard C++ and it adds complexity to the build chain (I had problems in dealing certain references and nuget support).
The best interop solution could come from a spin-off of the cppwinrt project, but probably the Windows division has no interest in investing there.
Interop is indeed an open problem in development. As fare as I can see in the real world, there is no language/framework that can satisfy all the requirements for a medium-large app, so interop is crucial but still undervalued from compiler manufacturers.

**Comment by kennykerr** [comment]
Hooking activation in C# is a little tricky. You'd have to avoid constructors and statics and call DllGetActivationFactory via pinvoke (I tried this and it seems to work). There may be a better way, but I haven't used C# in a while so I'm a little rusty. Hooking activation with C++/WinRT is pretty easy. I'm considering providing a simple way to do this with C++/WinRT, but you can technically pull it off without any help from the platform. 

> It is not a technical problem, it is just a political thing

That's not entirely true. It is mostly a problem of time and conflicting priorities. The work to enable this without manually calling DllGetActivationFactory or hooking RoGetActivationFactory involves changes to combase.dll that are not trivial. While the folks who own combase are just down the hall from me (and certainly know how to solve the problem), they are also rather busy. Just because it seems like a good idea, doesn't always mean that it's something we can act on immediately. Please keep the feedback coming. It's very helpful. In the meantime, I'll see what I can do to make it easier to hook this with C++/WinRT or at least share a sample.

And I agree with Raf that using C++/CLI is not a good idea. Far better to use pinvoke and simply call exported functions.

**Comment by Alovchin91** [comment]
@kennykerr @raffaeler I agree with you both on C++/CLI. It's always good to follow the standards and not invent the bicycle. And this is just one area in which seamless and transparent WinRT interop with custom components would come handy.

Anyway, I must say yet again that UWP is a failed experiment. I was experimenting with Desktop Bridge to make WPF app work with C# WinRT Component, and it just can't handle the references of .NET Core 2.0 (UWP 16299). I also figured out that on Windows 10 IoT Core, one can't run ASP.NET Core server in UWP background app, thus rendering a huge IoT scenario impossible for UWP.

After all, this makes UWP completely useless. On Desktop, we have traditional Win32 apps, which are much more advanced and are less tricky to deal with. On IoT, (thankfully) we have the ability to run console apps, which allow the scenarios that are essential for IoT and for some weird reason are impossible with UWP. On Xbox, we have a completely different experience, which implies writing a second full-fledged UI for the app, and that draws UWP as Universal platform useless. And how many apps do you _really_ need on Xbox anyway? On Mobile... well, we don't have Mobile anymore.

My point is - UWP has failed, it is more bad than good, and since Universal _tools_ are great and highly anticipated, the Universal _platform_ is completely useless. The Modern Windows should get over with UWP and let WinRT grow.

**Comment by Alovchin91** [comment]
@kennykerr It would be great to have an example of how one can hook the process of WinRT component activation from the desktop app! In regards of C#, maybe it could be possible to debug .NET Core runtime to see what it does when activating WinRT class and what can be done to hook this process.

**Comment by kennykerr** [comment]
I posted an example here:

https://gist.github.com/kennykerr/3649b0878824ead2755e1f7c86e4270a

You're definitely off-roading here, but I wanted to show that the OS itself does not prevent you from doing this. Naturally, Desktop Bridge is the recommend approach but since many of you are asking about how to do it without any restrictions from a desktop app then this should get you going. 

Hope that helps.

**Comment by raffaeler** [comment]
> Hooking activation in C# is a little tricky. You'd have to avoid constructors and statics and call DllGetActivationFactory via pinvoke (I tried this and it seems to work).
I was aware of that, it basically means skipping the C# generated projection and treating the component as a raw dll, but still relying on the vtable of the component to call the C++ methods.

@kennykerr thank you for the gist sample, I appreciate it too. Anyway it is quite an hack that can hardly be accepted in certain enterprise scenarios.

> > It is not a technical problem, it is just a political thing

> That's not entirely true. It is mostly a problem of time and conflicting priorities. 

You certainly have more details than me. I wrote that based on various discussions I had in the past @ build conference.
Frankly speaking, when talking to customers, UWP is out of discussion. It made sense in 2011 but a lot of things has changed since then and now there is not the same requirements to invest in a platform that is extremely limited without the benefits of going xplat and mobile.
What I hear is the need for something like Electron, that can produce desktop and/or UWP outputs. The problem with Electron is the very bad interop story, the bloat of memory usage and JS. The advantage is to have a solid structure like Angular. But all of this is OT here, sorry...

**Comment by Alovchin91** [comment]
@kennykerr @raffaeler Here's a funny experiment.

I just built the .NET Core 2.0 console app which references C# Windows Runtime component.
When I run this configuration using the "dotnet run" or the self-contained .exe, it crashes with TypeLoadException - as expected, it cannot find Windows Runtime class.
But if I build CoreCLR from sources in Debug configuration and run the app via CoreRun.exe, it works! It successfully read .winmd file, gets code from it and runs it!

I'll try a few tricks later today (C++ WinRT Component and the Release build of CoreCLR) to see if this really proves this is an artificial limitation, or it's just how CoreRun.exe reads managed assemblies inside .winmd file. I'll update this post accordingly.

**Comment by raffaeler** [comment]
@Alovchin91 out of my curiosity, can you post the InnerException(s)?
Also please set COREHOST_TRACE env variable to 1 and look at the console output to see if something interesting arise from the log.

**Comment by Alovchin91** [comment]
@raffaeler If you mean the TypeLoadException, here's a full exception information as printed out to console:
```
C:\Users\Alovchin\Downloads\coreclr-2.0.4\bin\Product\Windows_NT.x86.Debug>corerun C:\Users\Alovchin\source\repos\WinRtOnDesktop\ConsumerApp\bin\Debug\netcoreapp2.0\win10-x86\publish\ConsumerApp.dll

Unhandled Exception: System.TypeLoadException: Requested Windows Runtime type 'NativeRuntimeComponent.MyClass' is not registered. ---> System.Runtime.InteropServices.COMException: Класс не зарегистрирован (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))
   --- End of inner exception stack trace ---
   at System.StubHelpers.StubHelpers.GetWinRTFactoryObject(IntPtr pCPCMD)
   at NativeRuntimeComponent.MyClass..ctor()
   at ConsumerApp.Program.UseWinRtClass() in C:\Users\Alovchin\source\repos\WinRtOnDesktop\ConsumerApp\Program.cs:line 24
   at ConsumerApp.Program.Main(String[] args) in C:\Users\Alovchin\source\repos\WinRtOnDesktop\ConsumerApp\Program.cs:line 17
```
It doesn't seem to have any inner exceptions if I run the self-contained .exe, though:
```
C:\Users\Alovchin\source\repos\WinRtOnDesktop\ConsumerApp\bin\Debug\netcoreapp2.0\win10-x86\publish>ConsumerApp.exe

Unhandled Exception: System.TypeLoadException: Could not find Windows Runtime type 'NativeRuntimeComponent.MyClass'.
   at ConsumerApp.Program.UseWinRtClass()
   at ConsumerApp.Program.Main(String[] args) in C:\Users\Alovchin\source\repos\WinRtOnDesktop\ConsumerApp\Program.cs:line 17
```
The code that throws exception is in `coreclr-2.0.4\src\vm\interoputil.cpp@6968`:
```cpp
HRESULT hr;
SafeComHolder<IInspectable> pFactory;        
{            
    GCX_PREEMP();
    hr = clr::winrt::GetActivationFactory<IInspectable>(hName, &pFactory);
}

// There are a few particular failures that we'd like to map a specific exception type to
//   - the factory interface is for a WinRT type which is not registered => TypeLoadException
//   - the factory interface is not a factory for the WinRT type => ArgumentException
if (hr == REGDB_E_CLASSNOTREG)
{
    ThrowTypeLoadExceptionWithInner(pMT, WindowsGetStringRawBuffer(hName, nullptr), hr, IDS_EE_WINRT_TYPE_NOT_REGISTERED);
}
else if (hr == E_NOINTERFACE)
{
    ...
```

**Comment by raffaeler** [comment]
It looks like you are still leveraging the .net projection to activate the winrt component instead of using the activation provided by @kennykerr in his snippet.
By calling the constructor, the CLR hook the call and plugs in the default activation which actually does not allow to call custom components.
Did I miss something?

**Comment by Alovchin91** [comment]
@raffaeler Yeah, I'm now trying to investigate how the CLR reads the WinRT components referenced by the managed code)

The thing is, I tried breaking on RoGetActivationFactory in disassembler, and it did break on Windows.* APIs but did not on C# WinRT component. I made assumption that CLR calls something other than RoGetActivationFactory first, but it seems like it treats managed and unmanaged WinRT components differently. Still I'm yet to find out how exactly does it treat the managed WinRT component, because debugging CoreRun.exe gives nothing - it seems like it just reads the .winmd as a managed assembly.

I'm trying to find this out because I see more value in using WinRT components for managed/unmanaged interop, since you can reference your C++ code from a C++ app (or C# code from C# app) directly. While it's pretty straightforward to call DllGetActivationFactory in C++ DLL, it seems the activation flow for a managed component is a bit different.

BTW, the COREHOST_TRACE log contains only information about reading the .winmd metadata files into the domain, I don't see anything useful in it. There is no additional info when the app tries to access the runtime component.

**Comment by raffaeler** [comment]
@Alovchin91 if you go straight with netcore, it has no clue of windows-specific things, therefore I expect the projections are not created and the component is treated as there was no winrt.
If you share a gist or a project with the comparison test, I can take a look at it. I have a lot of (my own) tools and docs with details about activation that I wrote few years ago, when I initially was more enthusiast of winrt as the future of windows.

**Comment by Alovchin91** [comment]
@raffaeler .NET Core perfectly knows about WinRT type system :) Just take a look at all those winrt* files [here](https://github.com/dotnet/coreclr/tree/master/src/vm). It's just that CoreRun.exe takes all the .winmd files and parses metadata from them, and the CoreCLR Host does not. I'm now trying to figure out how is this done, and regardless whether I succeed I'll post a couple of Gists soon.

**Comment by raffaeler** [comment]
@Alovchin91 I am not sure we are talking about the same coreclr.
There is netcore using coreclr and UWP (managed) using corert which is a different flavor using the .net native feature.
I may be wrong, but it would surprise me to see the coreclr on ubuntu supporting winrt contracts :)

**Comment by Alovchin91** [comment]
@raffaeler Yes, this is the same CoreCLR, you can take a look at its repo. It has "IsWinRTSupported()" function though, so no, you won't see Ubuntu supporting WinRT contracts :)

Regarding WinRT, it seems that with .NET Core the only issue is that its default host doesn't correctly set ApplicationContext to point to application directory, and so it doesn't get the correct info from RoResolveNamespace API. And this API is delay loaded.

I'll check all this stuff on .NET Framework tomorrow with Microsoft's Detours library.

**Comment by Alovchin91** [comment]
@raffaeler @kennykerr Hey guys, so I finally uploaded the project to GitHub. Honestly, preparing it for GitHub took about the same time to do as the actual investigation 😆

Here it is: https://github.com/Alovchin91/WinRTDesktopInterop

The sample uses C++/WinRT from the latest available Insider SDK (17061 as I write this). I'll write a wiki page explaining in details what is happening there a little bit later, but for now here's a short overview:

* .NET relies on **RoGetActivationFactory** function to get the actual object; but it also relies on **RoResolveNamespace** function when getting the object metadata.
* Both function need to be hooked using the trampoline function method. In this sample, Microsoft Detours library is used, though you can use any other hooks library (like MinHook).
* RoResolveNamespace is the easy one: you just need to call it with the path to the application dir as parameter.
* RoGetActivationFactory is replaced with the algorithm based on what @kennykerr provided.

This method allows you to call not only the default constructor of the object, but also any custom constructors and static methods. I will update the sample C# app with examples of these in the coming days.

@kennykerr I've noticed that you have updated your Samples repo and included the project with the snippet above. It would be great if you could add reference to my project (or maybe even copy it to your Samples repo) so the others would see the solution. I believe it's really important for Windows Runtime as a platform. Thank you!

**Comment by mcosmin222** [comment]
Hi @kennykerr , I really do not see what can be more important than hooking winRT into desktop apps. In my opinion, this is the biggest impediment for the enterprise adopting winRT en-mass. 


I think your biggest priority should be seamless integration between UWP and win32/.net, so one can easily call into the other's technology (UWP into .net and .net into UWP for instance). As long as you stay tied to "UWP" (universal to what? it was never truly universal to begin with), winRT is basically just a learning experiment.

As for the demo project by @Alovchin91 , it is cool and nice, but as nothing more than an academic research project, maybe PhD worthy, but nothing more. No sane project manager is ever going to approve this into their enterprise application, nor will developers learn en-masse how to do this. Perhaps if VS did this by itself, so then we go back to the "full stop" problem...

**Comment by Alovchin91** [comment]
@mcosmin222 It's definitely a research and PoC project, even though you could perfectly compile the hooks into your WinRT implementation DLL 🤣 It would definitely be better to make a pull-request into CoreCLR repo to support this scenario without hooks (and now I'm calling for @terrajobst into this thread...).

I believe it's the "chicken-and-egg" problem we see here. Someone made a very shortsighted decision about 7 years ago that 3rd party (only 3rd party - sic!) WinRT components would be available only to AppX container apps. Since then, Microsoft paid near-zero attention to this issue, because WinRT wasn't widely embraced by developers (and especially by enterprises) - but developers didn't embrace WinRT because it had too many flaws and Microsoft didn't pay enough attention to WinRT.

I'm going to make some hype on this in a coming weeks - writing articles about it on CodeProject and local Russian IT site Habrahabr. I just hope I'll have enough enthusiasm 😃 I don't expect much from this but I hope Microsoft would finally listen to their developers some day.
