### ISSUE TITLE
SDK integrated cppwinrt - include file guidance

### ISSUE THREAD

**Issue by mediabuff** [Microsoft/cppwinrt#271]
The standard include paths now seem to have these (in order):
1) C:\Program Files (x86)\Windows Kits\10\Include\10.0.17025.0\winrt
2) C:\Program Files (x86)\Windows Kits\10\Include\10.0.17025.0\cppwinrt (which has a subfolder winrt)

What is the right way to include cppwinrt headers in Win32 and UWP apps respectively

how does it pickup the cppwinrt version in win32  in the following 

#include <windows.foundation.h>  -> come from 1)
#include <winrt/Windows.Foundation.h>  --> also comes from 1). But I really need 2)

or should itbe
#include <cppwinrt/winrt/Windows.Foundation.h>

**Comment by Scottj1s** [comment]
If you manually add the common ancestor to 1 and 2 (e.g., 1.C:\Program Files (x86)\Windows Kits\10\Include\10.0.17025.0), you'll have the ambiguity you mention.  If you allow VS (for the console) or the SDK (for VS projects) to set the include path, it will explicitly add 1 and 2, and there will be no ambiguity, as long as C++/WinRT headers are always #included via the "winrt/" subfolder.

**Comment by mediabuff** [comment]
>.If you manually add the common ancestor to 1 and 2 (e.g., 1.C:\Program Files (x86)\Windows Kits\10\Include\10.0.17025.0) to your include path, you'll have the ambiguity you mentio
No, I did not manually add. The VS generated (prior to 17025/sdk) has this sequence.

Are you suggesting that I we create a new project from IDE (post 17025) there will be no issue

>>it will explicitly add 1 and 2, 
Isn't the explicit addition causing the conflict ?

**Comment by Scottj1s** [comment]
It isn't necessary to create a new project in VS to make use of the cppwinrt SDK headers.  It's only necessary to retarget to SDK version 10.0.17025.0 (or later).  This in turn will add four SDK folders to your include path, all relative to the SDK root: um, shared, winrt, and cppwinrt.  The file C:\Program Files (x86)\Windows Kits\10\DesignTime\CommonConfiguration\Neutral\UAP\10.0.17025.0\UAP.props accomplishes this.  There should be no conflict with these additions, if you follow the rules for inclusion:  
#include <windows.foundation.h> -> to pull in the ABI header (1)
#include <winrt/Windows.Foundation.h> -> to pull in the C++/WinRT header (2)

Your conflict may be due to a relative include path element, like "..\", ahead of the SDK include paths.  Can you inspect your build output to see what your effective include path is, or confirm it in your project's C++ property sheet?

**Comment by mediabuff** [comment]
Thanks for the guidance and help.There was a redefinition of WINAPI_FAMILY macro in one of app headers and that caused a cascading set of issues.
