### ISSUE TITLE
explicit specialization; 'winrt::impl::abi<winrt::Windows::UI::Xaml::Interop::TypeName>' has already been instantiated

### ISSUE THREAD

**Issue by eklipse2k8** [Microsoft/cppwinrt#276]
Getting this error when building with the latest SDK:

1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.17035.0\cppwinrt\winrt/impl/Windows.UI.Xaml.Interop.0.h(81): error C2908: explicit specialization; 'winrt::impl::abi<winrt::Windows::UI::Xaml::Interop::TypeName>' has already been instantiated

**Comment by kennykerr** [comment]
This is a known issue that I fixed some time back. Unfortunately, the Windows SDK ships with a rather old version of C++/WinRT. We're looking into fast-tracking the next update so that it contains the very latest compiler and headers. Sorry about the inconvenience. We hope to ship another update before the end of the month.
