### ISSUE TITLE
Windows Runtime needs much more attention

### ISSUE THREAD

**Issue by Alovchin91** [Microsoft/cppwinrt#277]
Since many people (me among them) believe this project is the future of Windows Runtime, I think this is the best place for this suggestion.

Windows Runtime is a much better COM, which means this could and _should_ be **the** technology for the Modern Windows API. But for now, it doesn't get enough attention.

What I'm talking about is that, few years into Windows 10 and almost 6 years into Windows Runtime, UWP is a failed experiment. And Windows Runtime **needs** to break through the boundaries of this experiment.

Since it's a much better COM, it should be fully available for traditional Win32 apps to accomplish their tasks within the Modern Windows OS. This means:

* Extending available WinRT APIs to the state where they can supersede the traditional Win32 API
* Allowing Win32 apps to consume custom WinRT components. This is especially useful in terms of .NET apps that need interop with native code. This is a much better registration-free COM, this _should_ be **the** technology for this kind of tasks!
* Since WinJS is no longer developed, and Fluent design is not supported for WinJS apps, and we hear less and less about HTML/JavaScript UWP apps, Windows Runtime vNext should consider moving away from JS support. This would make those custom WinRT components much more ABI friendly: you would be able to write non-sealed classes (like current XAML ones), jagged arrays, custom exceptions, etc. etc.

Like many people following this project, I believe Windows Runtime is the future of Windows API. But for now, it is stuck on failed UWP experiment. It needs to break through these chains to shine.

**Comment by mcosmin222** [comment]
One of the biggest issues with winRT is enterprise adoption. Until UWP managed to break through the enterprise world, winRT will likely not see the love of developers, and in my opinion, the biggest obstacle towards wide spread adoption is the strict life cycle of UWP apps, which limits many multitasking scenarios.

Allowing classic apps to consume custom winRT components would be a great start. To this end, maybe Visual Studio should present with the options to reference Universal Windows by default in classic templates targeting just windows 10. 

Another big issue with performance, especially async only file access. Async is all great, but it does introduce latency, this makes winRT "async-only" IO model unsuitable for real-time applications. The async interfaces should proved ways to run IO blocking and reduce latency. 

And now let's get over the Platform::String class. This class needs a lot of love. Having to reference additional string libraries is a really bad idea. Operations like "Contains", "Split" or "IndexOf", "ToLower/Upper" should be supported out of the box. There should be no reason to have to use one additional string library just to be able to do these, and many of these libraries do not provide adequate support for internationalization.

**Comment by eklipse2k8** [comment]
@mcosmin222 I find boost's string algorithms just work out of the box with cppwinrt's projection. They did a fantastic job of bridging the two worlds, but don't forget, at the end of the day, an HSTRING is just a preallocated block of typed memory.

**Comment by eklipse2k8** [comment]
@Alovchin91 The WinJS effort seemed to stall out, weirdly, even though it's clear that companies want to build JS applications (eg. electron) and Visual Studio Code could have been the perfect dogfooding for that.

The weirdest thing to me about UWP, as it stands today, is how committed to C# Microsoft has become and I guess it makes sense from a developer experience. The only problem is the application that I'm writing can't be done properly in a managed environment. So I look to cppwinrt as the ray of sunshine in an otherwise cloudy platform. I love that Windows itself is being rewritten on top of WinRT, as that means this is a safe platform to build on top of, but I do agree that XAML being locked to a ICoreWindow vs. a  HWND is probably holding it back from greator adoption. I suspect that will change over time.

**Comment by Alovchin91** [comment]
@mcosmin222 Regarding Platform::String, this is just a C++/CX projection of the HSTRING object, that is very similar to classic COM's BSTR, but is used exclusively for Windows Runtime ABI. C++/WinRT makes it very easy to convert from std::wstring to winrt::hstring, so when you work with strings in C++/WinRT, you actually work with standard C++ strings and just pass them through the ABI using the winrt::hstring object. HSTRING (and thus Platform::String that doesn't exist outside hopefully fading C++/CX) is just an array of wchar_t's plus some string specific info (like the length of the string).

@eklipse2k8 I can imagine why this WinJS effort was abandoned. It should've been a one-timer aimed to attract as much developers as possible to adopt UWP, and it seems like this goal is either accomplished or considered useless. Since inside Windows 10 there is XAML, that IE (or Edge) engine inside the UWP app just doesn't expose the real underlying platform. On the other side, C# interop with WinRT, though immature, does expose the whole potential of XAML platform, and the platform itself is very familiar for C# (WPF) developers, thus the commitment.

But I definitely agree with you, and this is just pt. 4 in aforementioned list - WinRT needs to break through the bounds of XAML and provide the API for low level HWND manipulation. It just needs to supersede traditional Win32 API.

**Comment by MikeGitb** [comment]
Sorry if this is a naive question, but does the old win32 API even use com? What few native API calls I've made so far where simple C functions.

That aside, I think that issue confuses/mixes API technologies ("normal" C, com, com wrapped in proper c++ classes as in cppwinrt) with API collections (classic win32 vs winrt).

IMHO the main problem with winrt at the moment is that it is limited to win 10 and as win 10 mobile didn't really take off that market is much smaller than that for classic win 32 applications. That might change once win 7 support has ended.

**Comment by Alovchin91** [comment]
@MikeGitb I meant the whole set of current Win32 APIs — not only plain C kernel APIs, but also COM APIs provided by shell, networking, DirectX etc. They all need a refresh and WinRT is the technology that should lead this refresh.

I mean, we still get some Win32 (read — Windows desktop, classic Windows) APIs exposed in traditional COM — one of the latest examples is [INotificationActivationCallback](https://msdn.microsoft.com/en-us/library/windows/desktop/mt643711) interface.

We remember those experiments in Longhorn to transition Windows API to COM 2.0. They failed because COM 2.0 was managed — that is .NET Framework. And now we have COM 3.0 — that is Windows Runtime — and it's unmanaged and still compatible with .NET. Now this is a great start to refresh the whole Windows API.

**Comment by BenJKuhn** [comment]
The Windows Runtime is our premier API experience for Windows. It certainly expands beyond just Store applications and UWP, though as Alovchin91 notes, there are some gaps for applications that are not deployed via the store. Classic Win32 desktop applications can use most Windows Runtime APIs, but can't expose their own types. The desktop bridge (https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-root) helps significantly in that desktop bridge applications can use the full win32 suite of APIs and create Windows Runtime components.

With regard to inheritance, JavaScript isn't the only limitation. Windows Runtime inheritance is far more limited than native inheritance both in capability and performance, because the composed type is actually a set of aggregated objects, not a single, coherent derived type. It's a useful abstraction, but one that we would continue to apply very sparingly even without JavaScript as a consideration. We're still committed to our JavaScript programming experience though, so for platform APIs, that remains a key consideration.

Our goal continues to be to provide well-integrated experiences for developing in common programming languages. We've shifted a bit in that in years past, we would have pushed to make nearly everything Windows Runtime APIs, with some light language integration around basic types. Today, we try to complement and integrate with the libraries for each language better, rather than trying to supplant features with clumsy cross-language implementations. This shows in the design choices in C++ /WinRT in many ways.

Right now, we're focusing most of our energy on making sure that the Windows Runtime APIs continue to develop into a rich, performant API surface. Bringing the existing APIs forward is a complex task. It is something that we're interested in, but not investing in heavily at this time. Kenny started C++ /WinRT as an independent project that Microsoft eventually adopted. @Alovchin91 If you have some great ideas about how to bring the morass of Win32, COM, and psuedo-COM APIs forward into a more modern programming experience, just start building it. Share it. Get feedback. If it gets traction maybe someday we'll be having a conversation about folding it into the Windows SDK.

If you do get something started, keep us posted on progress.

Ben

**Comment by Alovchin91** [comment]
@BenJKuhn Just to make sure this issue also gets the link, here is a sample project showing the simple way to make custom WinRT component usable from desktop .NET app:

https://github.com/Alovchin91/WinRTDesktopInterop

The discussion is happening in #256 and (perhaps) Alovchin91/WinRTDesktopInterop#1.

**Comment by mcosmin222** [comment]
@Alovchin91 , nice one. However, its implementation and internal complexities will put off most .net developers at bay. Perhaps if Microsoft were to develop a tool into VS to allow seamless integration...

**Comment by Alovchin91** [comment]
@mcosmin Hey, good to read you again :) Let's move to #256 - we discuss just that in there)
