### ISSUE TITLE
Can we use WinRT with Direct3D applications without any specializations?

### ISSUE THREAD

**Issue by macxfadz** [Microsoft/cppwinrt#282]

**Comment by kennykerr** [comment]
I'm not sure what you mean by specializations. C++/WinRT provides a language projection for types that are described by WinRT metadata. Direct3D APIs are currently not described in that manner. Of course, you can still write [Direct2D and Direct3D applications](https://github.com/kennykerr/cppwinrt/tree/master/Direct2D) with C++/WinRT as we interop very well with COM APIs.

**Comment by macxfadz** [comment]
@kennykerr  Thank you very Kenny for your reply.I take this opportunity for thank you for another thing.I learnt lot of Win32/C++ stuff from your Pluralsight  lectures.Awesome!.

**Comment by kennykerr** [comment]
Thanks!

> When we able to get WinRT release with VS2017 update ?

We're working on direct Visual Studio support. I'm not yet sure when that will land.

> You developed Win2D project right? do you have an idea to develop Win3D project like that in near future? 

No, I didn't write Win2D. I worked on other DX projects aimed at C++ developers. Win2D is a very impressive WinRT component, however it is ultimately a wrapper around Direct2D and friends. My job is to make it easier to write high-performance APIs and then hopefully the folks that own Direct2D and Direct3D will be more inclined to deliver an official set of WinRT APIs that speak directly to the GPU.

**Comment by macxfadz** [comment]
@kennykerr  and @walbourn  Please correct me if I have got wrong idea here(Since I am new to the hood ;) ) I really eager to learn and build applications(simple 3D games) for PC (**x64** machines) using **_D3D_** and **_Vulkan_** APIs with WinRT native C/C++ support,
Can you give me instructions/advice(kick start-up) how to integrate these technologies properly in order to build such clean and efficient program ?

- GPU Vendor(Driver) support + D3D 12 + WinRT C/C++ 

-  GPU Vendor(Driver) support + Vulkan 1.xx + WinRT C/C++

**Comment by walbourn** [comment]
If you are new to Direct3D, you should strongly consider learning DirectX 11 first.  DirectX 12 is a challenging API to use and is intended for professional graphics developers who already fully understand the existing DirectX technology. Both DirectX 11 and DirectX 12 essentially drive the same hardware and expose the same hardware features, but manage the GPU differently.

One challenge with learning DirectX 11 is that a lot of the material online and in books is a little dated in terms of use of the legacy DirectX SDK components (``D3DX11`` for example), and uses older-style C++ (i.e. not "Modern C++" C++11/C++14 style). The DirectX Tool Kit tutorials do use modern C++ style and avoid the legacy components, and it can be used as a starting-point since the abstractions for the [DX11](https://github.com/Microsoft/DirectXTK/wiki/Getting-Started) and [DX12](https://github.com/Microsoft/DirectXTK12/wiki/Getting-Started) versions are similar.

The Direct3D APIs when used from native C++ are the same whether you are using them in them in the context of a Win32 desktop app, a C++/CX UWP or Xbox One app, or a C++/WinRT UWP or Xbox One app. I provide some useful starting Visual C++ templates [here](https://github.com/walbourn/directx-vs-templates/wiki).

> I can't speak to Vulkan here other than to say that neither OpenGL nor Vulkan are supported for UWP or Xbox One apps.

Typically for a Direct3D-based game, the Windows Runtime APIs are only used for CoreWindow interactions, some data storage functionality, and if you are using Xbox LIVE. Core rendering, game logic, threading, etc. are all pure, native C++ code.

**Comment by macxfadz** [comment]
@walbourn  wow.. Thank you for the great valuable information...  

> (D3DX11 for example), and uses older-style C++ (i.e. not "Modern C++" C++11/C++14 style). The DirectX Tool Kit tutorials do use modern C++ style and avoid the legacy components, and the DirectX 11 version can serve as a good starting-point for eventually learning DirectX 12 since the abstractions for the DX11 and DX12 versions are 

As  you mentioned,Learn **DX11** pipeline and implement **DX11** with Modern C++ is the better starting point !!! before jump in **DX12** and **Vulkan** ,I think DX12 and Vulkan APIs conceptually similar but core and implementation wise widely differ.
