### ISSUE TITLE
Question about pointers

### ISSUE THREAD

**Issue by tbandrowsky** [Microsoft/cppwinrt#299]
A while ago I had written a simple article where I was trying to get the map control to work in cpp/winrt but could not.  Kenny Kerr was kind enough to look into it and discover that it worked, but I must have been doing something wrong. Well, I managed to have a look at my code and discovered that I was declaring my map control in the class body and not inside the onlaunched method. Once I did this, everything worked:

	MapControl *mainMap;
	StackPanel *mainHazards;

	void OnLaunched(LaunchActivatedEventArgs const &)
	{
		Grid mainGrid;
		StackPanel spHazards;
		MapControl mpMap;

		mainMap = &mpMap;
		mainHazards = &spHazards;

On one level, it makes sense that this works, given all the plumbing going on underneath, but on the other, it violates everything we have learned about C++ - you know, copying a pointer to an object on the stack and all of that.

So my question is, what's really the right pattern for doing this sort of thing.  I have to declare my MapControl in OnLaunched for this to work, but how do I get a reference to it outside of OnLaunched.  MapControl::MapControl() actually does some serious plumbing under the hood.  Or is it that the pointer is in fact the way to go because the & operator is somehow overloaded on these objects.

**Comment by DefaultRyan** [comment]
That may because the default constructor attempts to activate the object. You need to initialize with a nullptr to avoid immediate (i.e. before COM init and on the wrong thread) activation.

You could try declaring it in the class body as:
MapControl mainMap { nullptr };

And then in your OnLaunched method:

mainMap = MapControl{};

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by tbandrowsky** [comment]
That completely worked. Thank you!
