### ISSUE TITLE
Addressing Id in DeviceInformation

### ISSUE THREAD

**Issue by jevansAN** [Microsoft/cppwinrt#325]
Having succeeded in obtaining a DeviceInformationCollection using a co_await with DeviceInformation::FindAllAsync(portSelector) I would like to create a MIDIPort using the deviceId of one of the DeviceInformation objects. Winrt docs in C# do this with, e.g. identifier = deviceInfo.Id;
and I assume that in cppwinrt that would be deviceInfo.Id(); but neither can be used. When attempting to access the Id I am told that DeviceInformation has no member "Id." How would one access the information in DeviceInformation using cppwinrt?
I  have found it necessary to declare the DeviceInformation object as

    `winrt::Windows::Foundation::Collections::IIterator<winrt::Windows::Devices::Enumeration::DeviceInformation> devInfo`

since winrt::Windows::Devices::Enumeration::DeviceInformation devInfo is not accepted as a return value when fetching from DeviceInformationCollection using, for example, devInfo = m_output_devices.First().  But I have a feeling this declaration must have something to do with the problem. DeviceInformation objects are used elsewhere than just in MIDI, though, so perhaps someone has a solution.

**Comment by DefaultRyan** [comment]
Sorry, but this is not a technical support forum for the WinRT API. Your issue does not appear to be a C++/WinRT bug, but seems to be a question about the basic functionality of IVectorView and IIterator.

Those usage/API questions are more appropriate for StackOverflow where there is a C++/WinRT tag dedicated for these questions (https://stackoverflow.com/questions/tagged/c%2b%2b-winrt) and you’re far more likely to get a quicker response there, simply because of the larger audience there. Additionally, the developer community as a whole would prefer these questions happen there, so that other developers can search for and see those questions and answers.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by jevansAN** [comment]
Default Ryan: Sorry, I don't see why it is not a cppwinrt question. The whole point is that the approach recommended in the winrt documentation does not work in cppwinrt. Therefore there must be a different approach required for cppwinrt. Is this not the place for cppwinrt issues?

**Comment by kennykerr** [comment]
Ryan's right. You are using the API incorrectly and as such this is not a C++/WinRT bug. Post the question on StackOverflow and one of us will be more than happy to answer.
