### ISSUE TITLE
C++/WinRT headers incompatible with "Creators Update"

### ISSUE THREAD

**Issue by rigdern** [Microsoft/cppwinrt#334]
### Repro Steps

- Get cppwinrt.exe from the Windows SDK 10.0.17095
- Use cppwinrt.exe to generate OS headers for the Creators Update (10.0.15063.0)
- Compile a C++ file which includes "winrt/base.h" against the Creators Update headers

Unexpected result: compilation errors:

```
winrt/base.h(10171): error C3861: 'OpenThreadToken': identifier not found
winrt/base.h(10218): error C3861: 'SetThreadToken': identifier not found
winrt/base.h(10224): error C3861: 'SetThreadToken': identifier not found
```

This also reproed in the latest cppwinrt.exe build I could find (1.0.180223.1).

### Cause

Comparing the Windows SDK headers for the Creators Update and the Fall Creators Update, it looks like `SetThreadToken` transitioned from `WINAPI_PARTITION_DESKTOP` to `WINAPI_PARTITION_APP`.

Adam Comella
Microsoft Corp.

**Comment by kennykerr** [comment]
We ship C++/WinRT in a particular Windows SDK and you are expected to build your apps with that SDK. If you want to use an older version of C++/WinRT then you can use the corresponding SDK that it ships in. We make a concession today for RS3 since RS4 has not yet shipped, but in general here is how you might target older platforms:

![platform](https://user-images.githubusercontent.com/9845234/36621589-9968198a-18ad-11e8-8670-a598a66bd49f.png)

**Comment by rigdern** [comment]
@kennykerr My understanding is that the only place `cppwinrt.exe` currently ships is in preview versions of the RS4 Windows SDK. Is that correct?

Can you clarify what `cppwinrt.exe` supports in terms of "Target Platform Version" and "Target Platform Min Version"? In other words, what's the minimum you can specify for target and min target?

Here's some context on what I'm doing. My app's target is RS2 (we're moving to RS3 soon) and min target is RS1. I grabbed `cppwinrt.exe` from a preview RS4 Windowsz SDK and used it to generate C++/WinRT OS headers for RS2. Everything worked great. I tried upgrading to the `cppwinrt.exe` in Windows SDK 10.0.17095 and ran into the errors I listed in my post.

Adam Comella
Microsoft Corp.

**Comment by kennykerr** [comment]
C++/WinRT itself relies on a minimal set of OS services. Those services are available all the way back to Windows 8.1.  You may however experience different constraints depending on the version of the Windows SDK you're using because different functions, like `OpenThreadToken`, may not have been available to store apps on older platforms. That's one of the reasons we only support using C++/WinRT with the version of the Windows SDK that it ships with.

That is the case for the RS4 version of C++/WinRT. RS5 may well adopt some new OS services that preclude its use on older platforms. Naturally, an older version of C++/WinRT will continue to work to support such a scenario.

**Comment by rigdern** [comment]
I'm not sure I totally understand the details. I have some followup questions:

1. You said that you only support using C++/WinRT with the version of the SDK that it ships with. Suppose it's the future and RS4 is officially out. I'm building my UWP app for RS4 (so "Target Platform Version" in VS is set to RS4). I'm using the version of C++/WinRT that ships with the RS4 Windows SDK. I want my app to run all the way down to RS1 (so "Target Platform Min. Version" in VS is set to RS1). Is this a supported scenario of C++/WinRT? I'm asking because if C++/WinRT happens to call an API like `OpenThreadToken` on RS1, something bad will happen. It seems that if C++/WinRT supports this, it must either avoid `OpenThreadToken` on RS1 or it must document what C++/WinRT APIs are supported on RS1 (C++/WinRT APIs which just wrap WinRT APIs are excluded because the WinRT docs cover that).
2. Regarding only using C++/WinRT with the version of the SDK that it ships with, you said that RS3 is a special case because RS4 hasn't shipped yet. Questions:
    - Am I correct in assuming my UWP app can target RS3 (so "Target Platform Version" in VS is set to RS3) using the version of C++/WinRT that ships with the RS4 Windows SDK?
    - If yes, does that only apply to C++/WinRT in preview versions of the RS4 SDK or will it also apply to C++/WinRT in the official release of the RS4 SDK?

Adam Comella
Microsoft Corp.

**Comment by kennykerr** [comment]
Taking this offline.
