### ISSUE TITLE
Documentation: Ownership contract for event handlers

### ISSUE THREAD

**Issue by rigdern** [Microsoft/cppwinrt#336]
Suppose I have an object that registers for an event like this:

```c++
namespace winrt::MyLib::implementation
{
  void Test::RegisterForEvents()
  {
    someObject.SomeEvent(SomeEventHandler(this, &Test::OnSomeEvent));
  }

  void Test::OnSomeEvent()
  {
    // Handle the event
  }
}
```

Assuming that `someObject` is an object from the Windows SDK, how does it hold onto the `Test` object when it registers for an event? I'm interested in knowing what will happen if I never unregister the event. I can imagine several possibilities:
  - The `Test` object never reaches a reference count of 0 because `someObject` is holding onto it.
  - The `Test` object gets deallocated but bad things happen when `SomeEvent` fires because `someObject` still has a reference to the `Test` object.
  - The `Test` object gets deallocated and everything is fine when `SomeEvent` fires because `someObject` had a weak reference to the `Test` object.

It would be great to have these kinds of details in the `Docs` folder of this repo.

Adam Comella
Microsoft Corp.

**Comment by BrentRe** [comment]
A properly written SomeObject class will do one of two things:
1. SomeObject will hold a strong reference to the event handler (Test). Thus the Test handler will always be around when the event fires.
2. SomeObject will hold a weak reference to the event handler. Thus the event firing logic in SomeObject will first attempt to resolve the weak reference. If it fails, SomeObject will unregister the handler as the Test instance is already gone. If it resolve succeeds, SomeObject will fire the event using the resulting strong reference, then upon return from the handler, release the strong reference.

In case (1), if Test never unregisters the handler, there are two scenarios:
A. Test kept a reference to the SomeObject instance so it *could* unregister but failed to do so. Both the SomeObject instance and the Test instance remain alive forever due to the reference cycle.
B. Alternatively, Test registered for the event, then dropped its reference to SomeObject. Test will live as least as long as SomeObject does. Should some external mechanism cause SomeObject to destruct, SomeObject will release all registered handlers, including Test, allowing Test to destruct if there are no additional references to it.

In case (2), Test can be released during the intervals before SomeObject resolves the weak reference and after SomeObject fires the notification and releases the strong reference.
 
Note that this isn't specific to C++/WinRT. It how properly written Windows Runtime objects should behave.
