### ISSUE TITLE
Is modern.exe available ?

### ISSUE THREAD

**Issue by CedricMi** [Microsoft/cppwinrt#34]
In the video [Universal Windows Apps with Standard C++](https://youtu.be/0EcPdV0L_JU) Kenny Kerr uses modern.exe to generate basic projects, which is great.
Is this modern.exe tool available somewhere ?
![kennykerr-modern2](https://cloud.githubusercontent.com/assets/4855088/19889001/b7b3aba6-a032-11e6-85c8-cfce2a6c0d31.png)

**Comment by kennykerr** [comment]
The cppwinrt.exe (previously modern.exe) tool is not yet available. We hope to make it available in a future update.

**Comment by vixuque** [comment]
Hi!
Excuse me for ask again the same.
Visual Studio 2017 comes with enhaced c++ support and with c++/winrt support.
I guest an utility like modern for make probes.
It will be spent more time for modern.exe release ?

Thanks.
This project is fantastic and will give an impactly progress for using c++ easy in Windows.

**Comment by jevansAN** [comment]
I read that cppwinrt.exe is included in SDK 17035. But I've updated as a Windows Insider, also downloaded the cppwinrt folder at github, and there is still no cppwinrt.exe anywhere in the system. Where exactly is this thing?

**Comment by kennykerr** [comment]
[It should be here](https://moderncpp.com/2017/11/15/cppwinrt-exe-in-the-windows-sdk/):
 
C:\Program Files (x86)\Windows Kits\10\bin\10.0.17035.0\x86\cppwinrt.exe

**Comment by jevansAN** [comment]
Thanks, Kenny. I guess the real problem is that there is no 10.0.17035.0 directory in my Windows Kits - latest is 16299. I had assumed I'd receive all this when I installed the latest SDK using Windows Insider, etc.
I am able to compile and run the Blocks sample (once I change it to local device and x64 instead of ARM) but I'm not sure what else I could install to obtain cppwinrt.exe. But wasn't cppwinrt required to compile Blocks?

Yours, Jeff

On Dec 1, 2017, at 6:26 PM, Kenny Kerr wrote:

It should be here:

C:\Program Files (x86)\Windows Kits\10\bin\10.0.17035.0\x86\cppwinrt.exe

**Comment by kennykerr** [comment]
16299 is the RS3 SDK. That's not an Insider SDK. You can [download the latest Insider SDK here](https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewSDK). 17046 is the current version. That will have both the headers and the tool. 

You do not however need the tool for most apps. The headers are included in the SDK so that you can simply include them to build your app. That's all that most of the samples do. The tool is only required to author your own WinRT classes or produce headers for third party WinRT components. There are examples of both scenarios here:

https://github.com/kennykerr/cppwinrt

**Comment by jevansAN** [comment]
That is very useful, Kenny. Frankly I've found the descriptions of the way to get started with C++/RT to be amazingly confusing. I thought I had followed all the instructions for installing the latest Insider SDK - took long enough for it to install! 

But I have a very large project for the Mac that is C++ with ObjC for the UI, and I am glad to know that there may now be a way to build in the contemporary style for Win10 without having to make a lot of awkward adjustments between straight C++ and C++/CX. I'm not planning to author RT classes.

I would like to use xaml markup if possible, but my understanding is that this can be done in RT. 

Thanks, Jeff

On Dec 1, 2017, at 8:15 PM, Kenny Kerr wrote:

16299 is the RS3 SDK. That's not an Insider SDK. You can download the latest Insider SDK here. 17046 is the current version. That will have both the headers and the tool.

You do not however need the tool for most apps. The headers are included in the SDK so that you can simply include them to build your app. That's all that most of the samples do. The tool is only required to author your own WinRT classes or produce headers for third party WinRT components. There are examples of both scenarios here:

https://github.com/kennykerr/cppwinrt

**Comment by jevansAN** [comment]
Thanks for the response - I have the latest Insider SDK now, I think.
Is there a sample project somewhere that is all set up for at least creating all the common UI elements programmatically in C++? StackPanel, Gridview, etc. with illustrations of how the properties are set in C++.

For example, online I find an example of setting the background color of a control, e.g. button.Background = new SolidColorBrush(Colors.Red);
But that won't work here:"Identifier 'Colors' is undefined" and 'new' "...cannot be referenced; it is a deleted function."

With a full set of examples I think progress would be speeded.

Jeff
 
On Dec 1, 2017, at 8:15 PM, Kenny Kerr wrote:

16299 is the RS3 SDK. That's not an Insider SDK. You can download the latest Insider SDK here. 17046 is the current version. That will have both the headers and the tool.

You do not however need the tool for most apps. The headers are included in the SDK so that you can simply include them to build your app. That's all that most of the samples do. The tool is only required to author your own WinRT classes or produce headers for third party WinRT components. There are examples of both scenarios here:

https://github.com/kennykerr/cppwinrt

**Comment by MikeGitb** [comment]
You can find some Information here: https://github.com/Microsoft/cppwinrt/issues/215

**Comment by jevansAN** [comment]
Thanks -
	Is there any way to obtain a clicked button object from the sender argument IInspectable const & sender in a button click handler?
	None of the simple techniques mentioned in C++ discussions seems to be applicable. 
	The problem of referencing UI controls is one giving me particular trouble. It was pretty easy in C++/CX, but an entirely different problem in winrt, apparently.

	Jeff

**Comment by kennykerr** [comment]
This should do it:

```C++
Button button;
button.Content(box_value(L"Hello"));

button.Click([](IInspectable const& sender, RoutedEventArgs const& /*args*/)
{
    Button button = sender.as<Button>();
    button.Content(box_value(L"Clicked"));
});
```

**Comment by jevansAN** [comment]
Terrific- the first part of that works! Though I see an error marked in the code (wiggly underline of "sender" in "sender.as<Button>)

no suitable user-defined conversion from "winrt::impl::com_ref<winrt::Windows::UI::Xaml::Controls::Button> to "winrt::Windows::UI::Xaml::Controls::Button" exists

The second line does not compile, however:  E0020: 'Identifier "box_value" is undefined" and C3861 'box_value: identifier not found." And if the second line is present then the first one also turns in a real error E0312, same as mentioned above. Do you suppose something is wrong in my project settings?

**Comment by kennykerr** [comment]
I wouldn't trust IntelliSense.

Also, it turns out that the `box_value` helper is not yet in the SDK. It will be in an upcoming Insider SDK, probably in the new year. Until then you can use `Windows::Foundation::IReference<hstring>` to create a boxed string value.

**Comment by jevansAN** [comment]
Thanks again. Don't want to be a pest, but I can't find documentation for the use of IReference<hstring>.  Could you show an example?

**Comment by kennykerr** [comment]
This should work with the build in the 10.0.17040.0 SDK:

```C++
Button button;
button.Content(IReference<hstring>(L"Hello"));

button.Click([](IInspectable const& sender, RoutedEventArgs const& /*args*/)
{
    Button button = sender.as<Button>();
    button.Content(IReference<hstring>(L"Clicked"));
});
```

**Comment by jevansAN** [comment]
Wonderful. That does the job. I really appreciate your responsiveness.

**Comment by jevansAN** [comment]
And since this is such good progress: do you have a recommendation of a way to store references to particular UI elements? I had thought I could declare them as member variables in the application class, e.g.
struct App: ApplicationT<App>
{
private:
StackPanel panel1;
public:
static void OnLaunched(LaunchActivatedEventArgs const&);
...etc
}
But if I then attempt to reference that StackPanel in a member function, e.g.
void App::CreateMainPage()
{
panel1.Height(40);
}
I am told that "a nonstatic member reference must be relative to a specific object." Yet this reference to panel1 is to a member of the App struct. Seems to be it's redundant within the method to refer to that member as App.panel1, but doing so leads to a different error: the (40) gets marked with "expected a type specifier." Making the panel a static member produces still other errors down the line. Is there an acceptable way to maintain persistent references to particular UI elements so that they can be altered during runtime?

**Comment by kennykerr** [comment]
I don't understand the question. If you have a non-static data member then you can naturally call it from a non-static member function. It's up to you which members are static and which are not. It looks like you may be making your member functions static when you don't need to.

**Comment by jevansAN** [comment]
I guess I wasn't clear.  But your remark helped :  the member functions were static, as they were in the example project, and that was keeping them from addressing nonstatic members. Changing those to nonstatic member functions clears that up -but produces an error in base.h: "'H': is not a legal base class" Perhaps the member functions are required to be static. Yet if they are static there doesn't seem to be a way to reference stored UIElements from those functions whether they are static members or not.

**Comment by jevansAN** [comment]
To be more specific: if I redeclare those member functions as static, and declare the UIElement references as static members too, both produce "LNK2001 unresolved external symbol" errors.
public:
static StackPanel panel1; 
static Button button1;
static void OnLaunched(LaunchActivatedEventArgs const&);
etc.

**Comment by jevansAN** [comment]
But surely there must be some way to store a reference to a UI element when using cppwinrt. I expect I am missing something very simple.

**Comment by DefaultRyan** [comment]
There is no requirement that OnLaunched be static, and I wouldn’t recommend it, specifically because of the problems you are hitting (and more).

I suspect you have some other problem that was causing issues when you made the member variable and member function non-static.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by jevansAN** [comment]
That's good to know, Ryan - I was just basing this on one of the example projects in which OnLaunched was static.  I've followed pretty closely the instructions for setting compiler options, etc. in Vinoth Rajendran's "Learn Universal Windows Programming Via Modern C++" at C#Corner (oddly enough). But something must be wrong. Really would be great to see a cppwinrt example .sln all set up and ready to run, including examples of the more common UI elements, StackPanels, etc. and how to reference them in click handlers, etc. Maybe there is such a thing and I just can't find it.

**Comment by kennykerr** [comment]
I don't know what samples you're referring to. The only samples I recommend are these:

https://github.com/kennykerr/cppwinrt

Have a look at the XamlButton sample. Perhaps that will help to get your going.

**Comment by jevansAN** [comment]
Thanks, would love to try that. It appears to require SDK 17040, so I downloaded the latest preview SDK and installed it - that is 17046. Opened XamlButton in VS preview and changed its target SDK to 17046 since 17040 was of course not found, and it will not compile - produces a large error count. Starting to think I should just go back to Win32 desktop as per a decade ago.

**Comment by jevansAN** [comment]
This info might prove of use: After reinstalling the latest preview SDK and the latest VS preview, the XamlButton example will not load into VS at all: it offers this explanation: "Project 'XamlButton' could not be loaded because it's missing install components. To fix this launch Visual Studio Setup with the following selections: Microsoft.VisualStudio.Component.Windows10SDK.0" But I have installed the SDK and can see that it is visible in ProgramFiles(x86)/Windows Kits/10 and its manifest describes it as version 10.0.17046.0. Perhaps I need to revert to an earlier SDK?

**Comment by jevansAN** [comment]
I am probably driving you nuts at this point but let me try one more. I replaced the XamlButton project with the original, and got the message, "To deploy this application, your deployment target should be running Windows Universal Runtime version 10.0.17040.0 or higher. You currently are running 10.0.17025.1000. Please update your OS or retarget..." At Insider Preview, however, there is no OS available for download that is later than 10.0.17025. The SDK in Windows Kits is the latest: 10.0.17046.0. If I retarget for 10.0.17025.0, I am told that the SDK 10.0.17025.0 was not found - because of course I have installed the latest 17046 SDK. XamlButton has its target set to 10.0.17040.0, presumably out of necessity. Do you perhaps have access to a later build of the OS that is required to make this go?

**Comment by kennykerr** [comment]
It's no trouble, we just may not have the time to respond very promptly. You also have a confluence of problems unrelated to C++/WinRT and our team usually does not have the bandwidth to address them all. Often these sorts of questions have nothing to do with C++/WinRT and are best posted to forums like StackOverflow. 

Anyway, you can still use the 17040 SDK to write apps that will run on older versions of Windows. You can simply update the project settings in Visual C++ accordingly. You can see this in the [default project files here](https://github.com/kennykerr/cppwinrt/blob/master/XamlButton/XamlButton.vcxproj). Notice the `WindowsTargetPlatformVersion` and `WindowsTargetPlatformMinVersion` values.

**Comment by jevansAN** [comment]
Thanks - somehow this has solved it. I did have the WindowsTargetPlatformVersion set to 10.0.17040.0 and the WindowsTargetPlatformMinVersion to 10.0.16299.0, as in your link. And the SDK installed in Windows Kits is 10.0.17046.0, the latest. Earlier I had not luck changing that to 10.0.17040.0 - But! Now it runs. This is a great start. Maybe the reinstalls helped.

**Comment by jevansAN** [comment]
Having made that progress perhaps this would be generally useful info too: Is it yet possible in winrt to use xaml, though without the designer? It would be handy to build the interface that way even without the help of the designer - but I see that I use Add New Item to add a default MainPage.xaml file the project will no longer build. The errors are "The type 'Page' was not found, and "The type 'Grid' was not found," and "Cannot resolve 'Windows.metadata'. Please install the Windows Software Development Kit..." It appears that VS creates an unusable file by default. If I Exclude that mainpage.xaml file the project of course again builds normally.

**Comment by jevansAN** [comment]
I notice that if I copy the buttonclick method from Xamlbutton into a method of my own, "IInspectable" is determined to be ambiguous and will not compile. In an example by Andrew Webb from 2016 I see he has used a fully qualified name, 
void myButtonClick(winrt::Windows::IInspectable const & sender, const Windows::UI::Xaml::RoutedEventArgs & args) 
apparently successfully. But if I do that I am told that "IInspectable is not a member of winrt::Windows". Has something changed? Your ButtonClick using a Lambda compiles fine if it's in the App struct. But it cannot be in a different class - even with all the same namespaces and includes. Must admit I am stumped. Without the ability to use xaml markup, how can I assign click methods to buttons declared in classes outside the app struct? Do additional classes (e.g. something like MyMainPage) need to derive from some base class? On the Mac OS they could derive from NSObject, for example.

**Comment by DefaultRyan** [comment]
IInspectable (and IUnknown) moved from winrt::Windows to winrt::Windows::Foundation last spring.

**Comment by jevansAN** [comment]
Ryan: Thanks. Exactly the information I needed.

**Comment by jevansAN** [comment]
Want to thank you guys for the answers - making good progress now and it's a pleasure to be doing it in straight-up C++.

**Comment by jevansAN** [comment]
Here's a question, though. As I am creating the UI elements without xaml, it's a little tricky to create a Button that displays an image. I know I need to create a bitmap image with a Uri source. The following builds without error, but crashes at the call to create a Uri. Perhaps the argument to the Uri constructor is wrong, but the compiler doesn't seem to notice:

BitmapImage buttonImage = BitmapImage();
Uri imageUri = Uri(L"Assets/Images/stopbutton.png"); //crashes in this
buttonImage.UriSource(imageUri);

? Thanks.

**Comment by kennykerr** [comment]
The `Uri` constructor likely throws an exception because that's an invalid URI format. The MSDN docs should explain the permitted URI format.

**Comment by YohDeadfall** [comment]
It isn't a compiler related issue. Check [docs](https://docs.microsoft.com/en-us/windows/uwp/app-resources/uri-schemes). As you can see, you have lost slash before Assets.

**Comment by jevansAN** [comment]
Did try putting a slash before assets, but it appears this must be an absolute file url, like file:C:Users/ etc. This way it runs without crashing but does not actually load the image. I get a generic image instead. Perhaps the fault lies in the way I'm assigning the image:
buttonImage.UriSource(imageUri);
Button button = Button();
button.Content(buttonImage);

**Comment by jevansAN** [comment]
Elsewhere I find that Uri(L"ms-appx:///Assets/Images/stopbutton.png") ought to work as a relative path, but this also fails to load the specified image.

**Comment by tim-weis** [comment]
@jevansAN: This issue is about the availability of the *modern.exe* (now *cppwinrt.exe*) compiler. Your questions are unrelated in that context. You may want to try another resource to get those sorted out, like [Stack Overflow](https://stackoverflow.com/).

**Comment by jevansAN** [comment]
Sorry, Tim. I was getting such good answers from Kenny and DefaultRyan that I was tempted to just go ahead and ask. I'm pessimistic about getting a cppwinrtp answer on stackoverflow.

**Comment by tim-weis** [comment]
Give it a try. The [c++-winrt](https://stackoverflow.com/tags/c%2b%2b-winrt/info) tag has been around for well over a year. Kenny Kerr as well as Brent Rector have been active in that community as well. It's just an overall better place for these types of questions.

**Comment by jevansAN** [comment]
Just gave that a try, we'll see. I've love to write the documentation for this, if I didn't already have a job.

**Comment by jevansAN** [comment]
OK, sorry, I'm going to come back with a remark off-topic. I asked at StackOverflow if tiling an ImageBrush was going to be supported in cppwinrt, as it seems so far as I can tell not to be supported at present, and Ken White closed the question as off-topic since it refers to future plans. Perhaps there is another way to contact Kenny K with a question of this type, but I don't know what that could be. Is there a way to draw a tiled background in winrt?

**Comment by jevansAN** [comment]
To finish this: I found the cppwinrt issues forum at GitHub, which is better than StackOverflow for this topic, and Kenny K has explained it, I think. Appears the tiling feature was never included in winrt so it's not accessible in cppwinrt. Starting to make sense to me now... I'll leave you alone.
