### ISSUE TITLE
Is there a way to use CppCoreCheck with the interop sample?

### ISSUE THREAD

**Issue by Holo-Krzysztof** [Microsoft/cppwinrt#345]
I'm thinking about reducing my dependency from C++/CX to a minimum so that I can use standard C++; however, I can't ditch it completely because the [Holographic Remoting](https://www.nuget.org/packages/Microsoft.Holographic.Remoting/) library's API uses it (HolographicStreamerHelpers is a non-public ref class).

One of the benefits of migrating to cppwinrt would be the ability to use CppCoreCheck, which is disabled for CX projects (compiled with /ZW). However, I still need that flag to be able to use the remoting library (at least in the files that interact with it).

I tried compiling the Interop project without /ZW while enabling that flag for Main.cpp and pch.cpp, however, when attempting to do code analysis it gives me this error message: `C1093 API call 'ImportFile' failed '0x80070002': ErrorMessage: The system cannot find the file specified.`

The question is: is there any way to have code analysis in a "hybrid" project? Is it even a good idea? (Building pch.cpp with CX gives me a feeling that it might break things in a subtle way, but I don't know for sure).

**Comment by dfields-msft** [comment]
Thanks for your feedback on Holographic Remoting, we're considering how we could make this more compatible with C++/WinRT.

For your immediate concern, perhaps you could create a C++/CX WinRT component which wraps the parts of HolographicStreamerHelpers that you use with a `public` interface so that you can use CppCoreCheck on your non-CX project? I can't speak to whether a "hybrid" configuration is otherwise possible.

**Comment by Scottj1s** [comment]
archive status
