### ISSUE TITLE
Improve cancellation support

### ISSUE THREAD

**Issue by AlexBAV** [Microsoft/cppwinrt#35]
I think that improved cancellation support is needed for the async/await compatible classes this library provides (like `IAsyncAction` and others, or `resumable_io` and others.)

Right now, we may have the following "task":

```
class Some
{
  IAsyncAction keep_alive_task;

  IAsyncAction keep_alive()
  {
    auto cancelled = co_await get_cancellation_token;
    while (!cancelled())
    {
      co_await 10min;
      // do some work
    }
  }
public:
  Some()
  {
    keep_alive_task = keep_alive();
  }

  ~Some()
  {
    keep_alive_task.Cancel();
    try {
      keep_alive_task.get();  // will block for as much as 10 minutes
    } catch(...) {}
  }
};
```

Currently, we have no way of cancelling that pending timer and will have to wait in `Some::~Some` until it fires.

While it is possible to create a version of cancellable timer (which I successfully did in my project), this all does not compose well. That is, there is no "connection" between outer cancellation and inner cancellation.

It would be nice to incorporate some solid cancellation support, for example, like in Concurrency Runtime with its cancellation sources, its tokens and subscriptions.

Are there any thoughts or future plans on improving cancellation support?

**Comment by kennykerr** [comment]
Yes, we plan to support deeper cancellation support particularly for things like I/O cancellation where a ReadFile or equivalent may be blocked indefinitely.

**Comment by AlexBAV** [comment]
Are you talking about modified `resumable_io` class with cancellation support (which I also created for my project), or about a way to associate outer cancellation with an inner one, possibly several levels deep? Like in my example, when I call `IAsyncAction::Cancel` on `keep_alive_task`, inner timer (or I/O in your example) are automatically cancelled?

**Comment by kennykerr** [comment]
There are two different modes or issues related to cancellation. The first is the cancellation of nested awaitable WinRT types for which we must work within the bounds of the cancellation statement machine through the ABI. The second is the cancellation of objects scheduled to the thread pool. Each of the thread pool objects support cancellation to varying degrees and I/O presents specific challenges since the I/O operation itself needs to be canceled along with the thread pool object that is waiting for its completion. The two need to be coordinated to avoid a leak.

**Comment by AlexBAV** [comment]
Yeah, I understand. It's wonderful that this is being addressed. Keep up a good work!
