### ISSUE TITLE
Add msbuild support for non-store component projects

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/cppwinrt#398]
Currently, the targets file relies on VS detection of project winmd outputs (via ResolveAssemblyReferences).  But this only supports "store" component projects, whether packaged or activated via Reg-free WinRT and the VCRT forwarders nuget.   To support test scenarios, and possible future platform enhancements, non-store projects should also be supported.

**Comment by kennykerr** [comment]
We really need this...

**Comment by axodox** [comment]
I am not sure if I understand correctly. But on our project we use non-store WinRT component libraries with docker + registration free manifests and also with appx + the desktop bridge. I just use the non-store C++ WinRT console template, change it to compile to DLL, add my IDL file, and module.def with 
`EXPORTS
DllCanUnloadNow = WINRT_CanUnloadNow                    PRIVATE
DllGetActivationFactory = WINRT_GetActivationFactory    PRIVATE`. And use it in other C++/WinRT and .Net Framework projects. Where I use the components, I add a manifest describing their names and the DLLs. It works well.

**Comment by Scottj1s** [comment]
@axodox, does your scheme allow a project to reference your non store component project, find it's winmd, and automatically generate projection headers?  That's what this issue addresses.

**Comment by Scottj1s** [comment]
@axodox, does your scheme allow a project to reference your non store component project, find it's winmd, and automatically generate projection headers?  That's what this issue addresses.

**Comment by axodox** [comment]
Ok I understand now. And no, it does not, I add a reference to the winmd by hand. At least it seems that it causes the dll to be copied to the other projects output folder, as long its name is the same as the winmd. But I still have to add the project as build dependency manually.

**Comment by sylveon** [comment]
In my case I'm trying to write XAML for a XAML Islands project, and when compiling the projection files are correctly generated for the main non-XAML C++ project, because the project with XAML is effectively just a UWP DLL but linking to the desktop CRT via an undocumented attribute in the project file. Dependencies aren't picked up, all NuGet dependencies which I use in the project that contains XAML must also be installed in the main executable project (which doesn't have any XAML code) otherwise the generation of the projection header fails because it can't find types from my dependencies.

Shouldn't have to use that undocumented attribute to get XAML working, and dependencies in such a manner should also be working.

**Comment by axodox** [comment]
We do not XAML on our project, it is WinRT is used to interoperate between C# and C++ code in a service, which runs as a desktop app in docker.

**Comment by axodox** [comment]
Sorry, my statement was not entirely correct, it generates the headers for C++, but I have to reference the dll to make it copied in the output.

**Comment by kennykerr** [comment]
We are not actively investing further in our msbuild support. If there is a workaround or fix available, please feel free to contribute.

**Comment by sylveon** [comment]
Is it not possible to get the msbuild team to fix the core issue? (ResolveAssemblyReferences finding WinMD only in store project types)

**Comment by kennykerr** [comment]
I can't speak for that team, but my impression is that they have no plans to improve support for native code. Hopefully that changes at some point.
