### ISSUE TITLE
auto_revoke support for winrt::event<> events

### ISSUE THREAD

**Issue by Mathos1432** [microsoft/cppwinrt#417]
Consider the following class:
```cpp
class Foo 
{
    winrt::event_token MockEvent(const winrt::delegate<> handler) { return m_mockEvent.add(handler); };
    void MockEvent(const winrt::event_token& token) { m_mockEvent.remove(token); }

    winrt::event<winrt::delegate<>> m_mockEvent;
}
```
It would be good if we had support for automatically revoking these events (using winrt::auto_revoke for example). Ideally we can simply add an extra method which takes in winrt::auto_revoke_t and returns an auto_revoke token, but it seems like this isn't supported for non projection types. 
```cpp
winrt::auto_revoke<Foo> MockEvent(const winrt::auto_revoke_t, const winrt::delegate<> handler)
{
... 
}
```
To work around the problem we've created our own copy of the event_revoker struct, but it feels like something we should consider supporting 😊.

**Comment by kennykerr** [comment]
The problem is with the lifetime of the event source - the "Foo" in your example. An event revoker should consider whether the revoker outlives the event source (instance). WinRT supports this via weak references, but for other types you're on your own to figure out how to achieve this (typically with a shared_ptr). The C++/WinRT library is only concerned with WinRT types. You can naturally define your own revoker (in some other namespace) that supports non-WinRT types.

**Comment by Mathos1432** [comment]
That makes sense to me. I was asked to bring up the issue here since we had to deal with it.
