### ISSUE TITLE
Question: get_activation_factory() and caching of non-agile factories

### ISSUE THREAD

**Issue by jonitis** [Microsoft/cppwinrt#45]
Hello,

Is it by design that for agile objects the activation factory is cached into static variable
``` c++
    static Interface factory = impl::get_agile_activation_factory<Class, Interface>();
```
but for non-agile objects get_activation_factory() always calls RoGetActivationFactory()?
``` c++
    if (!factory)
    {
        return impl::get_activation_factory<Class, Interface>();
    }
```
I've made small test program that calls get_activation_factory() from main thread and from worker thread. I get the same values. 
``` c++
#include "stdafx.h"

using namespace winrt;
using namespace Windows::Networking;
using namespace Windows::Networking::Connectivity;

using namespace Windows::Security;
using namespace Windows::Security::Credentials;
using namespace Windows::Security::Credentials::UI;

void OtherThread()
{
	initialize();

	const auto& ni1 = get_activation_factory<NetworkInformation, INetworkInformationStatics>();
	printf("WT: ni1 = %p\n", get(ni1));

	const auto& ni2 = get_activation_factory<NetworkInformation, INetworkInformationStatics>();
	printf("WT: ni2 = %p\n", get(ni2));

	const auto& cpo1 = get_activation_factory<CredentialPickerOptions>();
	printf("WT: cpo1 = %p\n", get(cpo1));

	const auto& cpo2 = get_activation_factory<CredentialPickerOptions>();
	printf("WT: cpo2 = %p\n", get(cpo2));

	uninitialize();
}

int main()
{
	initialize();

	std::thread t1(OtherThread);

	t1.join();

	const auto& ni1 = get_activation_factory<NetworkInformation, INetworkInformationStatics>();
	printf("MT: ni1 = %p\n", get(ni1));

	const auto& ni2 = get_activation_factory<NetworkInformation, INetworkInformationStatics>();
	printf("MT: ni2 = %p\n", get(ni2));

	const auto& cpo1 = get_activation_factory<CredentialPickerOptions>();
	printf("MT: cpo1 = %p\n", get(cpo1));

	const auto& cpo2 = get_activation_factory<CredentialPickerOptions>();
	printf("MT: cpo2 = %p\n", get(cpo2));

	uninitialize();

	return 0;
}
```
Output:
```
WT: ni1 = 000002036D511850
WT: ni2 = 000002036D511850
WT: cpo1 = 000002036D511BC0
WT: cpo2 = 000002036D511BC0
MT: ni1 = 000002036D511850
MT: ni2 = 000002036D511850
MT: cpo1 = 000002036D511BC0
MT: cpo2 = 000002036D511BC0
```

Can't you also cache the activation factory for non-agile objects? Something like this:
``` c++
    if (!factory)
    {
        factory = impl::get_activation_factory<Class, Interface>();  // do not return value, but assign to cache
    }

    return factory;
```
Or I've picked bad sample classes and getting same factory instances from different threads does not prove anything?

Thanks in advance!

**Comment by kennykerr** [comment]
Yes, this is by design. Activation factories should be agile, but sadly some are not. Caching agile activation factories is safe since the cached pointer may be used by any thread from any apartment. Non-agile activation factories may only be used by threads from the same apartment and the overhead of managing a per-apartment cache is prohibitive. Non-agile activation factories are also the source of a variety of bugs. We are moving to a world where all activation factories will be agile. This is the most reliable and efficient model, but we need this fallback in C++/WinRT to deal with existing non-agile factories. For more about agility [please read this overview](https://kennykerr.ca/2016/11/11/cppwinrt-fun-with-agility/).

**Comment by jonitis** [comment]
Thank you very much for clarification.
