### ISSUE TITLE
Support MSVC new preprocessor

### ISSUE THREAD

**Issue by NN---** [microsoft/cppwinrt#457]
Macros are defined in a non standard way.
https://devblogs.microsoft.com/cppblog/msvc-preprocessor-progress-towards-conformance

Fixed versions 

```cpp
#define VA_STRINGIZE(...) DETAIL_VA_STRINGIZE(__VA_ARGS__)
#define DETAILVA_STRINGIZE(...) #__VA_ARGS__



#include <winrt/base.h>

#define WINRT_WRAP(...) (__VA_ARGS__)

#define WINRT_ASSERT_DECLARATION(M, R, ...) WINRT_ASSERT_DECLARATION_(M, R, ##__VA_ARGS__)

#define WINRT_ASSERT_DECLARATION_(M, R, ...) \
{ \
    auto invocation = [](auto&& d, auto&&... params) -> decltype(R d.M(params...)) {}; \
    static_assert(winrt::impl::is_detected_v<winrt::impl::invoker_t, decltype(invocation), D, ##__VA_ARGS__>, \
        "\n\n\tC++/WinRT: Could not find method in implementation class:\n\t\t" #R " " #M "(" VA_STRINGIZE(__VA_ARGS__) ");\n"); \
}
```

**Comment by kennykerr** [comment]
Those macros no longer exist. Please upgrade to a newer version of C++/WinRT.

**Comment by NN---** [comment]
We use the version from SDK.
Is it expected to not use it and consume the headers from this repository directly ?

**Comment by kennykerr** [comment]
The version in the SDK is quite old. Builds from the repo are published here:

https://www.nuget.org/packages/Microsoft.Windows.CppWinRT/

If you use Visual Studio, you can simply add a NuGet package reference. This will replace the SDK headers in your include path. Otherwise, you can unzip the NuGet and run cppwinrt.exe to generate headers directly.

**Comment by NN---** [comment]
I added the nuget but I don't see any header.
