### ISSUE TITLE
winrt::guid does not implement operator<

### ISSUE THREAD

**Issue by dfields-msft** [microsoft/cppwinrt#463]
The omission of `operator<` on `winrt::guid` means that it can't be used as a key for `std::map`. While in many cases `std::unordered_map` may be sufficient, it should still be possible to create ordered maps keyed by `winrt::guid`.

**Comment by dfields-msft** [comment]
@oldnewthing pointed out that there are actually a variety of orderings which have been implemented for GUIDs; see:
https://devblogs.microsoft.com/oldnewthing/20190426-00/?p=102450 https://devblogs.microsoft.com/oldnewthing/20190913-00/?p=102859

For the purposes of this issue, I would lean towards either `memcmp` since it's trivial to implement and describe, or the `Platform::Guid` convention (treat as four 32-byte integers) for the benefit of codebases which may be migrating from C++/CX to CppWinRT.

@oldnewthing you mentioned that the `Platform::Guid` ordering was done that way for performance reasons; can you elaborate?

**Comment by kennykerr** [comment]
It used to be the case that comparing GUIDs as 4 integers was more efficient (either faster or producing less code I forget) but the C++ optimizer team assures me that using the `memcmp` intrinsic will now produce optimal code gen in all cases. That's why `winrt::guid` uses `memcmp` for its `operator==`.
