### ISSUE TITLE
Generate the headers so they can be pull from other projects

### ISSUE THREAD

**Issue by robUx4** [microsoft/cppwinrt#490]
For projects not using Visual Studio and the Windows SDK it's tricky to get the headers, especially when cross compiling (from Linux to Windows for example).
It would nice to have a repository with the headers readily available.

It would technically be possible to generate them using GitHub actions which can run code in [Windows Server 2019](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners#windows-server-2019). It would generate the headers as an artifact that can be loaded by other softwares (easiest way). Or it could upload the build result (when master changes for example) to another repo.

**Comment by kennykerr** [comment]
It's tricky because they're not just headers generated by `cppwinrt.exe` - they're headers generated for a specific set of input `.winmd` files. Those `.winmd` files describe a certain set of APIs you want to project into a given language. You typically need to pick a specific Windows SDK and harvest up the `.winmd` files from that version. But the build server may not always have the latest version or the specific APIs you're looking for and it becomes a much bigger challenge to manage in a general sense.

The simplest thing, if you're not using Visual Studio, is to call `cppwinrt.exe` yourself to generate the headers. You can then check those headers into your own repo, if so desired, and update them whenever you want to gain access to newer APIs or pick up fixes from a newer version of `cppwinrt.exe`. 

Running `cppwinrt.exe` is quite simple. The `.nupkg` files on the [releases page](https://github.com/microsoft/cppwinrt/releases) is just a zip file that contains the cppwinrt binary.
