### ISSUE TITLE
Question: c++ constness of value types

### ISSUE THREAD

**Issue by jonitis** [Microsoft/cppwinrt#50]
From provided samples it seems that you always prefer plain types without const modifier. By old habit I assigned the return value to const references and was confused that for const object I can still call property setters and modify delegates, since all these methods have const modifier, although they clearly modify the object. Would it have any benefits to remove the const modifier from property setters and delegate registration code? I understand that all code is auto-generated from metadata and CLI spec has read/write attributes only for properties. Modern compiler would not be able to know whether arbitrary function modifies the object or not. But at least for properties we can protect against modifying an object. It may give some sense of safety when passing const reference to a class instance as a function argument. Or we just have to forget about c++ constness because WinRT (like .NET) does not support it, because of support for other languages? What would be the best practice regarding const?

Other slightly related question is how to assign result that is returned by winrt function. Whether to assign it to variable of value type X or reference to X?

auto devices = co_await DeviceInformation::FindAllAsync(allReadersSelector);
  vs.
auto& devices = co_await DeviceInformation::FindAllAsync(allReadersSelector);

Does both variants have same number of AddRef() calls and there is no real benefit in using reference to value type (which itself is just a wrapped interface pointer)?

Thanks in advance!

**Comment by tim-weis** [comment]
`auto& devices = co_await DeviceInformation::FindAllAsync(allReadersSelector);` binds a reference to a temporary (the return value). That's undefined behavior. You cannot do this.

**Comment by jonitis** [comment]
>I assigned the return value to const references
sorry, it was const reference. Removed too much while preparing question :(

**Comment by kennykerr** [comment]
The const of C++ has no effect on WinRT mutability. The const is used to protect and clarify that the pointer held by the C++ object is not modified, but does not make any assertion that the WinRT object being pointed to will not be modified. A WinRT property getter might well modify the object. There are a few places in the projection where const is used as an optimization, in particular for input parameters. I’ll write more about this soon, but in short you should pass (synchronous input) objects by const & and return by value. You don’t save anything by returning to a const & since all WinRT return values will produce ref-counted values.

**Comment by jonitis** [comment]
Thank you very much for taking your time and clarifying those things in your blog posts.
