### ISSUE TITLE
Create an MSBuild SDK for cpp/winrt

### ISSUE THREAD

**Issue by stevenbrix** [microsoft/cppwinrt#519]
[MSBuild SDK's](https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk?view=vs-2019) are the bees knees. I'm not sure if there will be any equivalent work done for C++ projects like there is with .NET projects. It would be fantastic to have one for projects using Cpp/WinRT that removes a lot of the boilerplate MSBuild project file goo that is required

An example cpp/winrt UWP app .vcxproj:
```xml
<Project Sdk="Microsoft.Windows.CppWinRT">
   <PropertyGroup>
     <OutputType>AppContainerExe</OutputType>
     <TargetPlatformVersion>10.0.18632.0</TargetPlatformVersion>
     <TargetPlatformMinVersion>10.0.17134.0</TargetPlatformMinVersion>
   </PropertyGroup>
</Project>
```

An example cpp/winrt Win32 Desktop app .vcxproj:
```xml
<Project Sdk="Microsoft.Windows.CppWinRT">
   <PropertyGroup>
     <OutputType>WinExe</OutputType>
     <TargetPlatformVersion>10.0.18632.0</TargetPlatformVersion>
     <TargetPlatformMinVersion>10.0.17134.0</TargetPlatformMinVersion>
   </PropertyGroup>
</Project>
```

An example cpp/winrt library .vcxproj:
```xml
<Project Sdk="Microsoft.Windows.CppWinRT">
   <PropertyGroup>
     <OutputType>library</OutputType>
     <TargetPlatformVersion>10.0.18632.0</TargetPlatformVersion>
     <TargetPlatformMinVersion>10.0.17134.0</TargetPlatformMinVersion>
   </PropertyGroup>
</Project>
```

**Comment by kennykerr** [comment]
Thank Steven, that sounds neat. If you'd like to experiment and work on something like that for C++/WinRT that would be interesting, but I doubt we'll be able to find the time. Ideally, the Visual C++ team would consider such an approach. The C++ project system really needs some love.

**Comment by jlaanstra** [comment]
SDK based projects heavily rely on the project system to support it (globbing etc). None of this is supported by the C++ project system as far as I know. @AugP is this something that is on the roadmap?

**Comment by stevenbrix** [comment]
That doesn’t surprise me, although I wouldn’t think MSBuild would care? Or is it VS support that wouldn’t work?

I would be happy if it was everything sans globbing for ClCompile items

**Comment by wjk** [comment]
In my experience, MSBuild SDKs (`<Project Sdk="">`) and the C++ project system are totally orthogonal to each other. Neither knows nor cares about the other's existence. The C++ project system will preserve SDK elements in the project file just fine. I could certainly throw a PR together; in fact, I've been thinking about doing this for some time now.

However, that being said, we'll need to think about how to handle the project and item templates. If I were to build an SDK for CppWinRT, I would want to integrate the contents of the NuGet package into it, so I can get rid of `packages.config`. (I much prefer PackageReference, but the C++ project system NuGet support isn't compatible with that.) However, when I would then create an item using one of the CppWinRT project templates, VS would automatically add a reference to the NuGet package, and there is no way to stop or conditionalize this that I know of without breaking use of the templates in projects that do need to reference the NuGet package. Any pointers on how to tackle this problem would be greatly appreciated. Thanks!

**Comment by stevenbrix** [comment]
@wjk glad you joined the conversation here :)

Have you seen: https://github.com/microsoft/MSBuildSdks/tree/master/src/CentralPackageVersions#centralpackageversions-and-vcxproj-files? It seems to imply that `PackagReference` can work for `.vcxproj`, however the UI in VisualStudio just doesn't work, so you have to update `PackageReference`'s manually.

The auto-nuget reference comes from the cpp/winrt project templates. If the cpp/winrt project templates were to instead use an MSBuild SDK, they could probably avoid doing this.

**Comment by wjk** [comment]
What you say is correct; however, the item templates also contain an auto-nuget reference, and they are the problem, not the project templates.

**Comment by stevenbrix** [comment]
Ahh yeah I see, thanks for clarifying.

It would be awesome if you could put something together, although I'd wait and see what @augp says. If the Visual C++ team is creating an MSBuild SDK then it might not make a whole lot of sense, and this issue could be changed to "Have cpp/winrt use MSBuild SDK". Last I knew they weren't investing much in this space, and were focusing on other things like cmake and vcpkg

**Comment by kennykerr** [comment]
The best way to reach the Visual C++ team is to create an issue here:

https://developercommunity.visualstudio.com/spaces/62/index.html

**Comment by wjk** [comment]
@kennykerr Unfortunately, developers like myself have been creating issues like this one on the C++ Developer Community space for some time now, to no avail. The Visual Studio team does not seem to be placing any more resources into developing vcxproj; the general consensus is to use CMake instead.

The problem is, you cannot use CMake to develop a UWP/WinUI project, because the tasks required to compile XAML files for use at runtime are only exposed as MSBuild tasks that require vcxproj. ([More details can be found here.](https://github.com/microsoft/microsoft-ui-xaml/issues/1433)) CMake cannot be used to compile a C++/CLI project either, because the package resolution mechanism also requires vcxproj; nor does CMake integrate easily with a managed application built using a csproj file. ([This PR](https://github.com/dotnet/arcade/pull/4533) aims to solve that last issue, but it has stalled.)

Since it is clear that the Visual C++ team is not going to work on this ticket, could you please consider reopening it so the community can make an attempt at solving this? Thanks so much!

**Comment by kennykerr** [comment]
Hi William, you don't have to convince me of the state of C++ project support in Visual Studio. 😉 

If someone from the community would like to build a solution I'm all for it. I'm just closing this issue as the issues page here is primarily for active cppwinrt bugs or discussing features that someone is actually working on. Anyone can reopen this issue if and when there is some active progress. I just don't want the issues page to turn into into a wish list in hopes that "someone" will do the work, because practically speaking it usually comes down to me and I simply don't have the bandwidth for this. 

Feel free to keep the conversation going here if that is practical.

**Comment by stevenbrix** [comment]
@wjk is it just the xaml compilation task that is holding cmake back from being a reasonable solution for building cpp/winrt applications?

@kennykerr, @Scottj1s I had heard that you had attempted cmake at one point, but decided to go with MSBuild. What was the reason for that?

**Comment by wjk** [comment]
@stevenbrix XAML compilation, generation of the code-behind files that are a byproduct of that process, and packing those files into a PRI file are the three big tasks that currently require vcxproj. MSIX packing is easy to automate from CMake, so we don't need to worry about that. Thanks!

**Comment by stevenbrix** [comment]
@wjk I'm pretty sure pri creation is available as an exe (makepri.exe). Is there other stuff that is msbuild specific that would need to be done to make that work in cmake?

**Comment by wjk** [comment]
@stevenbrix Yes, makepri.exe does exist, but figuring out what the correct parameters to pass to it is nontrivial. The MSBuild targets (which I would prefer to use as reference) are very convoluted. Meanwhile, the docs do not explain very well how to integrate makepri.exe into a CMake-based build process, in a way that would get it to actually work. (In my experience, if you make a mistake building your PRI file, makepri.exe will succeed without error, but the app would crash somewhere during runtime.) Thanks!

**Comment by Scottj1s** [comment]
@stevenbrix - in answer, the cppwinrt nuget was created long before anyone mentioned using cmake for consuming winrt components.  so the question then becomes, "should we duplicate the cppwinrt nuget msbuild customizations for cmake?"   given the deep and complex stack of msbuild support for C++ projects, upon which the cppwinrt nuget msbuild suppport depends, and which is itself non-trivial, I seriously question the value of that.  cppwinrt is a Windows-specific technology, so it makes little sense to invest in a cross-platform invocation of it.
