### ISSUE TITLE
Question: is there a canonical way to polymorphically cast in/out of IInspectable

### ISSUE THREAD

**Issue by rhenninger** [Microsoft/cppwinrt#52]
Using a platform object like IPropertySet (eg project settings) which polymorphically stores/gets Platform::Objects (now IInspectable), what is the recommended way to store and retrieve its values using cppwinrt?   

Reading docs and examples I managed "settings.Lookup(L"CurrentProjectUri").as<IStringable>().ToString()" for retrieval, but storing a string or hstring via settings.Insert is not working: I can't figure out a reasonable dynamic_cast and as/try_as is not found on hstring.  What syntax do you recommend?

**Comment by rhenninger** [comment]
I found #39 and got a working combination by using IPropertyValue rather than IStringable.

	settings.Insert(L"CurrentProjectUri", PropertyValue::CreateString(m_currentProjectUri));

	std::wstring xx = settings.Lookup(L"CurrentProjectUri").as<IPropertyValue>().GetString();

**Comment by rhenninger** [comment]
While the solution in #39 solves the immediate program issue I had with application settings and property sets, I am still interested in the more general question I raised about a canonical syntax for polymorphic up and down casting of hstring into IInspectable.  Any thoughts?

**Comment by KevinWelton** [comment]
The casting problem for hstring to IInspectable is rooted in the fact that hstring a wrapper class for HSTRING, and does not derive in any way from IInspectable. So casting of hstring to IInspectable isn't possible.

In the case of PropertySet::Insert(), although the value parameter is declared as IInspectable, it will only accept IPropertyValue-based objects. Anything else will throw a winrt::hresult_invalid_argument exception. With the IPropertyValue requirement in mind, you end up with the code you pasted above.

**Comment by BrentRector** [comment]
To add to Kevin's reply, in the WinRT type system, an HSTRING has no type system relationship to an IInspectable. The C++/WinRT language projection simply models that.

In WinRT, if you need to wrap an HSTRING in an IInspectable, you do so by calling the static PropertyValue::CreateString method. So you do the same in C++/WinRT.

**Comment by rhenninger** [comment]
Thanks.  After all these years with winrt, I never realized that Platform::String^ didn't inherit from Platform::Object^.  C# assumptions that mask C++/CX reality.  Live and learn.  Thanks for the clear explanation.

**Comment by BrentRector** [comment]
To be even more explicit (or pedantic if you prefer) :), WinRT != C++/CX.

In the C++/CX language projection, the team decided:
* Platform::String is the CX language projection of the WinRT HSTRING type.
* Platform::Object is the CX language projection of the WinRT IInspectable type.
* Platform::String would derive from Platform::Object (mostly I think because CX models a lot after .NET).

But that CX type system relationship between those two CX types does not exist in the original Windows Runtime type system.

At a high level, it's similar to how there is no Windows.Foundation.Uri WinRT type in the .NET projection of WinRT. The .NET projection maps this WinRT type to the .NET System.Uri type. Each language projects a WinRT type to the most appropriate equivalent type in that language.

**Comment by rhenninger** [comment]
@BrentRector Thanks.  I appreciate the in depth explanation.  I have a clearer understanding of the differences now.
