### ISSUE TITLE
"Blank Page" Item Template difficult to integrate, no documentation

### ISSUE THREAD

**Issue by daviddetweiler** [microsoft/cppwinrt#581]
I recently wanted to add a blank xaml page to a C++/WinRT Blank App project.
How I expected it would work: like adding a new IDL file to a C++/WinRT component project, I add the blank page, then I add the IDL for the code-behind class, then I copy the generated files into the project, remove the generated `static_assert`s, and compile. If I do all of these, compilation fails, the error being `XamlTypeInfo.g.cpp` having code that refers to the code-behind class, but does not include the header for it. If I include the BlankPage header in `pch.h` as a work-around, I instead get linker errors for BlankPage not implementing methods such as `Connect`, which I presume are part of how Xaml wires up the code-behind internally.

It's concerning that something as basic as adding another page is apparently broken

**Comment by Scottj1s** [comment]
This appears to be two issues.  The first, regarding XamlTypeInfo.g.cpp not including the headers of unreferenced classes, I thought had been fixed.  I'll follow up with the Xaml team in that.  The second, regarding missing implementation files, is what Kenny is referring to.  That was a regression in Visual Studio 16.5 and will be fixed in VS 16.6 preview 3.  Here's the issue for tracking:
https://developercommunity.visualstudio.com/content/problem/959456/item-template-dependent-nesting-behavior-broken-in.html
