### ISSUE TITLE
database::get_string doesn't handle some utf-8 characters correctly

### ISSUE THREAD

**Issue by kennykerr** [microsoft/cppwinrt#618]
A TypeDef with a name of `ITouché` is returned as `ITouchÃ©`. In other places the string is returned correctly. It seems we need a bit of work before we can really support Unicode type names in C++/WinRT as the underlying winmd parser doesn't deal with utf-8 correctly.

**Comment by DefaultRyan** [comment]
This isn't a problem with cppwinrt or the winmd reader. They appear to be working fine (but the VC++ debug visualizer is probably misinterpreting those strings as ASCII instead of UTF-8, leading to the weirdness.

We are getting broken by midlrt. Creating a runtimeclass named `Touché` and running it through midlrt, and cracking open the winmd in ILDASM confirms it. The string heap has the correct names. The `ITouché` interface has an ExclusiveTo attribute that is suppsosed to have the target runtimeclass's name (`Touché`) in it, but that name has been misencoded - the last character is represented as a single byte, E9, instead of the two UTF-8 bytes (C3 A9) that should be there.

The `é` character is Unicode code point U+00E9. Apparently, when midlrt wrote the attribute, it probably assumed its UTF-16 input was entirely in the range of 0 to 0x7f and casted the `wchar_t` into `char`. There's the unlikely chance it actually bothered to call `WideCharToMultiByte` but supplied the wrong code page, but my money is on the first hypothesis.

**Comment by kennykerr** [comment]
Thanks for digging in, Ryan. I was hoping to add some Unicode tests, but we can pick this up again once we have a more reliable way to produce winmd files. 😉
