### ISSUE TITLE
cppwinrt : error Could not find the Windows SDK

### ISSUE THREAD

**Issue by BeErikk** [microsoft/cppwinrt#619]
I followed the advise building a release `cppwinrt.exe` and then run `build_projection.cmd`. A debug build then fails with the message:
`fatal error C1083: Cannot open include file: 'winrt/Component.h': No such file or directory`
and in x64 debug Component.log:
```
C++/WinRT compiler 
cppwinrt : error Could not find the Windows SDK
```
[Component.log](https://github.com/microsoft/cppwinrt/files/4620226/Component.log)

**Comment by kennykerr** [comment]
It is simpler to start with using pre-built version of cppwinrt that you can find here:

https://aka.ms/cppwinrt/nuget

You can also get project templates here:

https://aka.ms/cppwinrt/vsix

Building from the repo is only intended for developers working on C++/WinRT itself and is otherwise not supported since it is rather complicated to get working.

**Comment by BeErikk** [comment]
OK thanks, I just wanted to understand rather than use.
