### ISSUE TITLE
Same Xaml App takes longer to compile in C++/WinRT than C++/CX

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/cppwinrt#660]
C++/WinRT takes way longer to compile an UWP app with same Xaml code than C++/CX. This makes development slower.

**Comment by MikeGitb** [comment]
Isn't that to be expected, given that the compiler has to churn through lots and lots of template machinery in C++/WinRT. Conversly, the produced code should be much more efficient and smaller (at least that was the result when I experimented with it the last time a couple of years ago).

I'm not assiociated with MS or this repository, but my guess is, that in order to make this actionable, you'd have to provide some concrete numbers (with the used build settings) and ideally benchmark code/project so that the maintainers are able to reproduce your problem and maybe give you some tips of how to speed up your compilation (are you e.g. using precompiled headers?).

**Comment by tim-weis** [comment]
@Jaiganeshkumaran Are you comparing full rebuilds or incremental builds?

**Comment by BenJKuhn** [comment]
Compilation performance for complex template libraries is a challenge in C++. In fact, it was one of the  key reasons that C++ /CX was written as a language extension back in ~2010. Although we always wish the performance could be better, it's significantly faster today than it was then. Early mockups also showed that projects could easily exhaust address space for 32-bit compilers with a template-based solution. Compiler perf was considered a potential ship-stopper for a library-based solution. 

The compiler has come a long ways since, with both performance and language improvements, and there are many advantages to building this in vanilla C++, rather than using opaque language extensions.

That said, we're always looking for ways to speed up build performance and we understand the value of doing so. There are developments in the C++ standard and compilers that we are about (e.g. C++ modules). If you have specific suggestions for how we can optimize our dependencies or templates within C++ WinRT for in-market tools, we would greatly welcome them. 

Please feel free to open specific issues for optimizations that you believe we could make.

Thanks,

Ben
