### ISSUE TITLE
no windows.ui.xaml.media.dxinterop.h?

### ISSUE THREAD

**Issue by gettf** [Microsoft/cppwinrt#67]
cant find ISwapChainPanelNative interface and windows.ui.xaml.media.dxinterop.h

**Comment by KevinWelton** [comment]
Since the types in windows.ui.xaml.media.dxinterop.h aren't WinRT types, you won't find a header for them in the C++/WinRT projection.

The good news is that you can include this header from the SDK include paths and still use the interface.

In order to get the ISwapChainPanelNative instance from a WinRT SwapChainPanel, you would do something like this:

```
#include <winrt/Windows.UI.Xaml.Controls.h>
#include <windows.ui.xaml.media.dxinterop.h>

using namespace winrt::Windows::UI::Xaml::Media::Controls; // For SwapChainPanel
...
SwapChainPanel panel;
com_ptr<ISwapChainPanelNative> native_panel = panel.as<ISwapChainPanelNative>();
```

**Comment by gettf** [comment]
thanks
