### ISSUE TITLE
Application.Current.Resources.TryLookup throws hresult_error despite it being a Try* method

### ISSUE THREAD

**Issue by asklar** [microsoft/cppwinrt#685]
In the cppwinrt generated header we have this in windows.foundation.collections.0.h, and we go down the first branch in the code, which will throw if the item is not found (in this case, XAML's ResourceDictionary returns `E_FAIL`):

```cpp
        auto TryLookup(param_type<K> const& key) const
        {
            if constexpr (std::is_base_of_v<Windows::Foundation::IUnknown, V>)
            {
                V result{ nullptr };
                impl::check_hresult_allow_bounds(WINRT_IMPL_SHIM(Windows::Foundation::Collections::IMap<K, V>)->Lookup(get_abi(key), put_abi(result)));
                return result;
            }
            else
            {
                std::optional<V> result;
                V value{ empty_value<V>() };

                if (0 == impl::check_hresult_allow_bounds(WINRT_IMPL_SHIM(Windows::Foundation::Collections::IMap<K, V>)->Lookup(get_abi(key), put_abi(value))))
                {
                    result = std::move(value);
                }

                return result;
            }
        }
```

**Comment by oldnewthing** [comment]
The `Try` means that it returns `null` if the key is missing. The contractual way to report a missing key is to return `E_BOUNDS`, but ResourceDictionary went its own way. Will accommodate the nonstandard behavior. See upcoming PR.

The `Try` does not mean "ignore all errors". Try will throw if the key could not be looked up at all, because returning `null` in those cases would be misleading. The key isn't missing. We couldn't even get to the point where we could check whether the key is present or not, e.g., because you are on the wrong thread, or because you don't have access, or the map is otherwise unavailable.
