### ISSUE TITLE
cancellation_token<TPromise> doesn't remove cancellation callback, requiring more defensive code

### ISSUE THREAD

**Issue by mschofie** [microsoft/cppwinrt#690]
I'm attempting to implement cancellation of IAsyncOperation using cppwinrt, wrapping a call into a C-style asynchronous API. I'm following the pattern that is documented on the ["Register a cancellation callback"](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/concurrency-2#register-a-cancellation-callback) section of the ["More advanced concurrency and asynchrony with C++/WinRT"](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/concurrency-2) documentation. The code I have to write *appears* to be more defensive than I would like - essentially forcing an extra allocation for cancellation - and I hoped to get some perspective and discussion on a change.

The snippet of code of interest is here;

```C++
IAsyncAction CancellationPropagatorAsync()
{
    auto cancellation_token{ co_await winrt::get_cancellation_token() };
    auto nested_coroutine{ NestedCoroutineAsync() };

    cancellation_token.callback([=]
    {
        nested_coroutine.Cancel();
    });

    co_await nested_coroutine;
}
```

When the callback is registered the passed in Lambda captures the `nested_coroutine` by-value. This appears to be necessary since the cancellation_token simply adds the callback to the `promise_base` - the cppwinrt implementation of the coroutine promise. The `promise_base` instance out-lives the variables in the coroutine frame, so any state that the cancellation callback needs must out-live the variables in the coroutine frame. Realistically, the state for the C-abi async operation isn't copyable, so it means the (in this case) `nested_coroutune` would have a shared heap allocation.

If the `cancellation_token` instance controlled the lifetime of the cancellation callback, then (with a little re-ordering of the code) a user would be able to capture the `nested_coroutine` by reference;

```C++
IAsyncAction CancellationPropagatorAsync()
{
    auto nested_coroutine{ NestedCoroutineAsync() };
    auto cancellation_token{ co_await winrt::get_cancellation_token() };
    cancellation_token.callback([&]
    {
        nested_coroutine.Cancel();
    });

    co_await nested_coroutine;
}
```

The coroutine would unwind the locals and the cancellation_token would be destroyed (and so the cancellation callback unregistered) before the `nested_coroutine` state is destroyed.

Is my understanding of the cancellation flow correct? Is it reasonable to ask for the cancellation_token to control the lifetime of the registered cancellation callback?

**Comment by dunhor** [comment]
There's a few things to unpack here. The first is the assertion that there's an extra heap allocation in your first example compared to the second. Given the lack of information in the examples you've pasted, it's impossible to evaluate the accuracy of that statement. If I work on the assumption that `nested_coroutine` is a WinRT type (e.g. an `IAsyncAction`), then your statement is false. The copy will make a single call to `AddRef` (and subsequent call to `Release` on destruction). If it's a different, custom type, then it'll depend on the implementation of the type's copy constructor, of course. Either way, it's not hard to imagine a scenario where capture-by-value would be undesirable.

As far as your understanding of the "gotchas" w.r.t capturing locals by reference in the cancellation callback, my reading suggests that you are correct. That said, your assertion that something can be done to invalidate the callback on function exit/cancellation token destruction appears false since _that's already effectively being done_. Here is the definition of `Cancel`:
```c++
        void Cancel() noexcept
        {
            winrt::delegate<> cancel;

            {
                slim_lock_guard const guard(m_lock);

                if (m_status == AsyncStatus::Started)
                {
                    m_status = AsyncStatus::Canceled;
                    m_exception = std::make_exception_ptr(hresult_canceled());
                    cancel = std::move(m_cancel);
                }
            }

            if (cancel)
            {
                cancel();
            }
        }
```
As you can see, the callback is ignored if the async object is not in the `Started` state. Or in other words, when `m_cancel` is read, execution of `CancellationPropagatorAsync` has not yet completed since otherwise, `return_void`/`unhandled_exception` would have been called and set the state to something other than `Started`. The issue arises because the callback is called outside of the lock - which is generally a good property; you don't want to make callouts while holding a lock - meaning that the guarantee that `CancellationPropagatorAsync` has not yet exited is no longer true, and therefore it is not safe to capture locals by reference in the callback. I'll defer to @kennykerr / @DefaultRyan on whether or not there's anything we want to re-think here. E.g. if we want to bite the bullet and say that it is okay to make the cancel callback while holding the lock under the assumption that callbacks are relatively trivial and don't touch the underlying `IAsync*`, which would result in deadlock. Doing so is a segue into opening a pretty big can of worms IMO.

**Comment by DefaultRyan** [comment]
If you ask me, I think @dunhor covered it pretty well.

I'm trying to figure out which "extra heap allocation" is being referred to, and none of the semi-plausible candidates are guilty:
- As Duncan already stated, copying a WinRT async object increments the reference count. **no extra allocation**
  - If your async operation is some other type, then I'd expect it to be designed for shared ownership and not involve heap allocation on copy. Anything else would be bad design.
- The capture lambda itself is not heap allocated, it's a simple member variable of the lambda object. **no extra allocation**
- The coroutine stack frame is heap allocated, but this would be true regardless of your suggestion. The heap allocation could only be elided if the coroutines lifetime was known to be a strict subset of the lifetime of the caller, which is not the case here, because async. **no extra allocation**
- The `delegate` field `m_cancel` does perform a heap allocation to store the callback. *Perhaps* there could be something done there, like using `std::function` instead of `winrt::delegate` and its "small function optimization", to elide allocation in some cases. Off the top of my head, I can't think of why the callback needs to be a `winrt::delegate`, but I could be missing/forgetting something subtle.

**Comment by dunhor** [comment]
One downside of `std::function` is that it requires the function object to be copy constructible. *Googles status of `move_only_function`, which is apparently actually named `unique_function`*

**Comment by mschofie** [comment]
Whilst writing this up, I came across #674, which makes things better since I can manually remove the cancellation callback before the coroutine ends. It certainly helps, but tying the lifetime of the callback to the token would be more clear. IMHO.

----

The documentation I linked to - [Register a cancellation callback](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/concurrency-2#register-a-cancellation-callback) - discusses how to register a cancellation callback to cancel 'other asynchronous objects'. The fact that it then goes on to demonstrate the cancellation using Windows Runtime asynchronous objects is confusing. Apologies if I wasn't clear.

As I said, I'm trying to cancel a C-style async call. I would like to store the state for the async call in the coroutine frame. I've pulled together an example the uses WriteFileEx with an OVERLAPPED struct to provide an example to discuss. It's [here](https://gist.github.com/mschofie/05435a7e4760a6a2885b17877adeeb87). It shows code that I would like to write, but can't due to the fact that the cancellation callback's lifetime is attached to the cppwinrt promise. The async method starts with;

```C++
IAsyncOperation<int> WriteFileAsync(HANDLE file, const std::string& message)
{
    OVERLAPPED overlapped{};
    overlapped.Offset = 0;
    overlapped.OffsetHigh = 0;

    auto cancellation_token{ co_await winrt::get_cancellation_token() };
    cancellation_token.callback([&]
    {
        std::cout << "Attempting to cancel...\n";
        BOOL result = ::CancelIoEx(file, &overlapped);
        if (result == 0)
        {
            std::cout << "Cancellation failed: " << ::GetLastError() << "\n";
            return;
        }

        std::cout << "Cancellation succeeded!";
    });
```

The OVERLAPPED struct is stored in the coroutine frame. This means that its allocation is included with the coroutine state which will be heap allocated, unless the compiler can optimize that heap allocation away. The 'overlapped' instance is used in the cancellation callback, and is also passed into the C-function that performs the underlying async call. But the OVERLAPPED struct cannot be copied, so captured by reference in the callback.

When a coroutine reaches the co_return statement, it performs the following (taken from [the cppreference.com documentation on coroutines](https://en.cppreference.com/w/cpp/language/coroutines))

* calls promise.return_void() for
  * co_return;
  * co_return expr where expr has type void
  * falling off the end of a void-returning coroutine. The behavior is undefined if the Promise type has no Promise::return_void() member function in this case.
* or calls promise.return_value(expr) for co_return expr where expr has non-void type
* destroys all variables with automatic storage duration in reverse order they were created.
* calls promise.final_suspend() and co_await's the result.

Notice that all variables are destroyed - in reverse order to the order that they were created - before 'promise.final_suspend()' is called. The cppwinrt promise doesn't transition out of the `AsyncStatus::Started` state until the await_suspend of the promise.final_suspend() result. So between the final two bullet points there's a window of time where the cancellation_callback is registered, the promise is still in the AsyncStatus::Started state, and would reference a destroyed object.

To work-around the lifetime problems I ended up having to std::make_shared the OVERLAPPED instance so that the cancellation callback's capture could extend the lifetime of the instance. The bottom-line; C++ coroutines have gone to great lengths to amortize/elide heap allocations for coroutines, but cppwinrt's cancellation callback is unable to use anything from the coroutine's state because it's lifetime is greater than the variables in the coroutine frame.

**Comment by kennykerr** [comment]
The cancellation callback is not part of the WinRT async support proper. It is a concession that was added to support interop with other libraries in order to support cancellation propagation. As soon as you mix such libraries together, it becomes very unlikely that their state machines will cooperate in such a way as to avoid extra allocations. There are many examples of this. The NT thread pool could allocate its tiny callback objects on the coroutine frame but it doesn't provide such an option. The WinRT async object's heap allocation could be elided in many cases but the C++ compiler implementations don't allow for this. Libraries like PPL and STL rely on their own internal reference counting (much like COM and WinRT) and thus cannot fold allocations across these disparate state machines and object models (even when their lifetimes are strict subsets). So for the sake of interop, we arrive at something that is interoperable but not necessarily the most efficient. 

Having said that, the tiny allocations required in such cases are usually fulfilled by fixed block allocators and the performance impact is rarely meaningful. WinRT's coroutine types are also focused on implementing API boundaries. For overlapped IO, I've tended to write customer coroutine types that are optimized for that purpose (living on the NT thread pool) while avoiding the ABI overhead required by WinRT.

**Comment by oldnewthing** [comment]
One way to do this is to revoke the cancellation callback when the nested coroutine completes (or throws). Something like

```cpp
template<typename Token>
struct with_cancellation
{
    with_cancellation(winrt::delegate<>&& cancel, Token token) : m_token(std::move(token))
    {
        m_token.callback(std::move(cancel));
    }
    ~with_cancellation() { m_token.callback(nullptr); }

    Token m_token;
};

auto cancellation_token{ co_await winrt::get_cancellation_token() };
auto operation = SomethingAsync();
{
    auto canceller = with_cancellation([&]{ CancelIoEx(...); }, cancellation_token);
    result = co_await operation;
    // destruct the canceller
}
```

Use of an RAII type ensures that the cancellation callback is revoked even on abnormal failure.

You can go even further and wrap the whole pattern.

```cpp
template<typename Async, typename Token>
struct with_cancellation
{
    with_cancellation(Async&& async, winrt::delegate<>&& cancel, Token token) : m_async(static_cast<Async&&>(async)), m_token(std::move(token))
    {
        m_token.callback([this] { m_async.Cancel(); });
    }
    ~with_cancellation()
    {
        m_token.callback(nullptr);
    }
    Async&& m_async;

    // Assumes that Async has a member co_await. Real life is more complicated.
    decltype(auto) operator co_await() { return m_async.operator co_await(); }
};

auto cancellation_token{ co_await winrt::get_cancellation_token() };
result = co_await with_cancellation(SomethingAsync(), [&] { CancelIoEx(...); }, cancellation_token);
```
