### ISSUE TITLE
Cannot use std::vector<T> or com_array<T> for Runtime class

### ISSUE THREAD

**Issue by anup-das** [microsoft/cppwinrt#696]
I need to create an C style array of object for my run-time class (.idl) within the same compilation unit but I am unable to do so.
```
// This can also be seen with plain C++ class that uses winrt::implements<>. The error received is same

// Simple steps to reproduce the issue - Use C++/WinRT CoreApp project template to generate an app
...
int __stdcall wWinMain(HINSTANCE, HINSTANCE, PWSTR, int)
{
std::vector<App> test;
test.resize(5);  //  error C2259: 'App': cannot instantiate abstract class
    
com_array<App> test; // error C2092: 'abstract declarator' array element type cannot be function or abstract class type
    
CoreApplication::Run(make<App>());
}

//github is removing <> thinking its some kind of markup. please edit and see code
```
Kindly suggest how this can be done. Thanks in advance.

**Comment by anup-das** [comment]
[App.zip](https://github.com/microsoft/cppwinrt/files/4949965/App.zip)

**Comment by kennykerr** [comment]
The reason this fails to compile (and the same reason [your last issue failed to compile](https://github.com/microsoft/cppwinrt/issues/693#issuecomment-661270889)) is because you're trying to create an array of your implementation type rather than the projected type. You need to create a container of the projected type. 

That's what `use_make_function_to_create_this_object` is trying to tell you. More info here:

https://kennykerr.ca/2019/05/08/cppwinrt-diagnosing-direct-allocations/

Yes, you need to use `make` to create the individual implementation objects but the the type of the resulting container must be of the resulting projected type. Typically that's the class or interface you're implementing. Yes, that means each object is an individual heap allocation, but that's the nature of the reference counted object model used by WinRT. If you need a contiguous sequence of objects within a single allocation you may be looking for something other than WinRT.
