### ISSUE TITLE
Can winrt::event deliver invocations asynchronously?

### ISSUE THREAD

**Issue by jonwis** [microsoft/cppwinrt#724]
Currently, `winrt::delegate<T>::operator()` delivers its invocations on the calling thread. This can be problematic if the delegate _implementation_ is not reentrant, or if the invocation is advisory-only.  There's an internal implementation of a WIL type that creates a separate thread to deliver the invoke calls.  While this can lead to unnecessary thread creation, supporting a mode of "deliver this invoke async" as part of the delegate's traits directly would be useful.

Implementations can do this themselves, however:

```c++
template<typename Q> fire_and_forget do_async(Q&& action) 
{
    typename remove_reference<Q>::type stored { std::move(action) };
    co_await resume_background();
    stored();
}
void MyType::SetValue(hstring const& value) 
{
    {
        auto lock = lock_self();
        m_value = value;
    }
    do_async([self = get_strong()] {
        m_valueUpdatedEvent(self, m_value);
    });
}
```

**Comment by kennykerr** [comment]
Sounds like https://github.com/microsoft/cppwinrt/issues/361 - is there enough demand to add such alternatives to C++/WinRT itself?

**Comment by jonwis** [comment]
We're finding that event delivery and lock holding are real problems.  Async invocation avoids all those concerns by triggering the event "elsewhere" and letting delegates/marshaling handle any thread affinity problems.

It's fine to not add a specific type to C++/winrt, but we should figure out and describe the "best answer" for people trying to accomplish this without support in the projection.

Is the `do_async` above correct enough that we would tell people "here is how you replace `wil::AsyncEventSource` when moving to C++/WinRT?" (note: there's at least 143 hits internally for `AsyncEventSource*`.)

I _assume_ we'd need versions for the other projections as well...

**Comment by kennykerr** [comment]
We could pretty easily write a `winrt::async_event` that is both non-blocking and scalable backed on the NT thread pool. The solution above is ok, but not parallel and sufficiently contrived that it would probably be better to provide a canned implementation. I can also experiment with making this the default for Rust. We probably can't do that for C++ since Xaml is implemented with C++/WinRT and their delegates are dodgy.

**Comment by jonwis** [comment]
This came up in an API reps meeting recently and where we landed was that _most_ events should be raised using `Async` unless you needed to deal with a `.Handled` style model (like lots of UI-related events.)  The delegates (and the event's use of agile & marshaling) "make it right."  Definitely we can't make the default behavior of event async (breaking behavioral change) but having this be an easily switchable option would be great.

Thanks!

**Comment by jonwis** [comment]
The current WRL implementation doesn't attempt to do parallel delivery of events; it just delivers them all in a block from a new thread. Maybe that's v0 of the implementation, and v1 is the thread-per-handler model? Like `async_event` and `async_parallel_event` or a traits indicating how to fan out?

Out of curiosity, why the NT threadpool instead of some C++ built-in like `std::thread` or the coroutine model above?

**Comment by kennykerr** [comment]
It's about efficiency. Using `std::thread` on Windows is rarely a good idea because it burns a dedicated thread, which leads to overscheduling. The NT threadpool avoids this as it has an intimate relationship with the scheduler. C++/WinRT's coroutine support is good because it does the same thing under the hood. It's not quite as good as writing directly against the threadpool because unfortunately both require an allocation so you end up with a slightly less efficient allocation pattern. I've asked the threadpool owners to fix this but they have declined sadly. Perhaps in future when coroutines are the norm they may relent. 😉 

Anyway, sorry for the delay. I'll try to throw something together this week. I've been rather swamped with [Rust for Windows](https://github.com/microsoft/windows-rs). But I'd rather just have a single parallel model than support different modes. I'll whip up an `async_event` and you can take it for a spin before I bake it into C++/WinRT.

**Comment by kennykerr** [comment]
OK, I have an async version working. Here's an example. I'll get a PR out shortly.

```C++
int main()
{
    event<EventHandler<int>> sync;
    auto sync_start = get_start_time();

    for (int i = 0; i != 5; ++i)
    {
        sync.add([=](auto&&, int args)
            {
                printf("sync=%d args=%d elapsed=%lld\n", i, args, get_elapsed_time(sync_start));
                Sleep(500);
            });
    }

    sync(nullptr, 123);
    printf("\n");

    async_event<EventHandler<int>> async;
    auto async_start = get_start_time();

    for (int i = 0; i != 5; ++i)
    {
        async.add([=](auto&&, int args)
            {
                printf("async=%d args=%d elapsed=%lld\n", i, args, get_elapsed_time(async_start));
                Sleep(500);
            });
    }

    async(nullptr, 456).get();
    printf("\n");
 }
```

Here's the output:

```
sync=0 args=123 elapsed=0
sync=1 args=123 elapsed=505
sync=2 args=123 elapsed=1013
sync=3 args=123 elapsed=1522
sync=4 args=123 elapsed=2031

async=0 args=456 elapsed=0
async=1 args=456 elapsed=0
async=2 args=456 elapsed=0
async=3 args=456 elapsed=0
async=4 args=456 elapsed=1
```
