### ISSUE TITLE
No ranges support for collection types?

### ISSUE THREAD

**Issue by zh4ui** [microsoft/cppwinrt#807]
Hi!

Just to confirm. For the collection types, e.g. IVector, IMap. Currently there is no c++20 ranges support, right?

**Comment by kennykerr** [comment]
That's right - I don't yet know what would be involved in lighting that up. If you have, feel free to outline an approach and we can talk it through.

**Comment by sylveon** [comment]
It seems that the issue is that std::ranges::_Begin::_Has_ADL doesn't matches for cppwinrt types, meaning that `std::ranges::begin` is disabled, this making the `std::ranges::range` concept that everything else relies upon not match.

**Comment by sylveon** [comment]
The latest version supports C++ ranges now @zh4ui. There are errors in the IDE, but this is caused by IntelliSense and might be fixed soon™ (see https://github.com/microsoft/STL/issues/1621).

For example:
![image](https://user-images.githubusercontent.com/6440374/112902404-11147b00-90b4-11eb-8983-15b66f1355b8.png)
