### ISSUE TITLE
[Regression] Resolving metadata fails when referencing a C++/WinRT project from a C# UWP project

### ISSUE THREAD

**Issue by jbrianceau** [microsoft/cppwinrt#809]
_Original issue opened by @matthew4850 in https://github.com/dotnet/msbuild/issues/5412_

Since CppWinRT nuget version `2.0.191023.3`, generating the appxbundle of C# UWP project consuming a CppWinRT component fails because of a `Metadata file [path] could not be found` error.

See https://github.com/dotnet/msbuild/issues/5412 for further details and a sample solution to repro the issue.

Note: here are the results using different releases of CppWinRT nuget:
| CppWinRT nuget release | Issue does repro? |
|:-:|:-:|
| Microsoft.Windows.CppWinRT.2.0.191018.6 | No |
| Microsoft.Windows.CppWinRT.2.0.191023.3 | Yes |
| Microsoft.Windows.CppWinRT.2.0.200316.3 | Yes |
| Microsoft.Windows.CppWinRT.2.0.201113.7<br/>(current latest release) | Yes |

**Comment by kennykerr** [comment]
Thanks Julien, unfortunately I don't have any experience with msbuild. Build and package management with msbuild/nuget has been a longstanding problem. I recently [reverted all the changes to msbuild](https://github.com/microsoft/cppwinrt/pull/793) support in an attempt to stabilize a bit. If someone from the msbuild team would like to contribute a fix I'd be happy to look at it. Otherwise, there isn't much I can do. @jlaanstra is [trying to fix things](https://github.com/microsoft/cppwinrt/pull/796) but that's not his day job either and without serious review by the msbuild team I'm not sure we can accept that either.

**Comment by raffaeler** [comment]
@jbrianceau I am currently using:
- CppWinRT project (compile for desktop removing `<AppContainerApplication>false</AppContainerApplication>`): version 2.0.201113.7 
- Projection assembly (.NET 5.0) using Microsoft.Windows.CsWinRT version 1.1.0
- C# Console client (.NET 5.0)

This solution compile and works correctly.

**Comment by jbrianceau** [comment]
For the record, fix is available in the [Microsoft.Windows.CppWinRT.2.0.201217.4](https://github.com/microsoft/cppwinrt/releases/tag/2.0.201217.4) nuget release.
