### ISSUE TITLE
Improve/fix dev inner loops and docs for contributors

### ISSUE THREAD

**Issue by benstevens48** [microsoft/cppwinrt#821]
I just contributed a pull request, but the only way I could test my changes was to run the full build_test_all.cmd. The section in the readme describing the dev inner loop had some issues and was not detailed enough.

Firstly there is an issue which can probably be considered a bug, which is that the cppwinrt version specified in the props file is 2.3.4.5, whereas the one specified in the build_nuget.cmd, build_test_all.cmd, build_vsix.cmd files is 1.2.3.4. This can result in problems if you mix and match between running these scripts and building using Visual Studio. I kept on getting version mismatch errors.

Secondly, the description of the dev inner loop in the readme isn't very helpful. Basically, I was changing one of the files in strings (base_collections_base.h), and then I wanted to test the results. However, I wasn't able to work out what steps I needed to take to compile everything before running tests. Building the solution in Visual Studio after making the change simply said that everything was up to date. Even rebuild all didn't seem to work. I had to delete the _build folder and start from the beginning. Alternatively, I could run build_test_all.cmd.

Thirdly, it would be nice if the build_nuget.cmd file would use the same method for ensuring nuget as build_test_all.cmd, i.e.
```
if not exist ".\.nuget" mkdir ".\.nuget"
if not exist ".\.nuget\nuget.exe" powershell -Command "Invoke-WebRequest https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -OutFile .\.nuget\nuget.exe"
```
then use nuget.exe in that folder instead of requiring nuget to be on the path.

Fourthly, I'm not sure what the file compile_tests.cmd is for. I thought it might build the tests, but for some reason it refers to a directory 3 levels above the current one.

Finally, there's probably nothing you can do about this, but the solution folder is very large after building - over 15GB! I was running out of space on my PC and this resulted in a lot of problems like segmentation faults reported when running the tests etc.

Perhaps it would also be useful to explain the architecture of the project more. I'm starting to think that the strings files end up being compiled into the cppwinrt.exe program, but I didn't realise that to start with as I though maybe they were just copied somewhere.

**Comment by kennykerr** [comment]
The header files in the `strings` folder are encoded as C++ string literals by the `prebuild` project and then included by the `cppwinrt` project. The `cppwinrt` project produces the `cppwinrt.exe` executable that generates the C++/WinRT library and namespace headers that all of the remaining test projects rely on. That is why the build instructions indicate that the `prebuild` and `cppwinrt` projects need to be built first. It mentions that you should build their `Release` configuration only because running `cppwinrt` an an unoptimized binary is exceedingly slow. Once you've built `cppwinrt` you need to generate the headers into a location where the remaining projects will find them. That's what `build_projection.cmd` does. Again, you can run this in a variety of ways depending on what configuration you'd like to test but we generally test with x64 Debug locally. 

Building and testing `cppwinrt` locally is not trivial, but makes some sense once you get the hang of the flow. As for the rest of the build scripts, I only use `build_projection.cmd` and `run_tests.cmd`. The rest was added at various times by different people to support CI and signed builds, so I'm hesitant to change those.

**Comment by benstevens48** [comment]
@kennykerr - OK, thanks - any chance you could add some of that explanation to the readme?

I think it would be worth cleaning up the cmd scripts and fixing the version mismatch and nuget convenience issue, but I guess it's not that important.

I think I didn't understand that the all the steps in the description of the dev loop were required every time. I think the line `Build the x64 Release configuration of the prebuild and cppwinrt projects only. Do not attempt to build anything else just yet.` made me think that was a one-time step. Also, I probably forgot to change the configuration between Debug and Release.

Do you really do all those steps manually each time? Wouldn't it be better to run the first 4 steps using a script? Although I actually found that `build_test_all.cmd` didn't take too long. I'm struggling to build without segmentation faults though. I think maybe I don't have enough RAM, although I would have thought 8GB is sufficient.

**Comment by kennykerr** [comment]
It really depends on what you're trying to accomplish. Building and running `cppwinrt.exe` is pretty quick and doesn't require a lot of memory - it's very efficient. Building the resulting tests can take a huge amount of memory and some time to properly build and run, but they're exhaustive for a reason.

Usually, I'll build `cppwinrt` once and then sit in the `scratch` project testing things, tweaking the generated headers, quickly rebuilding just `scratch` to verify - this is my inner loop. Only once I'm happy will I copy over the changes to the original compiler, rebuild everything, and make sure the tests are all in good shape, add any additional tests, and I'm done.
