### ISSUE TITLE
C++/WinRT component generation incorrectly includes types in a -ref WinMD if a substring of their type and namespace also appears in the -in WinMD

### ISSUE THREAD

**Issue by llongley** [microsoft/cppwinrt#835]
I've created two WinMDs that demonstrate the issue here:

[CppWinRTGenerationBugRepro.zip](https://github.com/microsoft/cppwinrt/files/5785028/CppWinRTGenerationBugRepro.zip)

Extract them to (say) C:\Temp, then run this C++/WinRT command:

`cppwinrt.exe -in C:\Temp\Comp.winmd -ref C:\Temp\Ref.winmd -ref 10.0.18362.0 -out D:\Temp\winrt -comp`

The only type in Comp.winmd is `ReproClass`, so that should be the only class that has an entry created for it in D:\Temp\winrt\CppWinRTGenerationBugRepro.  However, the type `ReproClassInRef` in Ref.winmd also has an entry created as well.  Also interesting is that `NoReproClass`, also in Ref.winmd, does not have an entry created for it.  `ReproClassInRef` has the same namespace as `ReproClass` and contains "ReproClass" as a substring of its name, so it appears as though the C++/WinRT generation logic is incorrectly including it as a type needing generation.

I'm currently able to work around this by adding an explicit `-exclude` directive to the C++/WinRT parameters that removes from consideration the types that should be excluded automatically, but it'd be nice not to need to do so.

**Comment by kennykerr** [comment]
Hi Luke, sorry for the confusion. The command line arguments are a little complicated due to the historical evolution of the cppwinrt compiler. Unfortunately, we have some very large and diverse projects that now rely on this behavior and are thus unable to change it. I actually tried to clean this up between v1 and v2 but ultimately had to ensure command line compatibility. As you've noted, there are command line options available to give you precise control over what is included or excluded. So I'm glad you're unblocked. Oh, for a time machine. 😉
