### ISSUE TITLE
Can't pass collection of a derived type to a collection that asks an interface

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/cppwinrt#853]
Windows.Storage.StorageFile implements IStorageItem2 so passing an IVectorView of StorageFile for a method that asks for an IVectorView of IStorageItem2 should work but I get this compiler error: `no suitable user-defined conversion from "winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Storage::StorageFile>" to "const winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Storage::IStorageItem2>&" exists`

**Comment by Jaiganeshkumaran** [comment]
I found a workaround and seems to be valid: *reinterpret_cast<IVectorView<IStorageItem2>*>((void*)&files)

**Comment by kennykerr** [comment]
C++/WinRT provides all of the verifiably safe conversions. If the compiler tells you a conversion does not exist, it is very unlikely that `reinterpret_cast` is correct. I suggest you make a copy of the collection because while the `StorageFile` class implements the `IStorageItem2` interface, their memory layouts are not compatible.
