### ISSUE TITLE
Generated sources file should delete constructor for static classes

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/cppwinrt#915]
Today the generated sources file from your IDL file sets the constructor as default instead of delete for static classes.

**Comment by kennykerr** [comment]
The implementation class need not have a deleted constructor - the projection will prevent any construction so long as the metadata omits constructors. The developer is free to make this change directly. The generated class is merely a suggestion. Often the constructor is needed internally, which is why it isn't deleted to begin with.

**Comment by Jaiganeshkumaran** [comment]
But a static class definitely means it should not be constructed from the implementation size at any point
