### ISSUE TITLE
Overload winrt::to_hstring for IInspectable

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/cppwinrt#942]
Sometimes you may not what exactly the type is but still want a readable string representation. In C++/CX, you could use the Object::ToString which would return the most appropriate string representation of the object. This has many uses eg: string formatting. Please add an overload of winrt::to_hstring for IInspectable. If the object represents a boxed value, unbox it and return the string representation of that. If the object implements IStringable, return the result of the ToString method and otherwise just return the type name.

**Comment by kennykerr** [comment]
Thanks for the suggestion. The main caution I would have is around testing and supporting the stringification of boxed values, which is unlikely to work reliably in all cases. I do know that the to_hstring overloads have historically been problematic due to SFINAE but perhaps that's less of an issue these days. Give @oldnewthing or @DefaultRyan a few days and if they don't have concerns/suggestions feel free to contribute a PR for consideration.

**Comment by sylveon** [comment]
I think this might be an issue with enums since they aren't IReference<underlying_type_t<MyEnum>> when boxed

**Comment by kennykerr** [comment]
Right, and unless this is a very clean and isolated addition it would be unlikely to survive review due to compat risks. This is a case where it may be simpler for you to just write and use your own helper function.

**Comment by oldnewthing** [comment]
Even C++/CX did a bad job of "everything supports `ToString()`". If you have an `IBox<int>`, calling `ToString()` does not return the stringified boxed integer. It just returns `IReference`int`, which is not very useful.

The compat issue is valid, because we explicitly permit apps to add additional overloads of `to_hstring`, and if they had added one for `IInspectable`, we would have a build break.

You can certainly add an overload in your own project. You can also add it to [WIL](http://github.com/microsoft/wil/). It has a `wil/cppwinrt.h` that would be a suitable place for "extra helpers that do not require access to C++/WinRT internals". I think that would be better than trying to add it to core C++/WinRT.
