### ISSUE TITLE
`winrt::array_view` should support the `std::byte` type.

### ISSUE THREAD

**Issue by shelllet** [microsoft/cppwinrt#970]
c++17 introduced a new type: std::byte.  
winrt only works above c++17, so `winrt::array_view` should support the `std::byte` type.
```
1>winrt\base.h(3616,23): error C2664: 'winrt::array_view<uint8_t>::array_view(unsigned char *,winrt::array_view<uint8_t>::size_type) noexcept': cannot convert argument 1 from '_Ty *' to 'unsigned char *'
1>        with
1>        [
1>            _Ty=std::byte
1>        ] (compiling source file *.cpp)
```

**Comment by Jaiganeshkumaran** [comment]
std::byte isn't implicitly convertible to uint8_t. Either change the type from array_view<uint8_t> to array_view<std::byte> or use a cast.

**Comment by kennykerr** [comment]
Is there a compelling reason to support this? WinRT has a closed set of primitive types and `uint8_t` is the unsigned byte representation that we use in C++.

**Comment by shelllet** [comment]
i think  there doen't seems to be a necessary compiling reasons, except for the performance loss when there is a large size of array.
A project developed by 'winrt' and 'std c++' and other c++ libraries. There seems to be a lot of areas that need to be converted accordingly. especially container class.

**Comment by sylveon** [comment]
`reinterpret_cast` between `std::byte` and `unsigned char` is well-defined, so there is no need to perform any copy.

**Comment by kennykerr** [comment]
The difficulty is that `uint8_t` is already used to represent this concept and adding support for `byte` would necessarily require `byte` - as well as any potentially recursive template instantiations of `byte` - to be implicitly convertible to and from `uint8_t` - and its corresponding instantiations - in order for WinRT APIs that expect `uint8_t` to work. This is further complicated because WinRT requires that unique type signatures be generated in order to produce generic `GUID` values for interfaces. This is all doable but I just don't see the value in adding this complexity when, as @sylveon pointed out, you can just `reinterpret_cast` your values as needed.

**Comment by shelllet** [comment]
That means that `cppwinrt` tightly supports the smallest `c++` types, and regular c++ 
types to `winrt ` types requires explicit type conversions, including those required by some algorithms, is this by design?

**Comment by kennykerr** [comment]
In practice, WinRT collections are meant for interop across languages and ABI boundaries. They are not ideal for compute and algorithms because of the ABI overhead.
