### ISSUE TITLE
C++/WinRT fails to create generateXamlTypeInfo.g.cpp if "Scan Sources for Module Dependencies" is set to yes

### ISSUE THREAD

**Issue by pjmlp** [microsoft/cppwinrt#988]
While trying to use modules in a C++/WinRT project, I came into a strange behaviour.

On any random UWP C++/WinRT project.

1- Enable "_Scan Sources for Module Dependencies_"
2- Rebuild solution
3- It will fail with _"c1xx : fatal error C1083: Cannot open source file: 'Generated Files\XamlTypeInfo.g.cpp': No such file or directory"_
4- Disable "_Scan Sources for Module Dependencies_"
5- Rebuild solution
6- Everything compiled just fine

Versions:

C++/WinRT, 2.0.210722.2
Visual Studio, 16.10.4

**Comment by sylveon** [comment]
XamlTypeInfo.g.cpp is generated by the xaml compiler, not cppwinrt.

The team for https://github.com/Microsoft/microsoft-ui-xaml owns the xaml compiler, so it would be nice if you could go open an issue over there.

**Comment by kennykerr** [comment]
And if its a Visual Studio issue you could try: https://developercommunity.visualstudio.com/search?space=62

Either way, this

**Comment by pjmlp** [comment]
This ping-pong with bug reporting just irritates me.

So XAML compiler is to blame for cl.exe settings?

**Comment by sylveon** [comment]
Scan source for modules dependencies is more than just a compiler switch, it integrates with the project system and does a two-pass build:
```
1>Scanning sources for module dependencies...
1>ConsoleApplication53.cpp
1>Compiling...
1>ConsoleApplication53.cpp
```

The first build is probably causing an issue here because it runs before the XAML Compiler could. So it should be Compile XAML > Scan module deps > Compile but currently it's Scan module deps > Compile XAML > Compile, causing the auto-generated files to not exist yet.

**Comment by pjmlp** [comment]
@sylveon Thanks for taking the time to provide a more comprehensible answer.

**Comment by kennykerr** [comment]
> This ping-pong with bug reporting just irritates me.

I feel your frustration but this repo is specifically for the cppwinrt code generator and I am, for the most part, the only developer at Microsoft who is monitoring issues here. So unless the issue is something that can addressed in the cppwinrt code generator itself, creating an issue here is not going help, which is why I try to point folks to a more appropriate forum.
